### ISSUE TITLE
Login problem with extended controller

### ISSUE THREAD

**Issue by dragoialexandru1997** [CakeDC/users#1025]
Hello.
I want to add users plugin to my project, but i want to extend controller because i want to change layout for some actions. I've done exactly what the documentation says, but i receive following error when i try to login.
If i don't extend the controller, the login action is working fine.

Error
[https://ibb.co/3d8JjCM](url)

**Comment by dragoialexandru1997** [comment]
Problem sloved. I forget to add `$this->loadComponent('CakeDC/Users.Setup');` to the controller. You can close this topic. Thanks

**Comment by rochamarcelo** [comment]
Thank you for letting us know.
