### ISSUE TITLE
Customizing flash messages

### ISSUE THREAD

**Issue by tgoeminne** [CakeDC/users#1030]
I was looking how to customise the flash messages usage. For instance when a user is not logged in and wants to access something that they would normally be allowed to access when logged in. I don't want to show the flash messages but just redirect them to login screen. How to remove the flash message? Is there a way to easily set this in permissions or config?

**Comment by rochamarcelo** [comment]
You could create a custom unauthorized handler based on https://github.com/CakeDC/users/blob/11.next-cake4/src/Middleware/UnauthorizedHandler/DefaultRedirectHandler.php

For more information see: https://github.com/CakeDC/users/blob/11.next-cake4/Docs/Documentation/Authorization.md#authorization-middleware

**Comment by tgoeminne** [comment]
Thanks
