### ISSUE TITLE
CakePHP 4.5 deprecations

### ISSUE THREAD

**Issue by LordSimal** [CakeDC/users#1037]
Just tried to update my app to current `4.next` CakePHP which is basically the next 4.5 release and got the following deprecations warnings for CakeDC/users version 11.2.0

* Deprecated: Table::_initializeSchema() is deprecated. Override `getSchema()` with a parent call instead in `src/Model/Table/UsersTable.php`
* As of 4.5.0 using query() is deprecated. Instead use `insertQuery()`, `deleteQuery()`, `selectQuery()` or `updateQuery()`.

**Comment by rochamarcelo** [comment]
Thank You.
