### ISSUE TITLE
timezone for users

### ISSUE THREAD

**Issue by tgoeminne** [CakeDC/users#1039]
This is a feature request to add timezone to the users plugin. Save timezone on register and update it on login through a hidden field that is binded to javascript? Anyone have done this, and can share some code/insight, or want to add to the plugin at all??

**Comment by rochamarcelo** [comment]
You should be able to do include new fields on register page, just overwrite the template. For login you could create a custom event listener for Plugin::EVENT_AFTER_LOGIN to save any data

**Comment by ajibarra** [comment]
Closing this because it has passed more than a year without any response
