### ISSUE TITLE
Data too long for column 'avatar' error for some Google accounts

### ISSUE THREAD

**Issue by inigoflores** [CakeDC/users#1084]
Some accounts after registering via Google are met with an Error 500.

This is the error message:

    2024-03-25 07:56:43 error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'avatar' at row 1 in /

In MySQL I have changed the column `avatar`  from `VARCHAR(255)` to `Text`, and the issue has been fixed.

This is an example of what the field `avatar` now stores for a specific account:

    https://lh3.googleusercontent.com/a-/ALV-UjW-UIASU6xvTs0WIWlDwNFZaGzCSb4P2AeF5K5d7_x63rvEqjHAARGe31WggkP_MOBFIWPPC3fV8ps9xLzfBClxUo2sNDc8o-l45ml4OdMqOZL7OoJ9mll1NF4IvCyncZ1CYhUNIrNNFLy1nzadbEMEKLeYnW8cBSFfmvIjWDt4YzFZ7jaAPKruhzaabk1ZfDQjngOu8I6VVvw3l7_xiPoMYF8d3FSlAN6oCZc_3dcTarp5S69rvwiTjHvOmdwmZiLAnEtYRvorpnP_tXG_ImEWLuI2dasT1n6vL8Ibr9h2fFChf4swLpvYyRNRducE0d7zi9Ts5-WOkry0owqeyNrJvjlGnGlaTnn893nHzlfgUh95Mgtt5ESMp4bh2qhLkAmRpe7sqPfyRqx3y8hQ43cgL_U2xPOnaViouINTdjv5C0yza0nIwZTC5EtxN5gUoMQIipWVZi_J-Cyzt0gRNByyjQG4XMnBzpalUnF4uWVRx4kpZAU1uonFdgLTxrcLLmj6ahZcUln5m2GVG1qmTbfGhOEhk8ca54zDzZ38Tnt-G4aDyriaqrJbqIVHrHGm70JJFIGj9Lw_eYZ9VE3J-JCe3a4S18qBw5Qod65T4MK3isHzi71mef1LR-YWQLymXYJsOVIgn__EBkXbk16LLDpKxoFay0Dz_QExhqnyZN23OnucB9LU3I5Np-7wZTlqs--Y7bV3QDrBwqujDekC9N2IBOhkURyw_LUAkDL3xBchDdL0b-MVVAMIhjKSC6LqS_Mh0IFK-RKqXwkQs_b2TCYm30u3aFUV_8pBIdFpIBiaIJQEvNxY00ytCNgRqT9dlX-1e0khFEQEpfMZlwotkhzbHvUIig3T4vcbRYJrKeD2c72o2ooBAY-UulUlBAq00aup6VqPdctETVgeGLqu-nM1nhB6Msg28ZDwFt21cptl_p3ZQWJDR_zVlDCjUdM0hmKRr7LoWlB0_KNVfJkQ=s96-c

Total length = 1027.

It's weird, because the rest of the image URLs from Google are 90 to 94 chars long.

The field size should be increased to allow storing these very long URLs.

**Comment by steinkel** [comment]
closed per https://github.com/CakeDC/users/pull/1094
