### ISSUE TITLE
Table class for alias `Users` could not be found.

### ISSUE THREAD

**Issue by mehov** [CakeDC/users#1104]
This is probably some kind of an edge case, but still.

My host application uses a bunch of home-made plugins and a copy of cakedc/users.

At some point I started inconsitently (most likely because I'm turning things on and off during development) getting this error. 

> Table class for alias `Users` could not be found.
> CORE/src/ORM/Locator/TableLocator.php at line 250

So I went to [`TableLocator::createInstance()`](https://github.com/cakephp/cakephp/blob/2ebf9550c49dc6a1c28d1deddfdbcefd3b4d6191/src/ORM/Locator/TableLocator.php#L218) and made it dump each call. I noticed there is indeed a call with `$alias` being just `Users`, while all other calls from other plugins were using dot notation `PluginName.TableAlias`. So I made a hotfix that prepends `CakeDC/Users` to the `Users` alias and it worked.

```
    protected function createInstance(string $alias, array $options): Table
    {
        if ($alias === 'Users') {
            $alias = 'CakeDC/Users.Users'
        }
        // ...
```

I don't have any tables in my host application, everything is in plugins. And in one plugin I have a table with name `Users`, but I don't think it's being called on boot; I'm not using it at all actually.

Is this something obvious or something that makes sense to be fixed on `cakedc/users` side, or should I look into my code deeper? Does it make sense to prefix all your calls to your tables with `CakeDC/Users` just to eliminate any possible conflicts?

CakePHP 5.1.2
cakedc/users 14.3

**Comment by mehov** [comment]
Alright, I think it's coming from here:

https://github.com/cakephp/authentication/blob/3583745feb37c5069930cd1661bb0723a8f64f99/src/Identifier/Resolver/OrmResolver.php#L39

```
    protected array $_defaultConfig = [
        'userModel' => 'Users',
        'finder' => 'all',
    ];
```

- Changing `'userModel'` from `'Users'` to `'CakeDC/Users.Users'` fixes it. 
- And changing it to `'Usersrrrrrrr'` makes the error say
   
   > Table class for alias `Usersrrrrrrr` could not be found.

So that confirms where it is coming from.

But that's inside `vendor/cakephp/authentication`, so unless it's an issue with that plugin, it has to be fixed either here or in my application/plugins.

**Comment by mehov** [comment]
Found relevant configuration: 

https://github.com/CakeDC/users/blob/8f8350a576da6e494c24649c6a4de90081fc8e5c/Docs/Documentation/Configuration.md?plain=1#L115

Added that to my `config/users.php`:

```
<?php
return [
    'Auth.Identifiers.Password.fields.username' => 'email',
    'Auth.Authenticators.Form.fields.username' => 'email',
    'Users.table' => 'CakeDC/Users.Users',
    'Users.Tos.required' => false,
    'Users.passwordMeter.enabled' => false,
    'Users.Profile.viewOthers' => false,
];
```

Seems to have fixed it.

**Comment by mehov** [comment]
The error is back.

Here's my `APP/config/Users.php`. Even though I did set the `Users.table`, something else seems to be overwriting it.

```
<?php
return [
    'Auth.Identifiers.Password.fields.username' => 'email',
    'Auth.Authenticators.Form.fields.username' => 'email',
    'Users.table' => 'CakeDC/Users.Users',
    'Users.Tos.required' => false,
    'Users.passwordMeter.enabled' => false,
    'Users.Profile.viewOthers' => false,
];
```

And I can confirm that this configuration is being loaded because when I set `'Users.passwordMeter.enabled' => true`, I can see the meter reappear on the `/register` page.

**Comment by mehov** [comment]
I traced the call stack from [`\Authentication\Identifier\Resolver\OrmResolver->__construct()`](https://github.com/cakephp/authentication/blob/3583745feb37c5069930cd1661bb0723a8f64f99/src/Identifier/Resolver/OrmResolver.php#L48) back to entry point

-  [`cakephp/authentication/src/Identifier/Resolver/ResolverAwareTrait.php->getResolver()`](https://github.com/cakephp/authentication/blob/3583745feb37c5069930cd1661bb0723a8f64f99/src/Identifier/Resolver/ResolverAwareTrait.php#L41)
- [`cakephp/authentication/src/Identifier/IdentifierCollection.php->_create()`](https://github.com/cakephp/authentication/blob/3583745feb37c5069930cd1661bb0723a8f64f99/src/Identifier/IdentifierCollection.php#L82)
- [`CakeDC/users/src/Loader/AuthenticationServiceLoader.php->loadIdentifiers()`](https://github.com/CakeDC/users/blob/8f8350a576da6e494c24649c6a4de90081fc8e5c/src/Loader/AuthenticationServiceLoader.php#L58)

I can see that the `$config` that ends up in [`OrmResolver->__construct()`](https://github.com/cakephp/authentication/blob/3583745feb37c5069930cd1661bb0723a8f64f99/src/Identifier/Resolver/OrmResolver.php#L48) originates from [`AuthenticationServiceLoader->loadIdentifiers()`](https://github.com/CakeDC/users/blob/8f8350a576da6e494c24649c6a4de90081fc8e5c/src/Loader/AuthenticationServiceLoader.php#L54). Because that `$config` does not contain the `userModel` key, `OrmResolver` defaults to its `$_defaultConfig` where `userModel` is `Users`.

Does this mean that `Users.table` has no effect?

Anyway, I can think of three ways to (hot)fix this:

1. Add the following to `AuthenticationServiceLoader->loadIdentifiers()` [right before it does `$service->loadIdentifier($identifier, $options);`](https://github.com/CakeDC/users/blob/8f8350a576da6e494c24649c6a4de90081fc8e5c/src/Loader/AuthenticationServiceLoader.php#L57): 
    
        if (isset($options['resolver'])
        && isset($options['resolver']['className'])
        && $options['resolver']['className']==='Authentication.Orm') {
            $configured_users_table = \Cake\Core\Configure::read('Users.table');
            if (!empty($configured_users_table)) {
                $options['resolver']['userModel'] = $configured_users_table;
            }
        }

2. Add the following to [`CakeDC/users/config/bootstrap.php`](https://github.com/CakeDC/users/blob/8f8350a576da6e494c24649c6a4de90081fc8e5c/config/bootstrap.php#L22):
    
        $configured_users_table = Configure::read('Users.table');
        if (!empty($configured_users_table)) {
            Configure::write('Auth.Identifiers.Password.resolver.userModel', $configured_users_table);
        }

3. Do the `Configure::write('Auth.Identifiers.Password.resolver.userModel', Configure::read('Users.table'));` somewhere on my app level.

The important piece is of course to know why is this happening in my setup. I was able to find that this happens only if I have a specific plugin enabled, which *both* has a `Users` table (that actually does nothing) *and* hijacks every `Model.initialize` (but stops right away if the event is not coming from a model inside said plugin). So it shouldn't be causing any trouble, but it does.

I will do the aforementioned 3. just to get going for now, but I will keep the code, so if you need some more info or debug output, let me know

**Comment by steinkel** [comment]
In this case, you can change the UsersTable to another Alias, and use a custom users table https://github.com/CakeDC/users/blob/14.next-cake5/Docs/Documentation/Extending-the-Plugin.md so the 2 aliases won't collide in the table registry.

**Comment by mehov** [comment]
Thank you for your suggestions.

> you can change the UsersTable to another Alias

Sadly no because that other plugin is for a CMS which has the table named `Users` and I can't change that

> use a custom users table https://github.com/CakeDC/users/blob/14.next-cake5/Docs/Documentation/Extending-the-Plugin.md so the 2 aliases won't collide in the table registry

Sounds like an overkill. Meaning it's probably the way to do it, but I will keep `Configure::write('Auth.Identifiers.Password.resolver.userModel', Configure::read('Users.table'));` and revisit if it stops working.

Thanks again, I will close I guess because this still sounds like somewhat an edge case.
