### ISSUE TITLE
Setting of loginRedirect

### ISSUE THREAD

**Issue by davidyell** [CakeDC/users#130]
**Issue**
It's currently not possible, that I know of, to change the `loginRedirect` without extending the whole controller and either overriding or calling parent and then setting `loginRedirect` and returning.

**Proposed**
There needs to be a nicer way to configure the `loginRedirect` so that each user can specify it. I think that redirecting to the homepage isn't helpful in the majority of cases as it might be a transparent change to the user. They might not notice that 'Login' is now 'My Account' for example.

**Idea**
I'd suggest just removing this configuration value from the plugins `UsersController` ln178. This way, it will allow people to configure it in their own `AppController::beforeFilter()` giving them the flexibility to change it as they want.

I'm not sure if there is a way to pass configuration through into the Auth component from outside the plugin, short of putting something in the `CakePlugin::load()`, or using a `Configure::write()` value similar to `allowRegistration`.

**Discussion**
Would this make a reasonable solution? Having had a quick think about it, to me, it feels wrong to extend a whole controller for a single setting. I did try using my `AppController::beforeRender()` to overwrite the setting after all the beforeFilters had run, but without success.

Is there a more elegant way to get the plugin to take on a specific applications Auth settings?

**Comment by ironbone** [comment]
As I see at this moment it is possible to set the redirection by adding to your users.php, or just returning
return [
    'Auth.loginRedirect.controller' => 'Users',
    'Auth.loginRedirect.plugin' => null,
    'Auth.logoutRedirect.controller' => 'Pages',
    'Auth.logoutRedirect.plugin' => null,
];
