### ISSUE TITLE
If a password is present, the password will be hashed again.

### ISSUE THREAD

**Issue by aokazu** [CakeDC/users#208]
I am grateful to this plug-in.
I found a bug.
Thank you confirm.

line 857  of Model/User.php 

//if (!empty($this->data[$this->alias]['password'])) {
if (!empty($postData['password'])) {

**Comment by xDarkShadowKnightx** [comment]
Yeah I just stumbled upon this same issue.. nice to know I'm not the only one!

**Comment by dsinni** [comment]
Had the same problem. I commented out this line (about 858) in the edit method of the User model and that fixed the issue.

// $this->data[$this->alias]['password'] = $this->hash($this->data[$this->alias]['password'], 'sha1', true);

**Comment by steinkel** [comment]
thank you for reporting! merged and fixed into develop.
