### ISSUE TITLE
Association models not working and duplicate record requests...

### ISSUE THREAD

**Issue by gooseleggs** [CakeDC/users#211]
Been struggling for the last couple of days wondering why my HABTM relationship is not working in my AppUser model, and I think I have found the cause.  In the edit function of the model, we call getUserForEditing to allow the user to provide the details.  However, if the PostData is empty, ie, we haven't loaded any data then we return from the function without a return value.

In the Admin_edit controller function, we are checking a function result which may not be returned.  Also, in this function, if the "if (empty($this->request->data))" should we should be calling the getUserForEditing function to get the user data, instead of reading the record (without associations)?

So, I think the model edit function changes should be:

			} else {
				return $postData;
			}
		}
+		else return $user;   // if postdata is null, then return user defined results
	}

and the controller admin_edit changes:

    	if (empty($this->request->data)) {
-   		$this->request->data = $this->{$this->modelClass}->read(null, $userId);
+    		$this->request->data = $this->{$this->modelClass}->getUserForEditing($userId);
    		unset($this->request->data[$this->modelClass]['password']);

Anyone else have this issue?

**Comment by steinkel** [comment]
Hi @gooseleggs is this still an issue for you?
