### ISSUE TITLE
method isAuthorized - Access to admin_action*

### ISSUE THREAD

**Issue by manfe** [CakeDC/users#212]
I really try to find any answer looking at issues and google, but I couldn't find.

Any user registered can access the page admin_index, admin_edit etc.

Trying to use the isAuthorized method I could see that the method isn't called never.

I tried to extend but no success, how do you guys block the access to pages that only admin can access? 

Thank you so much. There are a some things that need to be  on documentation (I will help with it).

**Comment by dsinni** [comment]
I'm also having this problem. I tried setting $this->Auth->authorize = 'Controller' in the AppController beforeFilter method and it seems to do more harm than good. Is there a relatively simple way to restrict admin access in conjunction with the plugin? Any insight would be greatly appreciated. Thanks.

**Comment by steinkel** [comment]
Hi, you could extend the UsersController https://github.com/CakeDC/users/blob/develop/Docs/Documentation/Auth-in-the-Users-Plugin.md and override the _setupAuth metod to customize how the Auth is configured, adding Controller authorize for example and checking the prefix and role in the isAuthorized method.

Thank you!

**Comment by dsinni** [comment]
Thanks, Jorge! I'll give it a shot.


Cheers,

Dan
