### ISSUE TITLE
{$this->modelClass} and getMailInstance() on protected function _getMailInstance()

### ISSUE THREAD

**Issue by hjdc** [CakeDC/users#214]
Hello,

I'm new, can you help me? to solve this problem.
The variable $this->modelClass returns 0 or 1 when it should send "user", I think.

Thank you

/********************************/

Fatal Error
Error: Call to a member function getMailInstance() on a non-object	
File: /home/testmars/www/app/Plugin/Users/Controller/UsersController.php	
Line: 866

/*********************/

CAKE_VERSION	2.6.2
Php Version	5.3.3-7+squeeze25
bootstrap.php : 

CakePlugin::load('Utils');
CakePlugin::load('DebugKit');
CakePlugin::load('Search');
CakePlugin::load('Users', array(
	'routes' => true
));

Configure::write('Users.disableSlugs', true);
Configure::write('Users.emailConfig', 'default');
Configure::write('Users.roles', array(
	'admin' => 'Admin',
	'registered' => 'Registered'
));

Configure::write('Users.defaultRole', 'user_registered');
Configure::write('Users.allowRegistration', false);

**Comment by steinkel** [comment]
hi @hjdc could you debug the contents of the $this->Users and check if it's properly initialized?

**Comment by steinkel** [comment]
I'll close this one until feedback is provided, please feel free to reopen later.
