### ISSUE TITLE
routing issue plugins\Users\config\routes.php on line 22

### ISSUE THREAD

**Issue by surjit** [CakeDC/users#232]
2015-08-16 07:47:22 Error: Fatal Error (1): Unsupported operand types in [vendor\cakephp\cakephp\src\Routing\RouteBuilder.php, line 390]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??

2015-08-16 07:47:23 Error: [Cake\Error\FatalErrorException] Unsupported operand types
Request URL: /login
Stack Trace:
#0 vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Unsupported ope...', 'E:\\owned\\localy...', 390)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}

2015-08-16 07:47:23 Warning: Warning (4096): Argument 2 passed to Cake\Routing\RouteBuilder::connect() must be of the type array, null given, called in plugins\Users\config\routes.php on line 22 and defined in [vendor\cakephp\cakephp\src\Routing\RouteBuilder.php, line 387]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Routing\RouteBuilder::connect() - CORE\src\Routing\RouteBuilder.php, line 387
Cake\Core\Plugin::{closure}() - ROOT\plugins\Users\config\routes.php, line 22
Cake\Routing\RouteBuilder::scope() - CORE\src\Routing\RouteBuilder.php, line 593
Cake\Routing\Router::scope() - CORE\src\Routing\Router.php, line 886
include - ROOT\plugins\Users\config\routes.php, line 23
Cake\Core\Plugin::_includeFile() - CORE\src\Core\Plugin.php, line 390
Cake\Core\Plugin::routes() - CORE\src\Core\Plugin.php, line 342
Cake\Core\Plugin::routes() - CORE\src\Core\Plugin.php, line 331
include - ROOT\config\routes.php, line 95
Cake\Routing\Router::_loadRoutes() - CORE\src\Routing\Router.php, line 970
Cake\Routing\Router::parse() - CORE\src\Routing\Router.php, line 335
Cake\Routing\Filter\RoutingFilter::beforeDispatch() - CORE\src\Routing\Filter\RoutingFilter.php, line 53
Cake\Routing\DispatcherFilter::handle() - CORE\src\Routing\DispatcherFilter.php, line 145
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 389
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Routing\Dispatcher::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 62
[main] - ROOT\webroot\index.php, line 37

**Comment by steinkel** [comment]
hi @surjit this one was fixed here https://github.com/CakeDC/users/pull/233

Thank you for contributing this issue!
