### ISSUE TITLE
Email configuration not respected

### ISSUE THREAD

**Issue by BrianWendt** [CakeDC/users#236]
I'm trying to override the config for which email configuration to use.
`Configure::write('Users.emailConfig', 'smtp');`
I tried placing that in several different places including in UsersAppController.php and email.php but neither place seems to have any effect.

CakePHP 2.7.3

**Comment by omnuvito** [comment]
Hi @BrianWendt, The override must place it in the **bootstrap** file. I configured it and it took me all settings. Did you try to override the configuration on this file?
