### ISSUE TITLE
How to not remove plugin name from URL routes

### ISSUE THREAD

**Issue by emersonthis** [CakeDC/users#238]
It appears that by default, the prefix "users" appears before all URLs. So for example, unauthorized users get redirected to `/users/users/login`. What's the correct way to change it to `/users/login` ?

**Comment by emersonthis** [comment]
It seems to work when I add...

```
    $routes->connect('/users/login', ['plugin'=> 'Users', 'controller'=>'Users', 'action'=>'login']);
    $routes->connect('/users/logout', ['plugin'=> 'Users', 'controller'=>'Users', 'action'=>'logout']);
    $routes->connect('/users/register', ['plugin'=> 'Users', 'controller'=>'Users', 'action'=>'register']);
    ...
```

...to my `routes.php` but I suspect there's a config settings somewhere to do this more easily.

**Comment by steinkel** [comment]
Hi @emersonthis you did it right, overriding the routes in your main routes file is the way to go. Thanks
