### ISSUE TITLE
User login page

### ISSUE THREAD

**Issue by flangofas** [CakeDC/users#241]
I am using 3.x version and the config file doesn't affect the login page. All the configurations below are set to true.
- Users.RememberMe.active,
- Users.Registration.active, 
- Users.Email.required,
- Users.Social.login.

**Comment by steinkel** [comment]
Hi @flangofas what would you expect to happen based on these settings set to true in the login page?

**Comment by steinkel** [comment]
Closing this one, please @flangofas feel free to reopen with additional details to check & fix if needed. Thank you
