### ISSUE TITLE
Add support for Instagram social authentication

### ISSUE THREAD

**Issue by emersonthis** [CakeDC/users#242]
Judging from the [Instagram documentation](https://instagram.com/developer/authentication/), it looks like much of the logic from the Facebook auth can be recycled. If you'd like a PR for this, let me know and I might be able to take a crack at this myself.

**Comment by steinkel** [comment]
hi @emersonthis this would be nice, but please wait a couple days as we are finishing a mayor update on the feature/refactor-behavior branch for 3.x so you don't start working on this feature and get a lot of conflicts on merge. Thank you!

**Comment by ajibarra** [comment]
We have an alpha version of this working at feature/oauth branch. We decided to use league/oauth2-client instead. We still need to update docs and add twitter support but the you should be able to use it with multiple providers like google, instagram, facebook and linkedin. We will merge this into 3.1 branch once we add twitter support.
