### ISSUE TITLE
Add Google authentication

### ISSUE THREAD

**Issue by steinkel** [CakeDC/users#245]
Provide Google authentication, similar to current support for Twitter and Facebook Auth

**Comment by designway** [comment]
Maybe interesting to implement https://github.com/hybridauth/hybridauth
it includes OpenID, Facebook, Twitter, LinkedIn, Google, Yahoo, Windows Live, Foursquare and AOL
+ many more providers

And its a maintained repo ;)

**Comment by steinkel** [comment]
totally right @designway we decided to move to Hybrid and get rid of Opauth for Users

**Comment by designway** [comment]
Great :)

**Comment by ajibarra** [comment]
We have an alpha version of this working at feature/oauth branch. We decided to use league/oauth2-client instead. We still need to update docs  and add twitter support but the you should be able to use it with multiple providers like google, instagram, facebook and linkedin.
