### ISSUE TITLE
syntax error at or near "("           LINE 1: ... "token_expires" 

### ISSUE THREAD

**Issue by joserafael** [CakeDC/users#250]
Hello! nice work. 

Doing the migration show this error:

![captura de pantalla de 2015-09-25 10 42 02](https://cloud.githubusercontent.com/assets/60098/10104270/9f1b13d4-6372-11e5-8536-5696f5a7f896.png)

**Comment by steinkel** [comment]
It's fixed now in branch 3.1.x feel free to use it or wait for the next tag coming soon...

Thank you for submitting the issue @joserafael
