### ISSUE TITLE
Events register not fired after first social login and a  facebook hotfix api 2.4

### ISSUE THREAD

**Issue by designway** [CakeDC/users#251]
I had some issues:

The events beforeRegister and afterRegister are not fired after social login(first time)
Can be needed to send a welcome mail or something.

tos default filled in when first time login with social account

Facebook api version 2.4 is currently broken with https://github.com/opauth/facebook Facebook strategy for Opauth And it looks like its not maintained anymore.

So a small fix to get facebook with api version 2.4 working:
vendor/opauth/facebook/src/Facebook.php:141 
in function me($access_token)

replace:
```
$me = $this->http->get('https://graph.facebook.com/me', array('access_token' => $access_token));
```
with:
```
$me = $this->http->get('https://graph.facebook.com/me', array(
    'access_token' => $access_token, 
    'fields' => 'id,name,first_name,middle_name,last_name,age_range,gender,locale,timezone,verified,email'
));
```

**Comment by designway** [comment]
Forgot to mention that the facebook api works.. but you don't get any other fields like email etc.
with the hotfix you get all other fields like email address etc from facebook.

**Comment by steinkel** [comment]
@designway we've forked and fixed the issues with the facebook strategy, as the repo looks unmaintained now:

Add this to your composer.json file to get it fixed (email is coming back from Facebook again)

```
    "repositories":
    [
            {
                "type": "vcs",
                "url": "https://github.com/CakeDC/facebook.git"
            }
    ],
```

We'll take a look at the before/after register events.
About the tos, we'll need to add it to an "after register" page like we do now with the email when not provided by the social login process. Thank you for pointing that out.

**Comment by ajibarra** [comment]
@designway We have an alpha version of new oauth approach working at feature/oauth branch. We get rid of opauth and decided to use league/oauth2-client instead. We still need to update docs and add twitter support but the you should be able to use it with multiple providers like google, instagram, facebook and linkedin. We will merge this into 3.1 branch once we add twitter support.
