### ISSUE TITLE
Public SimpleRbac permissions

### ISSUE THREAD

**Issue by icex** [CakeDC/users#254]
This does not work:

        [
            'role' => '*',
            'controller' => ['Pages'],
            'action' => ['other', 'display'],
            'allowed' => true,
        ],

It still requires authentication. I want to allow some pages to be public(in this config, not hard-coded with auth->allow()). Any suggestions?

**Comment by ironbone** [comment]
The same question.

**Comment by icex** [comment]
I've solved this by setting this in AppController.php. I know it's a bit hacky but it works for me.

        if($this->Auth->user('id')=== null) {
            $this->Auth->setUser(['id'=> 0, 'group_id' => 3, 'role'=> 'guest']);
        }

**Comment by steinkel** [comment]
Hi @icex, keep in mind one thing is "allowing" a controller action, and another thing is setting a controller action as "authorized".

If you "allow" the action, you will not require login at all. In this case you should use $this->Auth->allow(...) http://book.cakephp.org/3.0/en/controllers/components/authentication.html#making-actions-public in your controller beforeFilter() callback.

If the action is not "allowed" you will require a logged in user, so you'll get redirected by Auth component to the login page, and after you are identified, you'll be able to match the action against any Authorize object configured, in this case, the SimpleRbacAuthorize.

Makes sense?
