### ISSUE TITLE
Not clear documentation

### ISSUE THREAD

**Issue by ironbone** [CakeDC/users#255]
The procedure described in 
https://github.com/CakeDC/users/blob/3.1.x/Docs/Documentation/Extending-the-Plugin.md
 will not work with some of your plugin templates.
For example in edit action you set a variable which name is equal to the alias of the table. 
In edit.ctp you use (for the mentioned variable) $Users which  will not work with the class  MyUsersTable without changing the alias.

I do not understand why you use such naming convention but there must be a reason.

**Comment by steinkel** [comment]
Hi @ironbone the idea behind the edit action (in SimpleCrudTrait) is to have a generic trait implementation for the basic crud actions using this trait, so the way the edit action and edit template is implemented would allow you to attach the trait to any other controller.

You will usually need to override the crud templates with your own templates in your project, in this case you can copy the provided example templates and override/update them with the markup needed for your project.

Does that answer your question?
