### ISSUE TITLE
Using this plugin with old database structures

### ISSUE THREAD

**Issue by davalb** [CakeDC/users#260]
I am using your plugin in a rewrite of a very old website. The database layout differs a little bit from the one used in your project. For instance is the name of the `users` table `customers` and `id` is `customer_id`. However, currently it is not possible for me to make changes to the database structure.
In order to make your plugin work I had to do some changes on its code and I thus lost the ability to easily update your plugin.
I wanted to know, if you would consider it an improvement of your plugin, if table and column names where made configurable. In a use case like mine I could just change the default-values in a config-file without touching the code itself. If you like the idea, I would try to implement it and send a PR.

**Comment by steinkel** [comment]
Hi @davalb, that's a good point, we were discussing internally to create a mapper configuration to allow "rename" the fields the plugin expects. 

We've already used the plugin using a legacy schema, extending the Users table and entity and using the accessors and mutators at the entity level to get the data the plugin expects internally. Then you just need to configure the parameter Users.table in configuration.

But, I think a matcher configuration could be cool, if you have the time send us a PR and we'll start discussion there...

Thank you!

**Comment by davalb** [comment]
Thanks for the answer, I will see if I can make do with extending the Users table and entity before. If not I will make that PR.

**Comment by steinkel** [comment]
Cool, thank you!
