### ISSUE TITLE
Login and logout url error

### ISSUE THREAD

**Issue by Penergy** [CakeDC/users#272]
Hi all,

I am following Blog tutorial and using Cakedc/users as my authenticate and authorize function. However, the url of the login and logout is wrong. 

In my case, the supposed url is http://localhost/blogTest/users/login. But the actual url is http://localhost/blogTest/users/users/login.  It is the same for logout.

Could anyone tell me how to solve this problem?

**Comment by omnuvito** [comment]
Hi @Penergy, if you're using CakePHP 2.x, you must configure in bootstrap the routes option: [Routing](https://github.com/CakeDC/users/blob/master/Docs/Documentation/Routing.md)
