### ISSUE TITLE
Refactor Social Login Implementation

### ISSUE THREAD

**Issue by ajibarra** [CakeDC/users#275]
We are switching from Opauth to league/oauthX-clients. 

Branch: feature/oauth

**Comment by ajibarra** [comment]
Work has been done for facebook/twitter/instagram/google and linkedin. 

@pedrofs please improve unit test coverage on this branch

**Comment by zamaliphe** [comment]
you have removed twitter in full

**Comment by steinkel** [comment]
@zamaliphe please note twitter is not removed, just processed with the specific oauth version it requires, please follow the documentation to configure twitter login

**Comment by steinkel** [comment]
closing this issue as already merged
