### ISSUE TITLE
Users table mapping

### ISSUE THREAD

**Issue by ajibarra** [CakeDC/users#276]
In some cases people have custom users tables that should be mapped to standard field in Users table. We should provide a way to map those fields.

**Comment by pedrofs** [comment]
Hi @ajibarra,

What do you think about defining some columns that can be customized? The most pertinent ones like `username`, `email`, `first_name`, `last_name`. I was also thinking about `password*`, but then I realized we will have to also work on setters and mutators to become flexible and follow column naming.

What do you think?

**Comment by steinkel** [comment]
I think this is maybe too work and added complexity for the benefits we provide... What do you think?

**Comment by pedrofs** [comment]
I agree. It will have a big impact to implement this and I'm not sure if it'll be much used by the community.

**Comment by ajibarra** [comment]
Agree too. Closing it.
