### ISSUE TITLE
Fresh installation

### ISSUE THREAD

**Issue by owenson** [CakeDC/users#278]
Fresh installation into 3.1, this is the result:  System is debian jessie

root@XXX ~www/owe/fpv # composer require opauth/facebook:1.0.x-dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for opauth/facebook 1.0.x-dev -> satisfiable by opauth/facebook[1.0.x-dev].
    - opauth/facebook 1.0.x-dev requires opauth/opauth ~1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
2 root@XXXXX ~www/owe/fpv # composer require opauth/twitter:1.0.x-dev                                                                                                                                     :(
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for opauth/twitter 1.0.x-dev -> satisfiable by opauth/twitter[1.0.x-dev].
    - opauth/twitter 1.0.x-dev requires opauth/opauth ~1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
2 root@XXXXX ~www/owe/fpv #

**Comment by ajibarra** [comment]
Hi @owenson, unfortunately it looks Opauth projects is abandoned so we moved to PHP League Oauth libraries in order to provide social authentication. 

Please pull the latest code from master and you will be able to enjoy the new features including FB login, TW login, Instagram, Google, LinkedIn.

Thanks for taking time to report issues.
