### ISSUE TITLE
[3.1] strtotime default locale issue

### ISSUE THREAD

**Issue by Pablushka** [CakeDC/users#279]
Greetings,

I'm using Users 3.1 on cakephp 3.1 with my local date and time configurations, as shows in bootstrap.php:
```
ini_set('intl.default_locale', 'es_AR');       // instead of 'en-US'
```

It changes the default  format of datetime types and breaks the function tokenExpired() in Model/Entity/User.php.

```
    public function tokenExpired()
    {
        return empty($this->token_expires) || strtotime($this->token_expires) < strtotime("now");
    }
```

The function always return true because strtotime($this->token_expires) always returns empty.

**Comment by steinkel** [comment]
This one was already fixed in master, anyway we've just refactored the User entity to use Time. Closing the issue as PR #314 was created.

Thank you!
