### ISSUE TITLE
Prefix redirection missing route

### ISSUE THREAD

**Issue by ahmadod** [CakeDC/users#280]
Hello
Thanks for your great piece of code
i had a problem with prefix usage in my app then i fixed it with adding  'prefix' => false in login action in config file , i suggest you to add this in your plugin

**Comment by steinkel** [comment]
Hi @ahmadod could you please add more details on how to reproduce the issue with the prefix?

Thank you

**Comment by drmonkeyninja** [comment]
@steinkel I've also experienced a similar issue when using a router prefix for an admin area.

I have the following in my routes.php file:-

```
Router::prefix('admin', function ($routes) {
    $routes->fallbacks('DashedRoute');
});
```

If I attempt to access the prefixed admin area, for example "/admin/pages", I get the error message:-

> Error: A route matching "array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'opauthInit', 'prefix' => 'admin', '_ext' => NULL, )" could not be found.

This is easily rectified by setting `'prefix' => false` on the `Auth.loginAction` and `Opauth.path` routes in the plugin's configuration. Is this perhaps something that could be set by default in the plugin, or should this remain up to the plugin user?

**Comment by steinkel** [comment]
I see, and it makes sense to have this configured by default. 
Thank you guys for pointing this out...

**Comment by ahmadod** [comment]
Hello . Yes , it will be better to have it by default
