### ISSUE TITLE
[3.1] How to change templates? 

### ISSUE THREAD

**Issue by sams** [CakeDC/users#282]
In the cake 2 version it was possible to do this. Would it be possible to have an option in config that enable the plugin to check the APP/src/Template/CakeDC/Users (with customised versions in there)

or is there a better way to achieve this?

**Comment by oussamac** [comment]
For CakePHP 3:
You should add a "Plugin" folder inside your "/src/template".

And copy the plugins view  files there and modify them accordingly.

You don't need any Config option.

**Comment by sams** [comment]
Thx. I've just read the contact-manager tutorial

http://book.cakephp.org/3.0/en/plugins.html#overriding-plugin-templates-from-inside-your-application

Cake 3 rocks

**Comment by steinkel** [comment]
:+1: we added a section to explain it in the docs too https://github.com/CakeDC/users/blob/3.1.x/Docs/Documentation/Extending-the-Plugin.md#updating-the-templates, let us know if this could be improved to make it easier for people to reuse the Plugin... thanks!

**Comment by llincoln** [comment]
In case anyone else is still on a hump with this: you just need:

{project_dir}/src/Template/Plugin/CakeDC/Users/Users/{templates_in_here}

**Comment by steinkel** [comment]
Let me add that to the docs... thanks!

**Comment by jarekgol** [comment]
You should add example from @llincoln because I tried few forms with lower and upper case (starting from cakephp manual my self), users and users/users and finally got here and only his answer was truely useful.

**Comment by rochamarcelo** [comment]
@jarekgol The recent doc has the information: https://github.com/CakeDC/users/blob/11.next-cake4/Docs/Documentation/Extending-the-Plugin.md#updating-the-templates
