### ISSUE TITLE
Install on cakephp 3.2.1 your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by vnt** [CakeDC/users#289]
Hi,
I have tried to install the plugin on cakephp 3.2.1 and I receive the follow error:

composer require cakedc/users:3.1.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakedc/users 3.1.0 requires cakephp/cakephp ~3.1.0 -> satisfiable by cakephp/cakephp[3.1.x-dev].
    - cakedc/users 3.1.1 requires cakephp/cakephp 3.1.* -> satisfiable by cakephp/cakephp[3.1.x-dev].
    - cakedc/users 3.1.2 requires cakephp/cakephp 3.1.* -> satisfiable by cakephp/cakephp[3.1.x-dev].
    - cakedc/users 3.1.3 requires cakephp/cakephp 3.1.* -> satisfiable by cakephp/cakephp[3.1.x-dev].
    - cakedc/users 3.1.x-dev requires cakephp/cakephp 3.1.* -> satisfiable by cakephp/cakephp[3.1.x-dev].
    - Conclusion: don't install cakephp/cakephp 3.1.x-dev
    - Installation request for cakedc/users 3.1.* -> satisfiable by cakedc/users[3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.x-dev].

Installation failed, reverting ./composer.json to its original content.

**Comment by zamaliphe** [comment]
same here thy need to update the composer.json requirements

**Comment by steinkel** [comment]
guys, you are right. I've fixed composer in master and we are doing some cleanup in master to release next version. Thanks.

**Comment by davidlyons24** [comment]
Just to let you know the same problem with the cake 3.1. Thanks!

**Comment by zamaliphe** [comment]
for your information you can fix this buy allies cakephp ver 3.2.1 to 3.1.10 

you can do this by editing the 

```
 "require": {
        "php": ">=5.4.16",
        "cakephp/cakephp": "3.2.1 as 3.1.10",
    }
```
this works for me and it makes cakedc/users think you are having ver 3.1.10 while all other plugins know that you have ver 3.2.1

**Comment by davidlyons24** [comment]
Hi Zamaliphe, it didn't work to me.

I try to install in a cake 3.2 and 3.1 installations doing in straight the:
composer require cakedc/users:3.1.*

And it doesn't work, then changing, as you said, the "cakephp/cakephp": "3.2.1", to 3.1.10 or 3.1 but it doesn't work either to me.

**Comment by steinkel** [comment]
hi, we've just commited a fix to the composer (along with some cleanup and phpcs issues) and tagged version 3.1.4, you should be able to install the plugin now using
```
composer require cakedc/users
```

Thanks, please let us know if you have issues with this (I've just tested plugin with a brand new cake 3.2 app)

**Comment by davidlyons24** [comment]
Perfect! for me now it works with 3.2.

Thank you very much!!

**Comment by steinkel** [comment]
I did a clean setup on 3.1 too. Thank you :dancers:
