### ISSUE TITLE
 Override loadModel to load specific users table is bad 

### ISSUE THREAD

**Issue by zamaliphe** [CakeDC/users#291]
/**
     * Override loadModel to load specific users table
     * @param string $modelClass model class
     * @param string $type type
     * @return Table
     */
    public function loadModel($modelClass = null, $type = 'Table')
    {
        return parent::loadModel(Configure::read('Users.table'));
    }

now lets say i used some loadModel to load some tables in the AppCntroller to load data 

now on every method on users controller i will get an error if i didn't comment that override

i think you should find a better way to Handel this

**Comment by ajibarra** [comment]
@zamaliphe Thank you! we will improve that in our next release.

**Comment by steinkel** [comment]
closed in favor of PR #325
