### ISSUE TITLE
UserController could not be found

### ISSUE THREAD

**Issue by blindpenguin** [CakeDC/users#296]
Hi there,

after installation of this plugin on a fresh CakePHP environment, i get this error at validating my email:

`Error: UserController could not be found.`

It advises me to create the UserController. Is this supposed to happen?

My AppController has the component and the bootstrap has the plugin, just like described in the docs.

**Comment by ajibarra** [comment]
Hi @blindpenguin, UserController does not exist. The controller is UsersController. Please check the 's' at the end.

Where are you getting this issue? is a link on a plugin template or it is yours?

**Comment by ajibarra** [comment]
@blindpenguin Closing this one. Please feel free to reopen if you find any other issue
