### ISSUE TITLE
Base table or view not found: 1146 Table '##.social_accounts' doesn't 

### ISSUE THREAD

**Issue by Omarmaste** [CakeDC/users#299]
I have a problem getting the response back to authenticate fb , seems it will not get in the Table social_accounts ,

The documentation described not see that table

**Comment by steinkel** [comment]
Hi @Omarmaste, did you follow the setup instructions to create the required tables? https://github.com/CakeDC/users/blob/master/Docs/Documentation/Installation.md#creating-required-tables

Thanks
