### ISSUE TITLE
Postgresql registration problem 

### ISSUE THREAD

**Issue by Draniu** [CakeDC/users#300]
I'm not sure if it is a bug. 
When I use PostgreSQL I have to change user.id type to UUID to be able to register.

**Comment by steinkel** [comment]
Interesting... we'll investigate a bit further... Thank you.

**Comment by LACabeza** [comment]
this is important because currently is not possible to change this by creating a new migration file with the statement:
`$table->changeColumn('id', 'uuid');`

If you do that, it'll raise the error:
> [PDOException]                                                                                       
>   SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "id" cannot be cast automatically to type uuid  
>   HINT:  You might need to specify "USING id::uuid".

**Comment by Draniu** [comment]
I handle this by changing migrations on create table. It's not the elegant way but it works for me

**Comment by steinkel** [comment]
closed by PR #333

**Comment by steinkel** [comment]
Thank you guys for reporting this one!
