### ISSUE TITLE
Cakedc Users plugin auth username or email problem

### ISSUE THREAD

**Issue by Penergy** [CakeDC/users#301]
Hi all,

I am using Cakedc Users plugin. However, I had a problem.
**Is it possible to configure CakeDC's Users plugin to use email or username field as a username?**

I am looking the post from stackoverflow
http://stackoverflow.com/questions/33462329/cakedc-users-plugin-use-email-field-as-a-username

I found it didn't work anymore.

**Comment by steinkel** [comment]
Answered here http://stackoverflow.com/a/35495640/365877

I think we could improve this in the plugin to make it easier for people using email as login, it's a very common use case, so I'll add a new issue based on your comments. Thank you!

**Comment by Penergy** [comment]
@steinkel Normally, it is probably to use both email or username or mobilephone number together as username.
