### ISSUE TITLE
UsersShell is using fixed table name "Users" instead of custom table name

### ISSUE THREAD

**Issue by sspecht** [CakeDC/users#304]
In `users/src/Shell/UsersShell.php` in lines [298](https://github.com/CakeDC/users/blob/develop/src/Shell/UsersShell.php#L298) and [323](https://github.com/CakeDC/users/blob/develop/src/Shell/UsersShell.php#L323) there is a fixed reference to "users" in a where clause. This is preventing the use of some shell commands with a custom table.

**Comment by steinkel** [comment]
Good catch, we'll take a look ASAP, thanks!

**Comment by steinkel** [comment]
It was fixed in https://github.com/CakeDC/users/pull/305
