### ISSUE TITLE
isAuthorized doesn't work in subfolder

### ISSUE THREAD

**Issue by jarekgol** [CakeDC/users#312]
Hi!
My friend and I run same code on different servers (linux/appache and win/xamp).
My friend have got app in server root directory and I've got in subfolder 
http://p933/laser/blachy/
+src
+vendor
etc...

and in my option` $this->User->isAuthorized(...)` doesn't work, always return false, when asterix * are not used in permissions.php

We've checked that in UserAuthComponent.php is problem with building "params" in
`$requestParams = Router::parse($requestUrl);` about line 138 
it copy part of subfolder path into 'controller' and 'action' instead of right arguments taken from 
`$url = Hash::get((array)$event->data, 'url');`

Please tell me if I must put my project in root directory or is it some kind of bug?
Jarek

**Comment by steinkel** [comment]
thank you @jarekgol we'll take a deeper look at this

**Comment by chav170** [comment]
I had the same issue working with Xampp on Windows.

A workaround you could use is something like this:
In you AppHelper (or any helper you want to use)

```
use Cake\Utility\Hash;
use Cake\Routing\Router;

class AppHelper extends Helper
{
     public $helpers = ['CakeDC/Users.User']

    public function authLink($title, $url = null, array $options = [])
    {
         // Convert url to array to use special url options
         if (!is_array($url)) {
             $url = Router::parse($url);
         }
         $defaultUrlParams = [
             '_base' => false,
         ];
         $url = Hash::merge($defaultUrlParams, $url);
         return $this->User->link($title, $url, $options);
    }
}
```
http://api.cakephp.org/3.0/source-class-Cake.Routing.Router.html#522-524

**Comment by jarekgol** [comment]
We make change in source of UserAuthComponent.php
`//$request->params = $requestParams;		
$request->params = $url;`

now we must add in permissions.php
`"plugin"=>"*"` for every rule but it works on both servers.

**Comment by steinkel** [comment]
@jarekgol did you try using `App.fullBaseUrl` configuration in `app.php`?

Thanks,

**Comment by jarekgol** [comment]
Yes, I was trying fill it with couple of addresses, it wasn't work. Last try was: 
`//'fullBaseUrl' => "http://p933/laser/blachy"`
also with above line not used rest work fine, `$this->link` generates good, working links, also `$this->Url->build` work.

**Comment by steinkel** [comment]
Thanks, please submit a PR if you think we should update the Plugin documentation to cover this case.

**Comment by jarekgol** [comment]
1. and what is "PR"?
2. what about this situation? did you fix it? or if someone want to use this plugin in subdirectory, then he should make walk-arounds?
