### ISSUE TITLE
Does the afterRegister event operate before definitive registration ?

### ISSUE THREAD

**Issue by keisukemizuno** [CakeDC/users#322]
I want to insert the function before registration regardless of whether sns register or not.
So, the best thing is that the afterRegister event operates after clicking the account validation link.

Your answers , please

[my version]
cakephp 3.1.5
cakeDC/users 3.1.5

**Comment by steinkel** [comment]
Hi @keisukemizuno,

What do you need to do?
There is a `UsersAuthComponent::EVENT_BEFORE_REGISTER` you could use too to handle any logic before the registration takes place.

Thanks,

**Comment by keisukemizuno** [comment]
I want to execute some logic before both the social registration and the normal registration.
Is it can be achieved with `UsersAuthComponent::EVENT_BEFORE_REGISTER` ?

**Comment by steinkel** [comment]
Yes, this event is triggered before the User and SocialAccount is saved in `RegisterTrait`,
Thanks,

**Comment by keisukemizuno** [comment]
I understood.
Thank you for answering !
