### ISSUE TITLE
Twitter login: in socialEmail method user session data empty

### ISSUE THREAD

**Issue by lithos77** [CakeDC/users#324]
In twitter login, both with develop and master branch, under cakephp 3.2.5, I've a problem with sessions:
after retreiving twitter data, it triggers the listener failedSocialLogin. 
In the failedSocialLogin method, the $exception is an instance of MissingEmailException and it writes correctly in session the user data passed in $data.
$this->request->session()->write(Configure::read('Users.Key.Session.social'), $data);

But after the redirect to socialEmail() in SocialTrait.php, the following session is always empty, user data are lost, neither written in db tables: 

 if (!$this->request->session()->check(Configure::read('Users.Key.Session.social'))) {
            throw new NotFoundException();
   }

**Comment by steinkel** [comment]
Hi @lithos77 is there anything that could be affecting the way sessions are stored/retrieved in your application?

Is the full session lost or only the `Users.Key.Session.social` key?

**Comment by lithos77** [comment]
Hi,
I saved $user in a custom session name in twitterLogin method (LoginTrait.php) and in socialEmail (SocialTrait.php) it still contains the $user data. But $this->request->session()->read(Configure::read('Users.Key.Session.social')) is empty.

Forcing in socialEmail the Configure::write('Users.Key.Session.social', $customSession), after saving the email address in the form, it gives a The request has been black-holed - and still no records saved in database.

**Comment by steinkel** [comment]
could you debug the values for 
`Configure::read('Users.Key.Session.social')` and the full session when you get the empty result?

**Comment by lithos77** [comment]
Session object is:
object(Cake\Network\Session) {
	[protected] _engine => null
	[protected] _started => true
	[protected] _lifetime => '259200'
	[protected] _isCLI => false
}

debug($this->request->session()->read(Configure::read('Users.Key.Session.social'))) 
is null

**Comment by steinkel** [comment]
Could you please debug values for:
```
debug(Configure::read('Users.Key.Session.social'))
debug($this->request->session()->read())
```

**Comment by lithos77** [comment]
vendor/cakedc/users/src/Controller/Traits/SocialTrait.php (line 36)
'Users.social'
/vendor/cakedc/users/src/Controller/Traits/SocialTrait.php (line 38)
[
	'Config' => [
		'time' => (int) 1458566613
	],
	'_Token' => [
		'allowedControllers' => [],
		'allowedActions' => [],
		'unlockedFields' => []
	],
	'temporary_credentials' => object(League\OAuth1\Client\Credentials\TemporaryCredentials) {
		[protected] identifier => '941mSQAAAAAAuLneAAABU5lYkGQ'
		[protected] secret => 'WMw9kxLSuH85rQVUlbp5syzS49KHoeqy'
	},
	'Users' => [],
	'Flash' => [
		'flash' => [
			(int) 0 => [
				'message' => 'Please enter your email',
				'key' => 'flash',
				'element' => 'Flash/success',
				'params' => []
			],
			(int) 1 => [
				'message' => 'Please enter your email',
				'key' => 'flash',
				'element' => 'Flash/success',
				'params' => []
			]
		]
	],
	'Auth' => [
		'redirect' => '/logout'
	]
]

**Comment by steinkel** [comment]
could you debug the session values after the $user is written, it does not make sense the session data is lost in the way...

**Comment by steinkel** [comment]
and, please edit your latest comment to remove your credentials...

**Comment by lithos77** [comment]
I try to summarize the debug:
1. in twitterLogin in the try-catch, $user = $this->Auth->identify() is false (we do not have email from twitter
2. failedSocialLoginListener has a MissingEmailException with the data of the user retrieved from Tw.
3. in failedSocialLogin() before redirecting to socialEmail,$this->request->session()->read(Configure::read('Users.Key.Session.social) has still user data 
after redirect session data are lost.

4. when you save the user data in database?

**Comment by steinkel** [comment]
Hi @lithos77 I did a couple twitter login tests locally, using CakePHP 3.2.5 and Users develop branch.

```
2016-03-22 23:56:25 Debug: 
CakeDC\Users\Controller\UsersController::failedSocialLogin() - /var/www/cakedc-users/src/Controller/Traits/LoginTrait.php, line 104
CakeDC\Users\Auth\SocialAuthenticate::_touch() - /var/www/cakedc-users/src/Auth/SocialAuthenticate.php, line 320
CakeDC\Users\Auth\SocialAuthenticate::getUser() - /var/www/cakedc-users/src/Auth/SocialAuthenticate.php, line 367
CakeDC\Users\Auth\SocialAuthenticate::authenticate() - /var/www/cakedc-users/src/Auth/SocialAuthenticate.php, line 157
Cake\Controller\Component\AuthComponent::identify() - CORE/src/Controller/Component/AuthComponent.php, line 769
CakeDC\Users\Controller\UsersController::twitterLogin() - /var/www/cakedc-users/src/Controller/Traits/LoginTrait.php, line 58
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37
'Users.social'
2016-03-22 23:56:25 Debug: 
CakeDC\Users\Controller\UsersController::failedSocialLogin() - /var/www/cakedc-users/src/Controller/Traits/LoginTrait.php, line 105
CakeDC\Users\Auth\SocialAuthenticate::_touch() - /var/www/cakedc-users/src/Auth/SocialAuthenticate.php, line 320
CakeDC\Users\Auth\SocialAuthenticate::getUser() - /var/www/cakedc-users/src/Auth/SocialAuthenticate.php, line 367
CakeDC\Users\Auth\SocialAuthenticate::authenticate() - /var/www/cakedc-users/src/Auth/SocialAuthenticate.php, line 157
Cake\Controller\Component\AuthComponent::identify() - CORE/src/Controller/Component/AuthComponent.php, line 769
CakeDC\Users\Controller\UsersController::twitterLogin() - /var/www/cakedc-users/src/Controller/Traits/LoginTrait.php, line 58
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37
[
	'full_name' => 'Jorge González',
        XXXXX
	'provider' => 'Twitter'
]
2016-03-22 23:56:25 Debug: 
CakeDC\Users\Controller\UsersController::socialEmail() - /var/www/cakedc-users/src/Controller/Traits/SocialTrait.php, line 36
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37
[
	'full_name' => 'Jorge González',
        XXXX
	'provider' => 'Twitter'
]
2016-03-22 23:56:34 Debug: 
CakeDC\Users\Controller\UsersController::socialEmail() - /var/www/cakedc-users/src/Controller/Traits/SocialTrait.php, line 36
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37
[
	'full_name' => 'Jorge González',
        XXXXXX
	'provider' => 'Twitter'
]
```

The session information is not lost in failedSocialLogin redirect to socialEmail. Could it be related to issues with your webserver configuration or PHP session configuration?

**Comment by lithos77** [comment]
As I wrote, the session problem could be resolved. The problem is user data is not stored in database and when i confirm the missing email, it black holes the request.

**Comment by steinkel** [comment]
@lithos77 could you debug the output of the save operation done here Model/Behavior/SocialBehavior.php:51 ?
Would be good to know the reason the data is not being saved.
About the black hole, you should be able to debug the reason of blackholes if using latest CakePHP master branch in debug mode :)

**Comment by steinkel** [comment]
please reopen if still an issue
