### ISSUE TITLE
What is callback url in CakeDC users Plugin ?

### ISSUE THREAD

**Issue by kh176** [CakeDC/users#327]
Hi,
I installed the plugin and i actived the social media...
When I create projects in Facebook or Google i give as url of callbacks : 
http://localhost:8080/plug/auth/facebook
http://localhost:8080/plug/auth/google
plug is the name of my Cakephp3 project.
But this give errors in Google and Facebook login..

This is Facebook Error : The URL provided is not allowed by the Application configuration .: One or more provided URL is not allowed by the application settings.
And this is google error:
The redirect URI in the request: http://localhost:8080/auth/google did not match a registered redirect URI.

**Comment by steinkel** [comment]
@kh176 you can't setup a Facebook callback to point to localhost, you'll need to define a virtualhost and configure your webserver, because Facebook is not going to call himself (localhost), something like "myserver.dev"

**Comment by kh176** [comment]
Ok but i alreaddy try localhost url with Google..
Another questions plz how to install twitter feature ?

**Comment by steinkel** [comment]
"localhost" should not be used, you'll need to create your own virtualhost (multiple references, dor example: https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts )

Installing twitter login is easy, follow the tutorial here > https://github.com/CakeDC/users/blob/master/Docs/Documentation/SocialAuthenticate.md

**Comment by kh176** [comment]
Thank you for responding but excuse me i can't find twitter url sign in because tehre isn't a way to install it with composer like facebook for example : composer require league/oauth2-facebook:@stable
And another question plz if i do a virtualhost what wil be the callback  function wich i should  give to Facebook or google ...

**Comment by steinkel** [comment]
For twitter, you need 
```
composer require league/oauth1-client:@stable
```
Once you configure your virtualhost, for example: `myvhost.dev`, the callback url would be
`http://myvhost.dev/auth/twitter`, `http://myvhost.dev/auth/facebook`, etc...

**Comment by kh176** [comment]
Thank you very match I will try it now ..

**Comment by kh176** [comment]
I did a virtualhost now when itry to login with google it say to me : You are not authorized to access that location.
