### ISSUE TITLE
Social account password

### ISSUE THREAD

**Issue by mferak** [CakeDC/users#335]
I encountered this issue: I log in using my social network account. New user gets created, with a random string generated for a password. If I ever decide to leave the social media, I won't be able to log in anymore, as I don't know what my password is. The only workaround I can think of is requesting to reset my password. Could this be done more elegantly?

**Comment by steinkel** [comment]
What's your suggested solution?

You have a way to reset the password once you leave the social network, so I don't see an issue as this use case would have minor impact.
