### ISSUE TITLE
not found error in users/social_email

### ISSUE THREAD

**Issue by keisukemizuno** [CakeDC/users#338]
https://github.com/CakeDC/users/blob/3.1.x/src/Controller/Traits/SocialTrait.php#L31

The above line has throw NotFoundException in the following settings.
If this line is removed, it will work correctly.
My Twitter callback url is "http://localhost/users/social_email".
Please tell me if you know something.

[bootstrap.php]
```
Plugin::load('CakeDC/Users', ['routes' => false, 'bootstrap' => true]);
Configure::write('Users.table', 'MyUsers');
Configure::write('Users.auth', false);
Configure::write('Users.Email.validate', true);
Configure::write('Users.Email.required', true);
Configure::write('Users.Social.login', true);
Configure::write('Users.Key.Session.social', 'Users.social');
Configure::write('Users.Key.Form.social', 'social');
Configure::write('Users.Key.Data.socialEmail', 'info.email');
Configure::write('OAuth.providers.facebook.options.clientId', env('FBID'));
Configure::write('OAuth.providers.facebook.options.clientSecret', env('FBSECRET'));
Configure::write('OAuth.providers.twitter.options.clientId', env('TWKEY'));
Configure::write('OAuth.providers.twitter.options.clientSecret', env('TWSECRET'));
```

[environment]
cakephp 3.1.5
cakedc/users 3.1.6

**Comment by kh176** [comment]
I have the same problem when i want to log in with twitter it redirect me to social_email with NotFoundException..
And when i debug $user i found the email null 
contrary to username and others informations

**Comment by kh176** [comment]
Can you please help me

**Comment by steinkel** [comment]
@kh176 removing this line https://github.com/CakeDC/users/blob/3.1.x/src/Controller/Traits/SocialTrait.php#L31 helps?

**Comment by kh176** [comment]
No it doesn't ...
What about Facebook and Google ? I need your help please

**Comment by steinkel** [comment]
@kh176 Could you do this?
Create a brand new app using CakePHP 3.2 and Users Plugin (develop) and leave all defaults but the OAuth client and secret id's, I'd like to check first if there is any issue in your initial setup or the issue could be related to any customization made.

**Comment by keisukemizuno** [comment]
@steinkel
Did you find out anything?

https://github.com/CakeDC/users/blob/3.1.x/src/Controller/Traits/LoginTrait.php#L45
This query gives no value.
So, L71 is excuted, and a session will not be written by L55.

Please tell me if you know something.

**Comment by steinkel** [comment]
hi @keisukemizuno I'm unable to reproduce it yet, could you debug the output of the temporary credentials and redirect url in lines https://github.com/CakeDC/users/blob/3.1.x/src/Controller/Traits/LoginTrait.php#L71 and https://github.com/CakeDC/users/blob/3.1.x/src/Controller/Traits/LoginTrait.php#L73 please?

**Comment by keisukemizuno** [comment]
@steinkel
Thank you for answering my questions.

```
        if (!empty($oauthToken) && !empty($oauthVerifier)) {
            $temporaryCredentials = $this->request->session()->read('temporary_credentials');
            $tokenCredentials = $server->getTokenCredentials($temporaryCredentials, $oauthToken, $oauthVerifier);
            $user = (array)$server->getUserDetails($tokenCredentials);
            $user['token'] = [
                'accessToken' => $tokenCredentials->getIdentifier(),
                'tokenSecret' => $tokenCredentials->getSecret(),
            ];
            $this->request->session()->write(Configure::read('Users.Key.Session.social'), $user);
            try {
                $user = $this->Auth->identify();
                $this->_afterIdentifyUser($user, true);
            } catch (UserNotActiveException $ex) {
                $exception = $ex;
            } catch (AccountNotActiveException $ex) {
                $exception = $ex;
            } catch (MissingEmailException $ex) {
                $exception = $ex;
            }

            if (!empty($exception)) {
                return $this->failedSocialLogin($exception, $this->request->session()->read(Configure::read('Users.Key.Session.social')), true);
            }
        } else {
            error_log('--1--');
            error_log(print_r($server,true));
            $temporaryCredentials = $server->getTemporaryCredentials();
            error_log('--2--');
            error_log(print_r($temporaryCredentials,true));
            error_log('--3--');
            $this->request->session()->write('temporary_credentials', $temporaryCredentials);
            error_log('--4--');
            $url = $server->getAuthorizationUrl($temporaryCredentials);
            error_log($url);
            error_log('--5--');
            return $this->redirect($url);
        }
```

The above code returns the following log.

```
[Sun Apr 03 05:25:50.479917 2016] [:error] [pid 2158] [client ::1:61417] --1--, referer: http://user.heart.local/users/login
[Sun Apr 03 05:25:50.480020 2016] [:error] [pid 2158] [client ::1:61417] League\\OAuth1\\Client\\Server\\Twitter Object\n(\n    [clientCredentials:protected] => League\\OAuth1\\Client\\Credentials\\ClientCredentials Object\n        (\n            [callbackUri:protected] => \n            [identifier:protected] => fvixam4hXpa8KicyAEa9l6dpI\n            [secret:protected] => FZisMH8Blgpr15DFD9fxyozwyFP9EzFZ0EJkosTCXfHJl9q04M\n        )\n\n    [signature:protected] => League\\OAuth1\\Client\\Signature\\HmacSha1Signature Object\n        (\n            [clientCredentials:protected] => League\\OAuth1\\Client\\Credentials\\ClientCredentials Object\n                (\n                    [callbackUri:protected] => \n                    [identifier:protected] => fvixam4hXpa8KicyAEa9l6dpI\n                    [secret:protected] => FZisMH8Blgpr15DFD9fxyozwyFP9EzFZ0EJkosTCXfHJl9q04M\n                )\n\n            [credentials:protected] => \n        )\n\n    [responseType:protected] => json\n    [cachedUserDetailsResponse:protected] => \n    [userAgent:protected] => \n)\n, referer: http://user.heart.local/users/login
[Sun Apr 03 05:25:51.229611 2016] [:error] [pid 2158] [client ::1:61417] --2--, referer: http://user.heart.local/users/login
[Sun Apr 03 05:25:51.229755 2016] [:error] [pid 2158] [client ::1:61417] League\\OAuth1\\Client\\Credentials\\TemporaryCredentials Object\n(\n    [identifier:protected] => 1iG_XgAAAAAAuFhvAAABU9inO_4\n    [secret:protected] => ZZqbqy2lWFBRJ3AznyLRPCNOoL7KHxnb\n)\n, referer: http://user.heart.local/users/login
[Sun Apr 03 05:25:51.229767 2016] [:error] [pid 2158] [client ::1:61417] --3--, referer: http://user.heart.local/users/login
[Sun Apr 03 05:25:51.229806 2016] [:error] [pid 2158] [client ::1:61417] --4--, referer: http://user.heart.local/users/login
[Sun Apr 03 05:25:51.229829 2016] [:error] [pid 2158] [client ::1:61417] https://api.twitter.com/oauth/authenticate?oauth_token=1iG_XgAAAAAAuFhvAAABU9inO_4, referer: http://user.heart.local/users/login
[Sun Apr 03 05:25:51.229837 2016] [:error] [pid 2158] [client ::1:61417] --5--, referer: http://user.heart.local/users/login
```

Would you like something clue ?

**Comment by steinkel** [comment]
So then, after twitter authentication using temporary credentials, the query variable oauthToken is missing? Could log the url sent by twitter after auth?

**Comment by keisukemizuno** [comment]
What is the url sent by twitter after auth?

After auth, redirect to the following url.
"http://user.heart.local/users/social_email?oauth_token=Z8-TDwAAAAAAuFhvAAABU9thFwE&oauth_verifier=rZElDq3z2CMNh9duhBmitUBI7od5sMJQ"

And, 
```
    public function socialEmail()
    {
error_log(print_r($this->request,true));
        if (!$this->request->session()->check(Configure::read('Users.Key.Session.social'))) {
            throw new NotFoundException();
        }
        $this->request->session()->delete('Flash.auth');

        if ($this->request->is('post')) {
            $validPost = $this->_validateRegisterPost();
            if (!$validPost) {
                $this->Flash->error(__d('Users', 'The reCaptcha could not be validated'));
                return;
            }
            $user = $this->Auth->identify();
            return $this->_afterIdentifyUser($user, true);
        }
    }
```

the above code returns the following log.

`[Sun Apr 03 18:08:50.924637 2016] [:error] [pid 268] [client ::1:64516] Cake\\Network\\Request Object\n(\n    [params] => Array\n        (\n            [plugin] => CakeDC/Users\n            [controller] => Users\n            [action] => socialEmail\n            [_ext] => \n            [pass] => Array\n                (\n                )\n\n            [isAjax] => \n            [_Token] => Array\n                (\n                    [unlockedFields] => Array\n                        (\n                        )\n\n                )\n\n            [_csrfToken] => f489400bff1f585d012bb6e564a6bfbda8ffc3c5\n        )\n\n    [data] => Array\n        (\n        )\n\n    [query] => Array\n        (\n            [oauth_token] => Z8-TDwAAAAAAuFhvAAABU9thFwE\n            [oauth_verifier] => rZElDq3z2CMNh9duhBmitUBI7od5sMJQ\n        )\n\n    [cookies] => Array\n        (\n            [csrfToken] => f489400bff1f585d012bb6e564a6bfbda8ffc3c5\n            [Q2FrZQ==_NzIxZmIzM2NhNGU0Mzc2Yjc3YWY0YmI3YTY2Mjg2N2Y1NjUxNmVkNDlhMTIxMzA0MzkxN2IzZTNhYjhkZDcwMZbr************************************************************************=] => \n            [crtg_rta] => \n            [_ga] => GA1.2.1******************\n            [_td] => 6eebe***************************\n            [CAKEPHP] => pkp1******************\n        )\n\n    [_environment:protected] => Array\n        (\n            [REDIRECT_REDIRECT_STATUS] => 200\n            [REDIRECT_STATUS] => 200\n            [HTTP_HOST] => user.heart.local\n            [HTTP_CONNECTION] => keep-alive\n            [HTTP_CACHE_CONTROL] => max-age=0\n            [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\n            [HTTP_UPGRADE_INSECURE_REQUESTS] => 1\n            [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36\n            [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch\n            [HTTP_ACCEPT_LANGUAGE] => ja,en;q=0.8,en-US;q=0.6\n            [HTTP_COOKIE] => csrfToken=f489400bff1f585d012bb6e564a6bfbda8ffc3c5; Q2FrZQ%3D%3D.NzIxZmIzM2******************; crtg_rta=; _ga=GA1.2.1956******************; _td=6eebe8fe-2***************************; CAKEPHP=pkp1******************\n            [PATH] => /usr/bin:/bin:/usr/sbin:/sbin\n            [SERVER_SIGNATURE] => \n            [SERVER_SOFTWARE] => Apache/2.4.16 (Unix) PHP/5.5.30 OpenSSL/0.9.8zg\n            [SERVER_NAME] => user.heart.local\n            [SERVER_ADDR] => ::1\n            [SERVER_PORT] => 80\n            [REMOTE_ADDR] => ::1\n            [DOCUMENT_ROOT] => /Library/WebServer/Documents/userheart\n            [REQUEST_SCHEME] => http\n            [CONTEXT_PREFIX] => \n            [CONTEXT_DOCUMENT_ROOT] => /Library/WebServer/Documents/userheart\n            [SERVER_ADMIN] => you@example.com\n            [SCRIPT_FILENAME] => /Library/WebServer/Documents/userheart/webroot/index.php\n            [REMOTE_PORT] => 64516\n            [REDIRECT_QUERY_STRING] => oauth_token=Z8-TDwAAAAAAuFhvAAABU9thFwE&oauth_verifier=rZElDq3z2CMNh9duhBmitUBI7od5sMJQ\n            [REDIRECT_URL] => /webroot/users/social_email\n            [GATEWAY_INTERFACE] => CGI/1.1\n            [SERVER_PROTOCOL] => HTTP/1.1\n            [REQUEST_METHOD] => GET\n            [QUERY_STRING] => oauth_token=Z8-TDwAAAAAAuFhvAAABU9thFwE&oauth_verifier=rZElDq3z2CMNh9duhBmitUBI7od5sMJQ\n            [REQUEST_URI] => /users/social_email?oauth_token=Z8-TDwAAAAAAuFhvAAABU9thFwE&oauth_verifier=rZElDq3z2CMNh9duhBmitUBI7od5sMJQ\n            [SCRIPT_NAME] => /webroot/index.php\n            [PHP_SELF] => /webroot/index.php\n            [REQUEST_TIME_FLOAT] => 1459674530.848\n            [REQUEST_TIME] => 1459674530\n            [APP_ENV] => local\n            [DEBUG_FLAG] => 1\n          [HTTP_X_HTTP_METHOD_OVERRIDE] => \n            [ORIGINAL_REQUEST_METHOD] => GET\n            [HTTPS] => \n            [HTTP_X_REQUESTED_WITH] => \n        )\n\n    [url] => users/social_email\n    [base] => \n    [webroot] => /\n    [here] => /users/social_email\n    [trustProxy] => \n    [_detectorCache:protected] => Array\n        (\n            [post] => \n            [put] => \n            [ajax] => \n            [patch] => \n            [delete] => \n            [requested] => \n            [get] => 1\n            [head] => \n            [options] => \n        )\n\n    [_input:protected] => \n    [_session:protected] => Cake\\Network\\Session Object\n        (\n            [_engine:protected] => \n            [_started:protected] => 1\n            [_lifetime:protected] => 1440\n            [_isCLI:protected] => \n        )\n\n)\n
`

Sorry, do you have become the answer of the question?

**Comment by steinkel** [comment]
Sorry, still no clue, is there a way you could zip me the related files to reproduce the issue locally?

**Comment by keisukemizuno** [comment]
[testheart.zip](https://github.com/CakeDC/users/files/201783/testheart.zip)

OK. I attached the sample file.
the tmp folder, the log folder and the tests folder were removed.
Please confirm the above.

**Comment by steinkel** [comment]
Hi @keisukemizuno I've tested your app locally and found 2 issues:
* Plugin::load('CakeDC/Users', ['routes' => false, 'bootstrap' => true]);
  * You should load the plugin routes to allow the email validation work, per documentation, the plugin should be loaded this way: `Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);`
* Configure::write('Users.table', 'MyUsers');
  * There is no `MyUsers` Table in your code, I don't know why this configuration was added, please remove it to use the default UsersTable from the Plugin, or use your own Table if you want following the docs.

I've successfully logged in via twitter using your app + updating the config.

Thanks,

**Comment by keisukemizuno** [comment]
Thanks for answering my question.

But it was not resolved by the pointed out issues.
And, my users table is customized.
So, `Configure::write('Users.table', 'MyUsers');` this line is needed.
https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md

**Comment by steinkel** [comment]
Hi, if you customized your Users Table (using MyUsers) you'll need to ensure the table `extends UsersTable` and provide also the Entity. I didn't see MyUsers table in the provided zip file so I couldn't test it. Thanks,

**Comment by keisukemizuno** [comment]
Yes, I understand about extending the model.
In my actual project folder, I ensure the table extends UsersTable and provide also the Entity.

Sorry, I took a mistake.
Now, I'm testing the simplest case.
Under the following condition, I can't log in via twitter.

1 change to `Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);`
2 `Configure::write('Users.table', 'MyUsers');` is removed

Have you been successfully logged in via twitter using this attachment file?
[testheart.zip](https://github.com/CakeDC/users/files/206159/testheart.zip)
![2016-04-06 19 01 28](https://cloud.githubusercontent.com/assets/1429563/14312992/fe7c7bb0-fc29-11e5-8b4d-d3f44297b0ea.png)

**Comment by steinkel** [comment]
Hey, the callback url should be

`http://testheart.local/auth/twitter`

**Comment by keisukemizuno** [comment]
I'm very sorry ...
This problem has been resolved !
Thank you very much.

Incidentally , in the case of `Configure::write('Users.table', 'MyUsers');`,
In perhaps because of validation,
after I input the email value, it caused the error of `Unable to login user with reference {0}`.
But this is a different problem, so I'll try again.

if I don't understand something, I wonder if you give me advice again.

Thanks.

**Comment by steinkel** [comment]
@keisukemizuno I'm happy you got it fixed. We'll try to help if any other issues, please open a new ticket if you get into troubles. Thanks,

NOTE: Feel free to submit a pull request to the docs if you find something needs clarification.

**Comment by keisukemizuno** [comment]
@steinkel
Thank you very much !
