### ISSUE TITLE
Facebook redirect problem

### ISSUE THREAD

**Issue by gerrymcdonnell** [CakeDC/users#340]
Everytime i login with facebook in my app it redirects to the wrong link;

http://localhost/auth/facebook?code=blahblah

for me it shud be
http://localhost/cakeusers/auth/facebook?code=blahblah

i spotted this line  in users/config/users.php which seems to be the issue;

    'OAuth' => [
        'path' => ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialLogin', 'prefix' => false],
        'providers' => [
            'facebook' => [
                'className' => 'League\OAuth2\Client\Provider\Facebook',
                'options' => [
                    'graphApiVersion' => 'v2.5',
                    '**redirectUri' => Router::url('/auth/facebook', true)**
                ]
            ],

**Comment by vietkungfu** [comment]
reference #329

**Comment by steinkel** [comment]
Looks like a problem related to NOT configuring a virtualhost for your application?

**Comment by steinkel** [comment]
@gerrymcdonnell please try to setup the redirectUri correctly, something like

```
'redirectUri' =>  Router::url('/cakeusers/auth/facebook', true),
```

**Comment by gerrymcdonnell** [comment]
hmm, ive tried that and i get;
"You are not authorized to access that location." (the cakephp notication)
it doesnt log me in. What have i done wrong.?

![cakephp fb login](https://cloud.githubusercontent.com/assets/1525657/14094163/bcb7f7e8-f54b-11e5-8bad-b2bfabc55d3e.png)

![fb app settings](https://cloud.githubusercontent.com/assets/1525657/14094177/ca1288b8-f54b-11e5-8f3d-ffff25a6033b.png)

**Comment by thinkingmedia** [comment]
I'm thinking that `localhost` is not a valid domain, and I'm surprised Facebook allowed you to assign it to the app. They use to have validation rules that would prevent it (I guess things have changed).

See this question on stackoverflow.

http://stackoverflow.com/questions/4532721/facebook-development-in-localhost

**Comment by Draniu** [comment]
add  to hosts
```
127.0.0.1 whatever.com
```
and use `whatever.com` domain

**Comment by mcassisa** [comment]
Me too, I am experiencing a similar problem as gerrymcdonnell but using a FQDN.
The redirectUri has my app subdirectory parameter `Router::url('/mysubdir/auth/facebook', true)` and the link in the login page is properly generated (it points to `www.mydomain.com:myport/mysubdir/auth/facebook`), but after clicking, i get a 404: the page is
```
https://www.facebook.com/v2.5/dialog/oauth?client_id=962334833848002&redirect_uri=http%3A%2F%2Fiwonttellyou.us-west-2.compute.amazonaws.com%3A31288%2Fauth%2Ffacebook&state=P3wgseHELfP7fbkqZYll1wAy7TDbAQJQ&scope=public_profile%2Cemail&response_type=code&approval_prompt=auto
```
please notice the (incomplete) redirect_uri parameter

**Comment by gerrymcdonnell** [comment]
It doesnt seem to work locally but i managed to test it online and it worked but still not quite able to get it to work locally.

**Comment by gerrymcdonnell** [comment]
It doesnt seem to work locally but i managed to test it online and it
worked but still not quite able to get it to work locally.

On 5 April 2016 at 21:10, mcassisa <notifications@github.com> wrote:

> Me too, I am experiencing a similar problem as gerrymcdonnell but using a
> FQDN.
> The redirectUri has my app subdirectory parameter Router::url('/mysubdir/auth/facebook',
> true) and the link in the login page is properly generated (it points to
> www.mydomain.com:myport/mysubdir/auth/facebook), but after clicking, i
> get a 404: the page is
>
> https://www.facebook.com/v2.5/dialog/oauth?client_id=962334833848002&redirect_uri=http%3A%2F%2Fiwonttellyou.us-west-2.compute.amazonaws.com%3A31288%2Fauth%2Ffacebook&state=P3wgseHELfP7fbkqZYll1wAy7TDbAQJQ&scope=public_profile%2Cemail&response_type=code&approval_prompt=auto
>
> please notice the (incomplete) redirect_uri parameter
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CakeDC/users/issues/340#issuecomment-205971560>
>



-- 
Cheers,
Gerry mc Donnell

The blog:
http://www.irishbloke.net

**Comment by steinkel** [comment]
@mcassisa what's the auth url configured in your facebook app?

**Comment by steinkel** [comment]
please reopen if it's still an issue
