### ISSUE TITLE
redirectUri has to be specified in config/users.php

### ISSUE THREAD

**Issue by mcassisa** [CakeDC/users#344]
In config/users.php I had to specify redirectUri parameter to have the login process going on.

```
'OAuth' => [
        'path' => ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialLogin', 'prefix' => false],
        'providers' => [
            'facebook' => [
                'className' => 'League\OAuth2\Client\Provider\Facebook',
                'options' => [
                    'graphApiVersion' => 'v2.5',
                   'redirectUri' => 'http://'

```

**Comment by steinkel** [comment]
@mcassisa yes, if you override the OAuth key in configuration, you'll need to specify all the params again, the suggested way to configure the plugin is described here > https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md

Thanks,
