### ISSUE TITLE
facebookLogin() not defined

### ISSUE THREAD

**Issue by PhantomWatson** [CakeDC/users#347]
[The docs](https://github.com/CakeDC/users/blob/master/Docs/Documentation/UserHelper.md) suggest creating Facebook and Twitter buttons like this:

    $this->User->facebookLogin();

    $this->User->twitterLogin();

But `facebookLogin()` isn't defined anywhere in the project and `twitterLogin()` isn't defined as a helper method. Am I missing something?

**Comment by steinkel** [comment]
Docs were updated, thanks!
https://github.com/CakeDC/users/blob/master/Docs/Documentation/UserHelper.md
