### ISSUE TITLE
Anonymous acces to all pages

### ISSUE THREAD

**Issue by amoncadap** [CakeDC/users#350]
i can allow anonymous access to some controllers?

**Comment by thinkingmedia** [comment]
It works the same as the `AuthComponent` for granting access.

You can allow all or pass an array of action names in your controller.

```
     public function beforeFilter() {
           parent::beforeFilter();
           $this->allow('*');
     }
```

For authorized users you need to also use the RBAC settings.

https://github.com/CakeDC/users/blob/master/Docs/Documentation/SimpleRbacAuthorize.md

**Comment by steinkel** [comment]
Exactly, also watch #332 as we will control public access in rules when this PR gets merged. Thanks!
