### ISSUE TITLE
register() function extend

### ISSUE THREAD

**Issue by Einzelnman** [CakeDC/users#353]
Hey Guy,

I'm using CakeDC Users 3.1.0. I see the previously version is know the users detail options.

I know, the extension is possible if I use same table to new field(s). But I need to save my data to an associated table. For example, the Users table store the default values, and another table (users_details) store many other informations (birth city etc) hasOne relationship. save($user, ['associated' => ['UsersDetails']]); (I know register() right here)
Is it possible default or I need to rewrite the Controller/Treit.
Thanks for your help.

**Comment by steinkel** [comment]
I would suggest to extend the UsersTable in this case, and add the columns and associations needed in your application. We decided long time ago to drop support for user_details as it's very specific to each application. Thanks,

**Comment by Einzelnman** [comment]
We find a solution. Create a custom Controller and catch the EVENT_AFTER_REGISTER component and here create a new entity and save it.
