### ISSUE TITLE
language with CakeDC/Users

### ISSUE THREAD

**Issue by Penergy** [CakeDC/users#358]
I have used the normal CakeDC/Users plugin, normally the profile linke is www.example.com/users/users/profile. 

When I implmented two language: I need the link like this:
www.example.com/en/users/users/profile

how can I change the routing? And finally I need www.example.com/en/profile.

**Comment by pyrokar** [comment]
Do you use the i18n Plugin from CakeDC (https://github.com/CakeDC/i18n)? This should do what you're asking for?!

**Comment by steinkel** [comment]
Closed as not related to Users Plugin
