### ISSUE TITLE
Redirection upon successful login

### ISSUE THREAD

**Issue by kwalski** [CakeDC/users#362]
I am lost with how to redirect the user to a specific controller action. Let's say I want to redirect user to /users/index

With the default config, I am redirected to `/`

I have tried this in my app/src/Controller/AppController.php but I still get redirected to / 
```
 $this->loadComponent('CakeDC/Users.UsersAuth', [
                             'loginRedirect' => [
                             'controller' => 'Users',
                             'action' => 'index'
                             ],
                            'logoutRedirect' => [
                             'controller' => 'Pages',
                             'action' => 'display',
                             'home'
                             ]
                             ]);```
Is there a different way?

**Comment by waspinator** [comment]
I had the same issue, and this is what @phillaf helped me figure out.

In `bootstrap.php` add

```
use App\Listener\UserListener;
use Cake\Event\EventManager;
EventManager::instance()->on(new UserListener());
```

and in `src/Listener/UserListener.php` add

    <?php
    namespace App\Listener;
    
    use Cake\Event\EventListenerInterface;
    
    class UserListener implements EventListenerInterface
    {
        public function implementedEvents()
        {
            return [
                'Users.Component.UsersAuth.afterLogin' => 'loginRedirect',
                'Users.Component.UsersAuth.afterLogout' => 'logoutRedirect',
            ];
        }
    
        public function loginRedirect($event)
        {
            return ['plugin' => false, 'controller' => 'Articles', 'action' => 'index'];
        }
    
        public function logoutRedirect($event)
        {
            return ['plugin' => false, 'controller' => 'Pages', 'action' => 'welcome'];
        }
    }

**Comment by steinkel** [comment]
@waspinator suggestion works, but you could do it much easier using the Auth specific loginRedirect config in AppController:

```
$this->loadComponent('CakeDC/Users.UsersAuth');
$this->Auth->config('loginRedirect', 'XXX');
```
