### ISSUE TITLE
Trying to access another page that isn't user/users and not working

### ISSUE THREAD

**Issue by tephysalazar** [CakeDC/users#369]
I tried to change permissions.php but still not working 
only work on localhost/project/users/users

-----------

Los usuarios del tipo user solo pueden ver la pestaña de usuarios, no pueden ver las tablas de la base de datos que establecí, aunque intente modificar los permisos, sigue sin funcionar.

**Comment by tephysalazar** [comment]
only work on localhost/project/users/users

**Comment by ajibarra** [comment]
Hi @tephysalazar, what is the exact issue you are facing with? 

If you need to show/hide menu options you can use UserHelper::isAuthorized to show/hide accordingly.

**Comment by tephysalazar** [comment]
Hi, 

I can't open any page that is not ...users/users with any user that isn't superadmin
I tried to change permissions but still no working, users are not authorized to that page 

[
            'role' => 'user',
            'plugin' => 'CakeDC/Users',
            'controller' => 'Cliente',
            'action' => '*',
            'allowed' => true,
        ],

**Comment by tephysalazar** [comment]
Solved..  Using this 

[
'role' => 'user',
'controller' => 'Cliente',
'action' => '*',
'allowed' => true,
],
