### ISSUE TITLE
findAllByUsernameOrEmail doesn't work in cakephp 3.x

### ISSUE THREAD

**Issue by mickeyze** [CakeDC/users#371]
In PasswordBehavior 

function "findAllByUsernameOrEmail" doesn't work in cakephp 3.x.
According to dochttp://book.cakephp.org/3.0/en/appendices/orm-migration.html:
"In 3.x the findAllBy* methods have been removed, instead findBy* always returns a query object. "

**Comment by steinkel** [comment]
closed per #373

Thanks!
