### ISSUE TITLE
requestResetPassword update breaks normal logic flow

### ISSUE THREAD

**Issue by 02GEEK** [CakeDC/users#374]
updated from 3.1.6 to 3.2.0
PasswordManagmentTrait.php (101-106): 
these lines :
            $resetUser = $this->getUsersTable()->resetToken($reference, [
                'expiration' => Configure::read('Users.Token.expiration'),
                'checkActive' => false,
                'sendEmail' => true,
                'ensureActive' => true
            ]);
ensureActive should be coming from the config file as - most would want when ever a user wants to reset there password but they didn't activate there account to have the account activate and reset at the same time. i can see a case where someone uses active as a way to block users but i think that should be separated. 

this update breaks functionality for all live sites so i think it should of have defaulted to false and controllable in the config.

**Comment by steinkel** [comment]
I agree adding a config param for it
