### ISSUE TITLE
allo for public area

### ISSUE THREAD

**Issue by zamaliphe** [CakeDC/users#375]
you need to provide a method to allow for public part of controller 

and provide a separate configuration for that

**Comment by waspinator** [comment]
in AppController try adding

```  
    public function beforeFilter(Event $event)
    {
        $this->Auth->allow('display');
        return parent::beforeFilter($event);
    }
```

**Comment by steinkel** [comment]
Hi @zamaliphe this is currently work in progress here > #339 meanwhile you can manage public access via Auth->allow as @waspinator suggested, thank you!

**Comment by zamaliphe** [comment]
mar 24 and still not pulled ? :(

**Comment by steinkel** [comment]
the PR has some tests broken
