### ISSUE TITLE
Users Could not load configuration file

### ISSUE THREAD

**Issue by incredibleX** [CakeDC/users#377]
I'm using [**CakeDC's Users**][1] Plugin for authentication. 
I've followed all the steps of installation as documented **[here][2]**, but i'm getting this error:

[![enter image description here][3]][3]

I've performed the following steps:

 1. `composer require cakedc/users`
 2. `composer require league/oauth2-facebook:@stable`
 3. `composer require league/oauth2-google:@stable`
 4. `bin/cake migrations migrate -p CakeDC/Users`
 5. In config/bootstrap.php 
        

        Configure::write('Users.config', ['users']);
        Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true ]);
        Configure::write('Users.Social.login', true); //to enable social login

 6. Load the Component in your src/Controller/AppController.php, and use
    the passed Component configuration to customize the Users Plugin:
    
        $this->loadComponent('CakeDC/Users.UsersAuth');

  [1]: https://github.com/CakeDC/users/
  [2]: https://github.com/CakeDC/users/blob/master/Docs/Documentation/Installation.md
  [3]: http://i.stack.imgur.com/yqWfK.png

**Update:** I've removed 

    Configure::write('Users.config', ['users']);

this line from my bootstrap as i'm using the default users.php file which is present inside the plugin now. 
But i get this error now:

    Invalid provider or missing class (League\OAuth2\Client\Provider\LinkedIn)
 I can get rid of this error by disabling social login (which is not what i want to do):

    Configure::write('Users.Social.login', false);

After disabling the social login i get this error:

    Error: A route matching "array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login', 'prefix' => false, '_ext' => NULL, )" could not be found.

**Comment by yeliparra** [comment]
@incredibleX Try  taking off from your users.php file 'OAuth.providers', those providers that you are not going to use, like for example 'linkedIn'

**Comment by incredibleX** [comment]
I've set social login false. 
Also what does this error tells?
Error: A route matching "array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login', 'prefix' => false, '_ext' => NULL, )" could not be found.
