### ISSUE TITLE
Allow finder configuration in ApiKeyAuthenticate

### ISSUE THREAD

**Issue by steinkel** [CakeDC/users#383]
We are using "all" now, but makes sense to specify a finder configuration shared with the main form login finder to ensure we restrict access to disabled users. See https://github.com/CakeDC/users/blob/master/src/Auth/ApiKeyAuthenticate.php#L73

**Comment by pedrofs** [comment]
Should we use this one
https://github.com/CakeDC/users/blob/develop/config/users.php#L106
or create a new index in the config file?

**Comment by steinkel** [comment]
I think we should use that one as a default value, and let the users specify another one in case they have different criteria for api users vs regular users

**Comment by steinkel** [comment]
closed per #463
