### ISSUE TITLE
Login pages...

### ISSUE THREAD

**Issue by Quentinvarquet** [CakeDC/users#384]
Hello,

I just installed your plugin on the last version of cakephp.

Everything is working but I have a question.

When I go on localhost/my_webite your plugin always redirect me to the /login pages.

Do you know what is the solution to disable this ? 

Thank you

**Comment by Lasim** [comment]
how about this?

https://github.com/CakeDC/users/issues/350

**Comment by ajibarra** [comment]
@Quentinvarquet as @Lasim point in #350..you just need to allow actions in your controller. The plugin is based on AuthComponent from the core.
