### ISSUE TITLE
problem with passing argument to the UsersAuthComponent 

### ISSUE THREAD

**Issue by saviobosco** [CakeDC/users#390]
arguments passed to the usersAuthcomponent on initialization is supposed to overwrite the component default parameters like 
$this->loadComponent('CakeDC/Users.UsersAuth',[
            'unauthorizedRedirect'=>[
                'controller' => 'Admins',
                'action' => 'login'
            ]
        ]);
but instead redirects you to plugin defined unauthorized redirect parameter .

**Comment by steinkel** [comment]
Hi @saviobosco I think it makes sense to check and override passed component params with exisiting defaults, current plugin configuration is described here > https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md
