### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Bestrafung** [CakeDC/users#397]
I'm new to Cake and Croogo and trying to learn everything. I've uploaded the files to the Plugin directory and migrated the Users table as described in the installation documentation. When I try to go to the admin profile (/admin/users/users/edit/1/1) or logout I get the below error. Can you please let me know what I'm doing wrong?

Error: AclFilter could not be found.
Error: Create the class AclFilter below in file: app/Controller/Component/AclFilter.php

<?php
class AclFilter extends Component {
}

**Comment by Bestrafung** [comment]
I forgot to add the stack trace at the bottom.

Stack Trace

    APP/Plugin/Users/Controller/UsersController.php line 154 → CroogoAppController->beforeFilter()
    [internal function] → UsersController->beforeFilter(CakeEvent)
    APP/Vendor/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php line 243 → call_user_func(array, CakeEvent)
    APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php line 677 → CakeEventManager->dispatch(CakeEvent)
    APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php line 189 → Controller->startupProcess()
    APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(UsersController, CakeRequest)
    APP/webroot/index.php line 105 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by steinkel** [comment]
Hi @Bestrafung this plugin is a standard CakePHP Plugin, not intended for using with Croogo's own plugin structure. We would need to play with both to see if there is a way for them to work together...
