### ISSUE TITLE
Permission to a specific view 

### ISSUE THREAD

**Issue by amohideen** [CakeDC/users#402]
I have implemented the user plugin on top of the blog app (from the CakePHP tutorial) and it works fine for superadmin (the first user).

However, when I want to allow open access to a specific view, it is not working. May be I got it wrong. Below is the permissions,php inside the config directory inside the a pp.

 return [
        'Users.SimpleRbac.permissions' => [
            [
                'role' => '*',
                'controller' => 'Articles',
                'action' => ['index'],
            ],
        ]
    ];
any help please.

**Comment by Xymanek** [comment]
If I understand correctly you want to allow guests (non-users) to view the page, right? In this case you need to add `$this->Auth->allow('index')` to `ArticlesController`'s `initialize()`. What you wrote above grants **any user** access to page but doesn't affect non-signed in clients.

**Comment by amohideen** [comment]
Yes.. Guests. Thanks.
