### ISSUE TITLE
Support for U2F / Yubikey / Google Authenticator (HOTP/TOTP)

### ISSUE THREAD

**Issue by jtraulle** [CakeDC/users#404]
Hi, this is not really an issue and more a feature request.
I apologize if this is not the right place for that.

It think it would be interesting to have Yubikey support 
https://github.com/enygma/yubikey (pretty decent implementation of Yubico validation in PHP)

as well as U2F (Universal 2nd Factor)
https://github.com/Yubico/u2fval-client-php

or Google Authenticator
https://github.com/antonioribeiro/google2fa

What do you think ?

**Comment by steinkel** [comment]
Hey, yes this is the right place :)

I'll add it as a feature request. Thanks.

**Comment by steinkel** [comment]
Closed per #439
