### ISSUE TITLE
AuthLinkHelper::link method returns false for url `mailto:test@test.com`

### ISSUE THREAD

**Issue by pedrofs** [CakeDC/users#406]
When there is no user in the session it assumes this url isn't authorized, returning false.

**Comment by Xymanek** [comment]
This probably has to do with #339

**Comment by steinkel** [comment]
Additionally would be a good idea to add 'auth' param to the link options and disable auth checks for a specific link

**Comment by steinkel** [comment]
Fixed in #427 we just need to set 'allowed' => true when creating the link
