### ISSUE TITLE
[Suggestion] Allow any user property used in SimpleRbac

### ISSUE THREAD

**Issue by Xymanek** [CakeDC/users#407]
Right now only `role` property can be used in SimpleRbac. I suggest to `Hash::get` any property (except reserved) from the user array. This will allow things like keeping roles in separate table and using `role.title` in SimpleRbac as well as many other options.

The reserved keywords that would remain to insure BC:

- `prefix`
- `plugin`
- `controller`
- `action`
- `allowed`
- `_ext`

I can try to PR if people think this is a good idea

**Comment by steinkel** [comment]
closed per #411
