### ISSUE TITLE
Route issue : false login redirect

### ISSUE THREAD

**Issue by ahmadod** [CakeDC/users#413]
Hello
I've installed this plugin in a project with no fronted and all admin sections are with no prefix, i have an issue : while generating url's with no controller the url will redirected to login controller , however when i add controller to the url it works fine but i can't do it with pagination.
i have the same issue with superuser as well.
can you help me please?

Thanks

**Comment by steinkel** [comment]
Please could you paste here your permissions.php, users.php files and the url you are trying to validate?

What means "generating url's with no controller" are these url's external to your application?

Thanks,

**Comment by ahmadod** [comment]
I mean when i want to create a link from index of a table to it's action normally it doesn't need to define controller in url array for example $this->Url->build(['action'=>'view',5) should generate a link to view form the same controller but it will generate to 'login' controller, but this $this->Url->build(['controller'=>'example','action'=>'view',5) works fine.

**Comment by ahmadod** [comment]
From This : http://localhost/gardeshgari/acms/ when creating link to view http://localhost/gardeshgari/acms/view/10 will be http://localhost/gardeshgari/login/view/9

Thanks

**Comment by steinkel** [comment]
Are you using any custom UrlHelper?

**Comment by ahmadod** [comment]
Yes , bootstrapUi

**Comment by steinkel** [comment]
Using Router::url() works fine?

**Comment by ahmadod** [comment]
No , it didn't

**Comment by steinkel** [comment]
If you are not using a users.php file for configuration, then please paste here all the CakeDC/Users related configuration to check if rules are being loaded correctly. Thanks,

**Comment by ahmadod** [comment]
Which files should i paste ? i haven't touched the vendor files
Thanks

**Comment by steinkel** [comment]
The relevant Configure::write('Users.XXX'); lines in your config file (bootstrap.php) and the Plugin::load('CakeDC/Users', ...);

**Comment by ahmadod** [comment]
// bootstrap.php
`Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);`

Just this line , there is no configuration in whole project matching Configure::write('Users.XXX');

Thank you

**Comment by steinkel** [comment]
@ahmadod is this still an issue after upgrading to latest release?

**Comment by ahmadod** [comment]
Hi , Just have update to 3.1.6, still the same issue.

**Comment by steinkel** [comment]
I was unable to reproduce the issue. Please could you provide some unit test/configuration/zip with blank project/c9 environment I could use to reproduce it?

**Comment by steinkel** [comment]
Unable to reproduce
