### ISSUE TITLE
Possibility for Users to change their own Profile

### ISSUE THREAD

**Issue by DrizztDarnok** [CakeDC/users#415]
Is it correct that normal Users can’t change their own profile?
If I have overseen anything it would be great if you could correct me.

**Comment by steinkel** [comment]
Hi @DrizztDarnok the profile page is not an edit page, the idea behind the profile is to display who you are and provide links to change password/edit your profile/anything you want to do with profiles in your app. What are you looking for?

Thanks,

**Comment by DrizztDarnok** [comment]
Hi @steinkel, i wanted to expand the profilpage with more attributes like hobbys, interessts and so on, which i have done with expanding the table (using my own via the guidelines provided) and everything works so far.
But i would like to use linked tables for security isses and for that i need to edit the profil-function (not just the template). Which dosent seem to be possible because the structure of the traits...

A generell question:
Would it be the right aproch to define an own for example edit2 function in my controller(expanding Userscontroller)  if i want to define my own way for editing the profil data?

**Comment by steinkel** [comment]
Yes, makes sense to add a new action "editProfile" in your users controller, to handle the form and store the users profile with the right associations, validation, etc. The provided "profile" feature is just a very basic placeholder.

Thanks,
