### ISSUE TITLE
Error: A route matching could not be found. 

### ISSUE THREAD

**Issue by plalanne** [CakeDC/users#419]
Hi
i have a new probleme with the plugin
Error: A route matching "array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login', 'prefix' => 'member', '_ext' => NULL, )" could not be found. 
I use prefixes (member, admin) it's the reason why there is 'prefix' => 'member'

the trace is

`None of the currently connected routes match the provided parameters. Add a matching route to config/routes.php

The passed context was:

[
    '_base' => '/local/faq',
    '_port' => '80',
    '_scheme' => 'http',
    '_host' => '192.168.56.101',
    'params' => [
        'plugin' => null,
        'controller' => 'Pages',
        'action' => 'index',
        '_ext' => null,
        'pass' => [],
        'prefix' => 'member',
        '_matchedRoute' => '/member/:controller',
        'isAjax' => false
    ]
]`

Is there something i forget to configure ?

thanks

**Comment by steinkel** [comment]
Hi @plalanne, in this case you'll need to configure a route to match the prefix and connect to the login page for this new prefix, for example:

```
$routes->connect('/member/login', [
        'plugin' => 'CakeDC/Users',
        'controller' => 'Users',
        'action' => 'login',
    ]);
```

Let me know if adding a new route works, if not we'll need to take a deeper look...

**Comment by plalanne** [comment]
Hi,

it's always the same
i try to put the route in
Router::scope('/', function (RouteBuilder $routes) {}
and
Router::prefix('member', function ($routes) {}

the result of the connecterd route given by cakephp is
`Connected Routes
Template	Defaults	Options
/auth/:provider	[ 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialLogin', 'prefix' => null ]	[ 'provider' => 'facebook|twitter|linkedIn|instagram|google', '_ext' => [], 'routeClass' => 'Cake\Routing\Route\Route' ]
/debug_kit/toolbar/clear_cache	[ 'controller' => 'Toolbar', 'action' => 'clearCache', 'plugin' => 'DebugKit' ]	[ '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'Cake\Routing\Route\Route' ]
/debug_kit/toolbar/*	[ 'controller' => 'Requests', 'action' => 'view', 'plugin' => 'DebugKit' ]	[ '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'Cake\Routing\Route\Route' ]
/debug_kit/panels/view/*	[ 'controller' => 'Panels', 'action' => 'view', 'plugin' => 'DebugKit' ]	[ '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'Cake\Routing\Route\Route' ]
/debug_kit/panels/*	[ 'controller' => 'Panels', 'action' => 'index', 'plugin' => 'DebugKit' ]	[ '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'Cake\Routing\Route\Route' ]
/	[ 'controller' => 'Projects', 'action' => 'index', 'plugin' => null ]	[ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/member/login	[ 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login', 'prefix' => false ]	[ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/:controller	[ 'action' => 'index', 'plugin' => null ]	[ 'routeClass' => 'DashedRoute', '_ext' => [] ]
/:controller/:action/*	[ 'action' => 'index', 'plugin' => null ]	[ 'routeClass' => 'DashedRoute', '_ext' => [] ]
/admin/:controller	[ 'action' => 'index', 'prefix' => 'admin', 'plugin' => null ]	[ 'routeClass' => 'InflectedRoute', '_ext' => [] ]
/admin/:controller/:action/*	[ 'action' => 'index', 'prefix' => 'admin', 'plugin' => null ]	[ 'routeClass' => 'InflectedRoute', '_ext' => [] ]
/member/:controller	[ 'action' => 'index', 'prefix' => 'member', 'plugin' => null ]	[ 'routeClass' => 'InflectedRoute', '_ext' => [] ]
/member/:controller/:action/*	[ 'action' => 'index', 'prefix' => 'member', 'plugin' => null ]	[ 'routeClass' => 'InflectedRoute', '_ext' => [] ]
/member/login	[ 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login', 'prefix' => false ]	[ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/api/projects	[ 'controller' => 'Projects', 'action' => 'index', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:id	[ 'controller' => 'Projects', 'action' => 'view', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/articles/:id	[ 'controller' => 'Articles', 'action' => 'view', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects	[ 'controller' => 'Projects', 'action' => 'index', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects	[ 'controller' => 'Projects', 'action' => 'add', '_method' => 'POST', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:id	[ 'controller' => 'Projects', 'action' => 'view', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:id	[ 'controller' => 'Projects', 'action' => 'edit', '_method' => [ (int) 0 => 'PUT', (int) 1 => 'PATCH' ], 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:id	[ 'controller' => 'Projects', 'action' => 'delete', '_method' => 'DELETE', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags	[ 'controller' => 'Tags', 'action' => 'index', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags	[ 'controller' => 'Tags', 'action' => 'add', '_method' => 'POST', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:id	[ 'controller' => 'Tags', 'action' => 'view', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:id	[ 'controller' => 'Tags', 'action' => 'edit', '_method' => [ (int) 0 => 'PUT', (int) 1 => 'PATCH' ], 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:id	[ 'controller' => 'Tags', 'action' => 'delete', '_method' => 'DELETE', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:tag_id/articles	[ 'controller' => 'Articles', 'action' => 'index', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:tag_id/articles	[ 'controller' => 'Articles', 'action' => 'add', '_method' => 'POST', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:tag_id/articles/:id	[ 'controller' => 'Articles', 'action' => 'view', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:tag_id/articles/:id	[ 'controller' => 'Articles', 'action' => 'edit', '_method' => [ (int) 0 => 'PUT', (int) 1 => 'PATCH' ], 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:tag_id/articles/:id	[ 'controller' => 'Articles', 'action' => 'delete', '_method' => 'DELETE', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/tags/:tag_id/articles/list	[ 'controller' => 'Articles', 'action' => 'articles_tag', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/articles	[ 'controller' => 'Articles', 'action' => 'index', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/api/projects/:project_id/articles/:id	[ 'controller' => 'Articles', 'action' => 'view', '_method' => 'GET', 'plugin' => null ]	[ 'id' => '[0-9]+|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}', 'pass' => [ (int) 0 => 'id' ], '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'DashedRoute' ]
/users/:controller	[ 'action' => 'index', 'plugin' => 'CakeDC/Users' ]	[ 'routeClass' => 'DashedRoute', '_ext' => [] ]
/users/:controller/:action/*	[ 'action' => 'index', 'plugin' => 'CakeDC/Users' ]	[ 'routeClass' => 'DashedRoute', '_ext' => [] ]
/auth/twitter	[ 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'twitterLogin', 'provider' => 'twitter' ]	[ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/accounts/validate/*	[ 'plugin' => 'CakeDC/Users', 'controller' => 'SocialAccounts', 'action' => 'validate' ]	[ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/profile/*	[ 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'profile' ]	[ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/login	[ 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login' ]	[ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/logout	[ 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'logout' ]	[ '_ext' => [], 'routeClass' => 'DashedRoute' ]`

**Comment by ramb0Ram** [comment]
I had the same problem, solve it like this:


**routes.php**
```
Router::scope('/', function (RouteBuilder $routes) {
    Router::prefix('Admin',function($routes){
        $routes->fallbacks('InflectedRoute');
    });
   ...
```

The important part is in users.php file. Change Auth.loginAction.prefix for **false** insted of null

**Comment by plalanne** [comment]
Hi,

it's better but now i have a new message
` Error: CakeDC/Users.UsersController could not be found.

Error: Create the class UsersController below in file: /vendor/cakedc/users/src/Controller/UsersController.php`

but the file exist !!! i really don't understand !!!

**Comment by steinkel** [comment]
@plalanne are you using the latest release of the plugin?

**Comment by plalanne** [comment]
yes,
i just do a composer update et there is nothing to install or update

**Comment by steinkel** [comment]
weird, I'll need to test this locally...

**Comment by infokani** [comment]
@ramb0Ram answer is solution tnx

> Change Auth.loginAction.prefix for **false insted of null**

**Comment by rrd108** [comment]
After upgrading to Cake 3.6 and CakeDC/Users 7 if I remove `Plugin::routes();` from the end of `/config/routes.php` file I get this: `Error: A route matching "array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login', 'prefix' => false, '_ext' => NULL, )" could not be found.`

Any idea why?

**Comment by tersmitten** [comment]
We have the same problem with one of our plugins

**Comment by saeideng** [comment]
remove 
`Plugin::routes();`
use `addPlugin()` for all plugin (after cake 3.6.6 )

**Comment by rrd108** [comment]
If I put `$this->addPlugin('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);` into my config/bootstrap.php file or into my src/Application.php file as the cookbook requires I got the following error message.

The plugin class `CakeDC\Users\Plugin` cannot be found. Ensure your autoloader is correct.

What do I miss?

**Comment by tersmitten** [comment]
I think this is because of a missing `Plugin.php` in [src](https://github.com/CakeDC/users/tree/7.0.2/src)

**Comment by steinkel** [comment]
ok, let me add a new issue related to this one as it's already closed, thank you for your feedback here

**Comment by saeideng** [comment]
@rrd108 
>The plugin class CakeDC\Users\Plugin cannot be found. Ensure your autoloader is correct.

are you using cake 3.6.6?

**Comment by rrd108** [comment]
My fault, it was 3.6.5

But after upgradeing to 3.6.6 I get this error message.

Error: A route matching "array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login', 'prefix' => false, '_ext' => NULL, )" could not be found.

**Comment by saeideng** [comment]
I tested in local
it worked for me
`localhost/site/login`

**Comment by saeideng** [comment]
tested on both way `->addPlugin` and `Plugin::load()`

**Comment by rrd108** [comment]
Strange . It seems the plugin works (at least the auth component loads), as when I try to access any page it redirects me to the login page, but it does not find it. Any guess what do I miss?

**Comment by rrd108** [comment]
I think I found the solution.

It seems my src/Application.php was not updated when I uograded from 3.6.5 to 3.6.6 after fixing this the plugin works fine.

**Comment by jhob101** [comment]
Have also been wrestling the same issue. Updating src/Application.php worked - thanks!
