### ISSUE TITLE
JSON views not working in 3.2.3?

### ISSUE THREAD

**Issue by gentunian** [CakeDC/users#420]
Hi,

I've copied my site to another server and I did `composer update`. I spent almost 3 hours finding why my .json views were redirecting to home after I found out that it was CakeDC/Users plugin (I first thought it was apache config).

After setting `composer.json` to require 3.2 and run `composer update`:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing cakedc/users (3.2.3)
  - Installing cakedc/users (3.2.0)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

It is working again. It would be nice to find any logs or info I could share with you, as I didn't find any information. It was just a try to disable the plugin and found that .json views were working.

Anything I could do to share info, please let me know.

Regards,

**Comment by gentunian** [comment]
Ok, thanks to `savant` at #cakephp channel I starting to test different versions.

So I've found that it works on `3.2.0` but it started to fail in `3.2.1` with the addition of `extension`: https://github.com/CakeDC/users/commit/b5885df743719b77ec50e64dfa454d2bbd979563

So I finally configured `config/permissions.php` with `extension` set to `json`:

```
[
            'role' => ['user'],
            'controller' => ['Data'],
	    'extension' => 'json',
            'action' => '*',
            'allowed' => true,
        ],
```

Not sure If it's a bug. Doc says that extension is optional.

Cheers

**Comment by steinkel** [comment]
Hi @gentunian this is actually a feature, as now extensions are protected by default when using the plugin and you can set them as public (as you did in the permissions file) or if your json extension does not require auth at all you could add this to AppController using `Auth->allow()`

The reference to optional in the documentation means you can use or not this key in the options array to configure the permission (and default will be NOT using extension). 

Do you think we should add it to the docs in a "Working with extensions" section?

Thanks,

**Comment by gentunian** [comment]
Hi @steinkel, thanks for the reply and clarifcations about it.

I think is worth mention or somehow warning developers. For example, any working code will break after the update. In my case the update was accidental (a migration to another server). For sure is not ok to go updating plugins without reading the changelog.

Regards,
