### ISSUE TITLE
Problem with custom UsersTable 

### ISSUE THREAD

**Issue by ironbone** [CakeDC/users#421]
The following problem appears in version 3.2.3. In version 3.2.2 everything works well.

Description. I use my own users table. There I have foreignKey => country_id
```
class UsersTable extends \CakeDC\Users\Model\Table\UsersTable
{
    public function initialize(array $config)`
.....
$this->belongsTo('Countries', [
            'foreignKey' => 'country_id',
            'joinType' => 'INNER'
        ]);
....
}

```

In version 3.2.3 when calling in my AppController:
`$countries = $this->Users->Countries->find('list');`
I get the error
`Table "CakeDC\Users\Model\Table\UsersTable" is not associated with "Countries"`

I have the same even if I change the table and antity name to MyUsers, MyUser.
It seams that the plagin use all the time CakeDC\Users\Model\Table\UsersTable and ignores
'Users.table' => 'MyUsers',
in my users.php

**Comment by ajibarra** [comment]
Fixed in #325. Tagged 3.2.4
