### ISSUE TITLE
Using 'email' as username still requires an 'username' on user creation

### ISSUE THREAD

**Issue by drmonkeyninja** [CakeDC/users#424]
I am perhaps approaching this wrong, but I am trying to use the `email` as the username as described [in the docs](https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md#using-the-users-email-to-login):-

```
Configure::write('Auth.authenticate.Form.fields.username', 'email');
```

Everything seems to work fine, except when it comes to creating a new user as I no longer want to include the now defunct `username` field in any add user form. This seems to cause a validation error on save arising from the `username` `notEmpty` rule on creation in `UsersTable::validationDefault`. The response to issue #290 seems to imply you can remove the `username` field from a registration form.

I've got round this by extending the `UsersTable` class to remove the rule when `email` is being used like this:-

```
public function validationDefault(Validator $validator)
{
    $validator = parent::validationDefault($validator);
    $username = Configure::read('Auth.authenticate.Form.fields.username');
    if ($username === 'email') {
        $validator->remove('username');
    }
    return $validator;
}
```

Is this check something missing from the plugin?

**Comment by alexlambson** [comment]
I got around this by extending the Users model and over-riding the default validation.

**Comment by steinkel** [comment]
I think it makes sense to leave this up to the user extending the UsersTable and configure it based on his own requirements. Let me know if we should do anything else here... Thanks!
