### ISSUE TITLE
How to allow superusers to create superusers?

### ISSUE THREAD

**Issue by flangofas** [CakeDC/users#429]
What is the best approach to do this? 
I had this task today and the way that I found is by extending users plugin... then I was wondering if it is a good idea to make this configurable instead to avoid all the overriding for a single value. 

Unless, there is a better way to do it?

Thanks,

**Comment by steinkel** [comment]
Hi @flangofas the superuser is intended as an administrative user only for development. If you need a managed superuser, I would create a superuser role, and a rule to give him access to everything, then allow administrative users to set the role as "superadmin" and you are done.

**Comment by flangofas** [comment]
Thanks @steinkel
