### ISSUE TITLE
restriction to registration of new users or manual adding

### ISSUE THREAD

**Issue by jarekgol** [CakeDC/users#434]
Hi!
I don't know if this is a proper place, but I need help with make restriction for registration of new users. I use yours plugin and now anyone can make new account. It has default role that hasn't got much privileges but I want to make some manual "allow".

ps. this link https://www.cakedc.com/contribution-guidelines does not work.

**Comment by steinkel** [comment]
https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md
Check `Registration.active` option, this should enable/disable registration in your app.
Thanks for the link report, we'll open an internal ticket in our site to fix this.

**Comment by jarekgol** [comment]
Thanks for indication.
ok, and then how do I add users?
Can I just insert values into DB? Which fields are mandatory to work? And what is password format?

**Comment by steinkel** [comment]
Hey @jarekgol you have a backend available for superadmins under
/users/users/add

You can create users via shell too, check https://github.com/CakeDC/users/blob/master/src/Shell/UsersShell.php#L54

Thanks

**Comment by jarekgol** [comment]
This is what I was looking for. auth piece of code (and your plugin) was added by my friend and he wrote by his hand editing of users. We had problems with expiration if someone didn't click email fast enough and now I see it can be changed in nice way (we just delete them from DB and they have to do it again)
I suppose he didn't know about this /users/users either. Thank you!
