### ISSUE TITLE
ajax requests no longer work as expected

### ISSUE THREAD

**Issue by synergyhealth** [CakeDC/users#436]
Hi I recently updated to 3.2.3 from 3.2.0 

I have set up permissions.php to allow for specific actions e.g.

```
[
            'role' => 'user',
            'plugin' => 'Content',
            'controller' => 'Articles',
            'action' => ['rating', 'view'],
],
```
I have an ajax function that calls rating.json. Before the upgrade this worked fine for all logged in users.  Now, however, this only works for super user role.  If I remove the .json it works as expected. Is there another setting I need to add to my set up now?
Cheers,
Neysa

**Comment by steinkel** [comment]
Naysa, you need to whitelist your extensions in rules, as extensions are now checked too. To ensure this rule applies to your .json calls ensure adding configuration for your 'extension'  too, see https://github.com/CakeDC/users/blob/master/Docs/Documentation/SimpleRbacAuthorize.md, in your case, try adding
'extension' => '*' to the rule
Thanks,

**Comment by synergyhealth** [comment]
Thank you!
On 28/10/2016, at 11:02 pm, Jorge M. González Martín <notifications@github.com<mailto:notifications@github.com>> wrote:


Naysa, you need to whitelist your extensions in rules, as extensions are now checked too. To ensure this rule applies to your .json calls ensure adding configuration for your 'extension' too, see https://github.com/CakeDC/users/blob/master/Docs/Documentation/SimpleRbacAuthorize.md, in your case, try adding
'extension' => '*' to the rule
Thanks,
