### ISSUE TITLE
Bug: All new users added via shell are superusers

### ISSUE THREAD

**Issue by digitalfotografen** [CakeDC/users#438]
There is a bug in the addUser command in Users shell. All users created with this command gets superuser privileges (independent of role). 

$userEntity->is_superuser is default false, and should stay false for normal users.

Line 95 in UsersShell.php should be removed to solve this
        $userEntity->is_superuser = true;

**Comment by steinkel** [comment]
Closed per #440

**Comment by mamchenkov** [comment]
This can be interpreted as a feature :)

Creating users via command line is a rare occasion in my case, and I **do** want them to be super administrators.  However now (after the PR #440), I have to use `addSuperUser` method, which does not provide any flexibility, like controlling the username, password, email, etc.

:confused:

**Comment by steinkel** [comment]
We could think about creating a unique addUser shell method, and allow passing the role but also set the superuser flag, or generate random usernames and passwords like the addSuperuser method does, makes sense?

**Comment by digitalfotografen** [comment]
One solution is to give the addSuperuser method the same options as the addUser, and if options are left it keeps the current behaviour with random options. Then the difference between addUser and addSuperuser makes better sense.

I can volunteer to make this change to the addSuperuser method.
