### ISSUE TITLE
Cannot override Model to use my custom table

### ISSUE THREAD

**Issue by gooseleggs** [CakeDC/users#446]
Hello

I have been trying to follow the guide on extending the plugin as I want to override the Model.  

I have created a table called app_users, configured an AppUsersTable.php and AppUser.php class as per the documentation.
I have done the following:
Configure::write('Users.config', ['users']);

But putting this in just gives me an error (Error: The application is trying to load a file from the Users plugin. ).  I gather I need to create a controller for this as well?
Plugin::load('Users', ['routes' => true, 'bootstrap' => true]);

If add in the config/users.php as per the doco,  I can see in the MySQL queries, it has
...FROM user AppUsers WHERE ...  which wasn't the outcome I was hoping for.

What else do I need to do to override the model controller.  Dont need to extend the controller at the moment.

I think I followed the doco correctly.  Running Cakephp 3.3.8

**Comment by DrizztDarnok** [comment]
do i have to note anything special if i want to do both?
custom controller & custom tables?

**Comment by steinkel** [comment]
Do I have to note anything special if i want to do both? > No, both are extended in a different way, and you can extend both at the same time.

And should I copy the table and entity from the plugin into my structure? > Not needed, you can create your own table and bake the table&entity for them if you want, or extend the table & entity from the plugin, whatever is easier for you.

We'll fix that typo in a bit, thanks!

**Comment by DrizztDarnok** [comment]
if i extend my tables do i have to change something in the Auth?

**Comment by steinkel** [comment]
Yes, you'll need to configure the plugin to use your custom table 
https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md#extending-the-model-tableentity

    return [
        'Users.table' => 'MyUsers',
    ];

**Comment by DrizztDarnok** [comment]
I already did that. Its still the same problem. 
Just to be sure:
- Every change is in my own project? i change nothing in the plugin code.
- I can delete the original users table?
- I have a users.php file in my config folder with only this `return [
    'Users.table' => 'MyUsers',
];` inside

What i also noticed was that if i change 'Users.table' => 'MyUsers', to for example 'Users.table' => 'MybadUsers', it tells my that 'MybadUsers' Table cannot be found .... 
I'm really greatful that you help me. I'm just lost right now.

**Comment by steinkel** [comment]
* All changes in your app, plugin code is not changed
* Yes, as you are going to use my_users table
* OK, then you need to tell the plugin to load the file, see the Configuration chapter in documentation.

Thanks,

**Comment by DrizztDarnok** [comment]
I'm sorry but I don't understand what you mean?

**Comment by steinkel** [comment]
You need to load you config/users.php config file this way.

In bootstrap.php use 

    Configure::write('Users.config', ['users']);
    Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);

https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md

**Comment by DrizztDarnok** [comment]
yeah sure i did. 
Thats my problem stil giving me the error...

**Comment by steinkel** [comment]
Sorry I would need to get access to your code to be able to debug it...

**Comment by DrizztDarnok** [comment]
what do you need?

**Comment by steinkel** [comment]
Push the related (not all) code into a public git repo/gist
OR use an environment like c9.io and provide me access to take a look.

Thanks,

**Comment by DrizztDarnok** [comment]
https://github.com/DrizztDarnok/magic_matrix

Her are alle the files

**Comment by steinkel** [comment]
comments added

**Comment by DrizztDarnok** [comment]
i have updated as you told me. (already pushed)
now i get: Unknown finder method "auth" 
With this message:
   Could this be caused by using Auto-Tables?

    Some of the Table objects in your application were created by instantiating "Cake\ORM\Table" instead  of any other specific subclass.

    This could be the cause for this exception. Auto-Tables are created for you under the following       circumstances:

    The class for the specified table does not exist.
    The Table was created with a typo: TableRegistry::get('Atricles');
    The class file has a typo in the name or incorrect namespace: class Atricles extends Table
    The file containing the class has a typo or incorrect casing: Atricles.php
    The Table was used using associations but the association has a typo: $this->belongsTo('Atricles')
    The table class resides in a Plugin but no plugin notation was used in the association definition.
    Please try correcting the issue for the following table aliases:

    MyUsers

Thanks again for your help. Im already siting on this Problem for 4 Days now...

**Comment by steinkel** [comment]
Ensure you have a findAuth custom finder, or change the finder in the Auth configuration.

It would be a good idea to provide this finder in a behavior, for now, copy it into your new table

 /**
     * Custom finder to filter active users
     *
     * @param Query $query Query object to modify
     * @param array $options Query options
     * @return Query
     */
    public function findActive(Query $query, array $options = [])
    {
        $query->where([$this->aliasField('active') => 1]);
        return $query;
    }
    /**
     * Custom finder to log in users
     *
     * @param Query $query Query object to modify
     * @param array $options Query options
     * @return Query
     * @throws \BadMethodCallException
     */
    public function findAuth(Query $query, array $options = [])
    {
        $identifier = Hash::get($options, 'username');
        if (empty($identifier)) {
            throw new \BadMethodCallException(__d('CakeDC/Users', 'Missing \'username\' in options data'));
        }
        $query
            ->orWhere([$this->aliasField('email') => $identifier])
            ->find('active', $options);
        return $query;
    }

**Comment by DrizztDarnok** [comment]
Done that still have the same problem.
Should I also copy the UsersAuthComponent?

**Comment by steinkel** [comment]
No, this does not require UsersAuthComponent, for some reason the finder is not being found in your MyUsers table class. Try to debug this first (try to call the finder from another controller and see if it's there)

**Comment by DrizztDarnok** [comment]
no it also cannot be found from another controller.
I tried this:
        $users = TableRegistry::get('MyUsers');
        $query = $users->find('auth', ['user' => $userEntity]);

**Comment by steinkel** [comment]
Oh looks like your table class is missing a "namespace"

**Comment by DrizztDarnok** [comment]
oh... shit...

**Comment by DrizztDarnok** [comment]
Thank you very much. You Helped me alot. Im sorry for the dumb mistake, but i learned a lot.
I have a final question (hope) i also wanted to override the controller for customization of profile
and profile edit. Did i do it correctly? (pushed into repo)
And do I have to reconnect all routes in cakephp to the new controller and its templates?

**Comment by steinkel** [comment]
You're welcome.

Override the controller is easy, you can use your own controller and you only need to change the users.php configuration (Auth) to point to your controller for login and use the traits you need (check UsersController in the Plugin).

Thanks,
