### ISSUE TITLE
Not found class namespace \ReCaptcha\ReCaptcha($reCaptchaSecret);

### ISSUE THREAD

**Issue by EOM** [CakeDC/users#447]
Fix ReCaptchaTrait.php

Print Error not found files class return new \ReCaptcha\ReCaptcha($reCaptchaSecret);
http://s19.postimg.org/o5040vmxv/Print_de_pantalla_201.png

**Comment by EOM** [comment]
Solution 
`composer require google/recaptcha "~1.1"`

**Comment by steinkel** [comment]
Yes, this is noted in the docs, as recaptcha is optional if you want to use it you'll need to install the package...
