### ISSUE TITLE
Users.Component.UsersAuth.isAuthorized

### ISSUE THREAD

**Issue by EOM** [CakeDC/users#450]
Hi,
I do not see in the documentation where I can do something like these

```
$this->loadModels('Permissions');
$dataPermissionsDb = $this->Permissions->Find('all')->hydrate(false)->toArray();
`Configure::write('Users.SimpleRbac.permissions', $dataPermissionsDb);`
```

**Comment by steinkel** [comment]
you can do this right after the plugin is loaded, for example in an utility class and call it from bootstrap.php. I would suggest to cache the permissions generated...

**Comment by EOM** [comment]
Hi my \App\Config\Permissions.php and Solution.
 
`<?php
namespace App\Config;

use Cake\Cache\Cache;
use Cake\Controller\Controller;


class Permissions extends Controller
{
    public function get()
    {
        $base = [
            [
                'role' => '*',
                'plugin' => 'CakeDC/Users',
                'controller' => '*',
                'action' => '*',
            ],
            [
                'role' => 'user',
                'plugin' => 'CakeDC/Users',
                'controller' => 'Users',
                'action' => ['register', 'edit', 'view'],
            ],
            [
                'role' => 'user',
                'plugin' => 'CakeDC/Users',
                'controller' => 'Users',
                'action' => '*',
                'allowed' => false,
            ],
            [
                'role' => ['user'],
                'controller' => ['Pages'],
                'action' => ['other', 'display'],
                'allowed' => true,
            ],
        ];

        $P_db = (array)$this->get_db($cache = false);
        $out = array();
        $out = $base;

        // Loop
        foreach ($P_db as $d) {
            $r = array();
            if(isset($d['role'])==true && (is_array($d['role']) || strlen(trim($d['role'])))){
                $r['role'] = $d['role'];
            }
            if(isset($d['plugin'])==true && (is_array($d['plugin']) || strlen(trim($d['plugin'])))){
                $r['plugin'] = $d['plugin'];
            }
            if(isset($d['prefix'])==true && (is_array($d['prefix']) || strlen(trim($d['prefix'])))){
                $r['prefix'] = $d['prefix'];
            }
            if(isset($d['extension'])==true && (is_array($d['extension']) || strlen(trim($d['extension'])))){
                $r['extension'] = $d['extension'];
            }
            if(isset($d['controller'])==true && (is_array($d['controller']) || strlen(trim($d['controller'])))){
                $r['controller'] = $d['controller'];
            }
            if(isset($d['action'])==true && (is_array($d['action']) || strlen(trim($d['action'])))){
                if(is_array($d['action'])){
                    $r['action'] = $d['action'];
                }else{
                    $d['action'] = trim($d['action']);
                    if(strlen(trim($d['action']))>=2 && strpos($d['action'], ',')>1){
                        $actions = explode(',',$d['action']);
                        if(is_array($actions)==true){
                            $r['action'] = $actions;
                        }else{
                            $r['action'] = '';
                        }
                    }else{
                        $r['action'] = $d['action'];
                    }
                }
            }
            if(isset($d['allowed'])==true && strlen(trim($d['allowed']))){
                if(trim($d['allowed'])=='1'){
                    $d['allowed'] = true;
                }elseif (trim($d['allowed'])=='0'){
                    $d['allowed'] = false;
                }else{
                    $d['allowed'] = trim($d['allowed']);
                }
                $r['allowed'] = $d['allowed'];
            }
            // Set out
            $out[] = $r;
        }
        $p = [
            'Users.SimpleRbac.permissions' => $out
        ];
        //exit(debug($p));
        // Out
        return $p;
    }

    protected function get_db($cache=true)
    {
        $where = [
            'fields' => [
                'role',
                'plugin',
                'prefix',
                'extension',
                'controller',
                'action',
                'allowed'
            ]
        ];

        $d = array();
        // Load cache data..?
        if($cache== true){
            // Get data in cache
            $d = Cache::read('Permissions');
        }else{
            $d = false;
        }
        // Date in Cache ..?
        if ($d === false) {
            $this->loadModel('Permissions');
            try {
                // Get data
                $d = (array)$this->Permissions->find('all', $where)
                    ->hydrate(false)
                    ->toArray();
                // Set Cache
                Cache::write('Permissions', $d);
            } catch (PDOException $e) {
                echo __('Exception: Problem DataBase');
            }
        }
        // Out data
        return $d;
    }
}

// Get Permissions DB
$p = New Permissions();
return $p->get();
`
