### ISSUE TITLE
404 not found after Facebook login

### ISSUE THREAD

**Issue by Josecanalla** [CakeDC/users#452]
I am trying the plugin and I have a problem with Facebook login. If I have session closed on facebook, when I press "Sign in with facebook" I get the facebook form to log in. When I login, I get 404 not found page on this URL: http://localhost/auth/facebook?code=AQCGxfeVUGKxdg1Q6Eg8hESy1Isy4GXpMVKzZtH5I_tR8_RoakZ-Fr7aUB5ZnDh9ZjDtDgeafWtKbQPuk-jAea7LvS0bAIlZ53BwcF48MBZi........... (continues).

If I am with session opened on Facebook, I get directly the 404 not found error page. 
In my Facebook app I have the URL http://localhost/auth/facebook added.

What can I do? Thanks!

**Comment by Josecanalla** [comment]
Well, the error is only in localhost. When I upload the project to a server, it works OK. 

I only edit in the users.php configuration file the graphapi version from 2.5 to 2.8 which is the current Facebook api version. In the Facebook panel I configure: domains of the application: yourdomain.com and in the URL of the site http://yourdomain.com/auth/facebook and it works. I hope may it helps to others.

Is there any way to work on localhost for development purposes?

**Comment by steinkel** [comment]
No, I don't think Facebook will allow you to do this...

You did the right thing, create a development virtualhost and using it in Facebook app.
Thanks
