### ISSUE TITLE
How to change social login language?

### ISSUE THREAD

**Issue by Josecanalla** [CakeDC/users#453]
When I print Facebook social login in a view with $this->User->socialLogin("facebook"); , I get "Sign in with facebook". How can I display it in spanish language?

Thanks

**Comment by steinkel** [comment]
Hi @Josecanalla we are using a string you can translate to your own language, there are several languages provided by the plugin, listed here > https://github.com/CakeDC/users/blob/master/Docs/Documentation/Translations.md so you only would need to switch to the target language you are looking for, for example, spanish and the strings will be translated to spanish. See more about translations here > http://book.cakephp.org/3.0/en/core-libraries/internationalization-and-localization.html
