### ISSUE TITLE
Google login not works

### ISSUE THREAD

**Issue by Josecanalla** [CakeDC/users#455]
I have already working the Facebook and Twitter login. But with Google login, after I give permissions to Google, I get "You are not autorized to access that location" and the user are not logged in.

**Comment by rochamarcelo** [comment]
Please see if you get any error message at SocialAuthenticate:: _authenticate in line 191: https://github.com/CakeDC/users/blob/master/src/Auth/SocialAuthenticate.php#L191

**Comment by Josecanalla** [comment]
Yes, I get an error. I need to enable Google+ API and Contacts API in the Google panel. It's solved now.

Thanks!
