### ISSUE TITLE
sociallogin -> missing controller

### ISSUE THREAD

**Issue by tgoeminne** [CakeDC/users#456]
When clicking facebook login button. I get the error: 

Error: CakeDC/Users.UsersController could not be found.

Error: Create the class UsersController below in file: /opt/bitnami/frameworks/cakephp/vendor/cakedc/users/src/Controller/UsersController.php

I checked and the file is there, why is it throwing this error?

**Comment by tgoeminne** [comment]
'Auth' => [
    	'loginAction' => [
    				'plugin' => 'CakeDC/Users',
    				'controller' => 'Users',
    				'action' => 'login',
    				'prefix' => null
    	],
        'authenticate' => [
            'all' => [
                'finder' => 'active',
            ],
            'CakeDC/Users.RememberMe',
            'Form',
        ],
        'authorize' => [
            'CakeDC/Users.Superuser',
            'CakeDC/Users.SimpleRbac',
        ],
    ],
'OAuth' => [
			'path' => ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialLogin', 'prefix' => null],
			'providers' => [
					'facebook' => [
								'className' => 'League\OAuth2\Client\Provider\Facebook',
								'options' => [
										'graphApiVersion' => 'v2.5',
										'redirectUri' => 'http://www.url.com/auth/facebook',
								]
						],
					'google' => [
								'className' => 'League\OAuth2\Client\Provider\Google',
								'options' => [
										'userFields' => ['url', 'aboutMe'],
										'redirectUri' => 'http://www.url.com/auth/google',
								]
					],
			],
	]

After adding this, it forwards me to facebook website, but when returning i get a You are not authorized to access that location. message on login page

**Comment by tgoeminne** [comment]
I have set Cache::disable(); in bootstrap, when I change the users.php

'Social' => [
            //enable social login
            'login' => true,
        ],

I get the errors: The "_cake_model_" cache configuration does not exist.

**Comment by tgoeminne** [comment]
I am assuming it could be a problem with routes?

Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);

Is it not supposed to load website.com/users to the index action of users? I have to write website.com/users/users instead?

**Comment by tgoeminne** [comment]
also there is a link on the view profile page that links to -> /users/accounts and this throws missing controller error

**Comment by steinkel** [comment]
hi @tgoeminne you can check the defined routes here: https://github.com/CakeDC/users/blob/master/config/routes.php we provide
* /login
* /logout
* /profile
* /users for the admin panel
* /accounts/validate for email validation link callbacks
* /auth/xxx if socialLogin enabled

If you want to access the users index page, the url would be
/users/users/

I don't see a link to /user/accounts here https://github.com/CakeDC/users/blob/master/src/Template/Users/profile.ctp is this what you are talking about?

Thank you!

**Comment by tgoeminne** [comment]
In the view.ctp template there is a link to accounts controller. This link returns missing controller.

**Comment by tgoeminne** [comment]
Is there anything else I need to change to make socialogin work? It always shows not authorized to access that location when get back to login page, from facebook..

**Comment by steinkel** [comment]
Ah I was looking to profile, let me fix the view.ctp
Thank you for reporting this one

**Comment by steinkel** [comment]
closed per #462 thanks!
