### ISSUE TITLE
Can't log in with facebook using graphApi 2.5

### ISSUE THREAD

**Issue by rochamarcelo** [CakeDC/users#457]
The default graphApiVersion is 2.5, which query for "bio" field, but facebook stills returns the error:
'OAuth "Facebook Platform" "invalid_request" "(#12) bio field is deprecated for versions v2.8 and higher"''. This message is not showing in error.log or debug.log files, I founded debugging AbstractProvider::sendRequest in "app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php" and SocialAuthenticate::_authenticate in "/app/vendor/cakedc/users/src/Auth/SocialAuthenticate.php".  To solve the problem we have to use version 2.8, if not possible to change config/users.php we should at least consider to log this message.

**Comment by steinkel** [comment]
That's a good catch, we should definitely log it at least. Closing this ticket per #458 Thanks!
