### ISSUE TITLE
Error with Twitter when email is not present

### ISSUE THREAD

**Issue by rochamarcelo** [CakeDC/users#459]
When the twitter api doesn't return any email, the \Auth\SocialAuthenticate::_touch method returns a Cake\Network\Response (it should return the user data) then the LoginTrait::_afterIdentifyUser set the AuthComponent::user with that renspose value, causing the error "Invalid data type, must be an array or \ArrayAccess instance."

The \Auth\SocialAuthenticate::_touch should always return the user data even when there is no user email, correct?

object(Cake\Network\Response) {

	'status' => (int) 302,
	'contentType' => 'text/html',
	'headers' => [
		'Location' => 'http://awesome.dev/users/users/social-email'
	],
	'file' => null,
	'fileRange' => [],
	'cookies' => [],
	'cacheDirectives' => [],
	'body' => null

}

2016-12-01 17:43:39 Error: [InvalidArgumentException] Invalid data type, must be an array or \ArrayAccess instance.
Request URL: /auth/twitter?oauth_token=here_was_the_original_token
Stack Trace:
#0 /www/app/vendor/cakephp/cakephp/src/Controller/Component/AuthComponent.php(691): Cake\Utility\Hash::get(Object(Cake\Network\Response), 'id')
#1 /www/app/vendor/cakedc/users/src/Controller/Component/RememberMeComponent.php(105): Cake\Controller\Component\AuthComponent->user('id')
#2 /www/app/vendor/cakephp/cakephp/src/Event/EventManager.php(424): CakeDC\Users\Controller\Component\RememberMeComponent->setLoginCookie(Object(Cake\Event\Event), Object(Cake\Network\Response))
#3 /www/app/vendor/cakephp/cakephp/src/Event/EventManager.php(391): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#4 /www/app/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#5 /www/app/vendor/cakedc/users/src/Controller/Traits/LoginTrait.php(208): Cake\Controller\Controller->dispatchEvent('Users.Component...', Array)
#6 /www/app/vendor/cakedc/users/src/Controller/Traits/LoginTrait.php(58): CakeDC\Users\Controller\UsersController->_afterIdentifyUser(Object(Cake\Network\Response), true)
#7 [internal function]: CakeDC\Users\Controller\UsersController->twitterLogin()
#8 /www/app/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#9 /www/app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(122): Cake\Controller\Controller->invokeAction()
#10 /www/app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(96): Cake\Http\ActionDispatcher->_invoke(Object(CakeDC\Users\Controller\UsersController))
#11 /www/app/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 /www/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#13 /www/app/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 /www/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#15 /www/app/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#16 /www/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#17 /www/app/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#18 /www/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#19 /www/app/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#20 /www/app/vendor/cakephp/cakephp/src/Http/Server.php(92): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#21 /www/app/webroot/index.php(37): Cake\Http\Server->run()
#22 {main}

**Comment by ajibarra** [comment]
@rochamarcelo we don't rely on getting email from twitter but we redirect to social email action to let the user enter their email and then validate it with the usual email validation workflow. From what I see the response is correct, and you should not get any error. I will take a look to the twitter workflow to see what happens and let you know if I can reproduce the bug. Thanks for reporting.

**Comment by suhaboncukcu** [comment]
Getting the same error with Twitter on ```Hash::check``` from SimpleRbacAuthorize.php authorize function

**Comment by caicedodavid** [comment]
I am also using trying to use the twitter login but when I get redirected to my website, nothing happens. The Facebook login is working fine.

**Comment by ajibarra** [comment]
Hi, I was doing some testing today and I fixed an issue which happened when Twitter returned an email. Initially Twitter didn't return the email so if found it caused an issue mapping raw data. However it has nothing to do with the issue you are reporting. I tested both workflows (with and without email) and both work fine now. 

I will ask other people on the team to test as well but it would be good if you could provide Cake Version, Users plugin version, web server version, and any other info that could help us to identify this issue.

Thanks

**Comment by suhaboncukcu** [comment]
Hi @ajibarra 

I forced email and got the same result when I have email too. 

This is my users.php config file:
```php
<?php
return [
    'Users' => [
        'table' => 'MyUsers',
        'auth' => true,
        'Email' => [
            //determines if the user should include email
            'required' => true,
            //determines if registration workflow includes email validation
            'validate' => false,
        ],
        'Registration' => [
            //determines if the register is enabled
            'active' => true,
            //determines if the reCaptcha is enabled for registration
            'reCaptcha' => false,
            //ensure user is active (confirmed email) to reset his password
            'ensureActive' => false
        ],
        'Tos' => [
            //determines if the user should include tos accepted
            'required' => true,
        ],
        'Social' => [
            //enable social login
            'login' => true,
        ],
        //Avatar placeholder
        'Avatar' => ['placeholder' => 'CakeDC/Users.avatar_placeholder.png'],
        'RememberMe' => [
            //configure Remember Me component
            'active' => true,
        ],
        'Key' => [
            'Session' => [
                //session key to store the social auth data
                'social' => 'Users.social',
                //userId key used in reset password workflow
                'resetPasswordUserId' => 'Users.resetPasswordUserId',
            ],
            //form key to store the social auth data
            'Form' => [
                'social' => 'social'
            ],
            'Data' => [
                //data key to store the users email
                'email' => 'email',
                //data key to store email coming from social networks
                'socialEmail' => 'info.email',
                //data key to check if the remember me option is enabled
                'rememberMe' => 'remember_me',
            ],
        ],
    ],
    'Auth' => [
        'authenticate' => [
            'all' => [
                'finder' => 'active',
            ],
            'CakeDC/Users.RememberMe',
            'Form' => [
                'fields' => [
                    'username' => 'email'
                ]
            ],
        ],
        'authorize' => [
            'CakeDC/Users.Superuser',
            'CakeDC/Users.SimpleRbac',
        ],
    ],
    'OAuth' => [
        'path' => ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialLogin', 'prefix' => null],
        'providers' => [
            'facebook' => [
                'className' => 'League\OAuth2\Client\Provider\Facebook',
                'options' => [
                    'graphApiVersion' => 'v2.8',
                    'redirectUri' => 'http://domain.com/auth/facebook',
                    'clientId' => 'id',
                    'clientSecret' => 'secret',
                ]
            ],
            'twitter' => [
                'options' => [
                    'redirectUri' => 'http://domain.com/auth/twitter',
                    'clientId' => 'id',
                    'clientSecret' => 'secret',
                ]
            ],
        ],
    ]
];
```


My cakephp version: ```3.3.9```
My users plugin version according to my composer: ```"cakedc/users": "^3.2"```

**Comment by caicedodavid** [comment]
Fixed my issue. Did not Know that I had to put the Redirect URL in twitter as http://domain.com/auth/twitter. My bad.

**Comment by suhaboncukcu** [comment]
updating to latest release fixed my issue.

**Comment by steinkel** [comment]
nice!
