### ISSUE TITLE
facebook login

### ISSUE THREAD

**Issue by tgoeminne** [CakeDC/users#464]
Here is my relevant code:

Bootstrap:

Configure::write('Users.config', ['users']);
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
Configure::write('Users.Social.login',true);
Configure::write('Auth.authenticate.Form.fields.username', 'email');

Configure::write('OAuth.providers.facebook.options.clientId', 'xxxxxxxxx');
Configure::write('OAuth.providers.facebook.options.clientSecret','xxxxxxxxxxxxxx');

Configure::write('OAuth.providers.google.options.clientId', 'xxxxxxxxxxxx');
Configure::write('OAuth.providers.google.options.clientSecret', 'xxxxxxxxxxxx');

Configure::write('Users.reCaptcha.key', 'YOUR RECAPTCHA KEY');
Configure::write('Users.reCaptcha.secret', 'YOUR RECAPTCHA SECRET');
Configure::write('Users.reCaptcha.registration', false); //enable on registration
Configure::write('Users.reCaptcha.login', false); //enable on login

config/users.php

$config = [
		'Users' => [
				//Table used to manage users
				'table' => 'CakeDC/Users.Users',
				//configure Auth component
				'auth' => true,
				//Password Hasher
				'passwordHasher' => '\Cake\Auth\DefaultPasswordHasher',
				//token expiration, 1 hour
				'Token' => ['expiration' => 3600],
				'Email' => [
						//determines if the user should include email
						'required' => true,
						//determines if registration workflow includes email validation
						'validate' => true,
				],
				'Registration' => [
						//determines if the register is enabled
						'active' => true,
						//determines if the reCaptcha is enabled for registration
						'reCaptcha' => true,
						//allow a logged in user to access the registration form
						'allowLoggedIn' => false,
						//ensure user is active (confirmed email) to reset his password
						'ensureActive' => false
				],
				'reCaptcha' => [
						//reCaptcha key goes here
						'key' => null,
						//reCaptcha secret
						'secret' => null,
						//use reCaptcha in registration
						'registration' => false,
						//use reCaptcha in login, valid values are false, true
						'login' => false,
				],
				'Tos' => [
						//determines if the user should include tos accepted
						'required' => true,
				],
				'Social' => [
						//enable social login
						'login' => true,
				],
				'Profile' => [
						//Allow view other users profiles
						'viewOthers' => true,
						'route' => ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'profile'],
				],
				'Key' => [
						'Session' => [
								//session key to store the social auth data
								'social' => 'Users.social',
								//userId key used in reset password workflow
								'resetPasswordUserId' => 'Users.resetPasswordUserId',
						],
						//form key to store the social auth data
						'Form' => [
								'social' => 'social'
						],
						'Data' => [
								//data key to store the users email
								'email' => 'email',
								//data key to store email coming from social networks
								'socialEmail' => 'info.email',
								//data key to check if the remember me option is enabled
								'rememberMe' => 'remember_me',
						],
				],
				//Avatar placeholder
				'Avatar' => ['placeholder' => 'CakeDC/Users.avatar_placeholder.png'],
				'RememberMe' => [
						//configure Remember Me component
						'active' => true,
						'Cookie' => [
								'name' => 'remember_me',
								'Config' => [
										'expires' => '1 month',
										'httpOnly' => true,
								]
						]
				],
		],
		//default configuration used to auto-load the Auth Component, override to change the way Auth works
		'Auth' => [
				'loginAction' => [
						'plugin' => 'CakeDC/Users',
						'controller' => 'Users',
						'action' => 'login',
						'prefix' => null
				],
				'authenticate' => [
						'all' => [
								'finder' => 'auth',
						],
						'CakeDC/Users.ApiKey',
						'CakeDC/Users.RememberMe',
						'Form',
				],
				'authorize' => [
						'CakeDC/Users.Superuser',
						'CakeDC/Users.SimpleRbac',
				],
		],
		'OAuth' => [
				'path' => ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialLogin', 'prefix' => null],
				'providers' => [
						'facebook' => [
								'className' => 'League\OAuth2\Client\Provider\Facebook',
								'options' => [
										'graphApiVersion' => 'v2.5',
										'redirectUri' => Router::fullBaseUrl() . '/auth/facebook',
								]
						],
						'twitter' => [
								'options' => [
										'redirectUri' => Router::fullBaseUrl() . '/auth/twitter',
								]
						],
						'linkedIn' => [
								'className' => 'League\OAuth2\Client\Provider\LinkedIn',
								'options' => [
										'redirectUri' => Router::fullBaseUrl() . '/auth/linkedIn',
								]
						],
						'instagram' => [
								'className' => 'League\OAuth2\Client\Provider\Instagram',
								'options' => [
										'redirectUri' => Router::fullBaseUrl() . '/auth/instagram',
								]
						],
						'google' => [
								'className' => 'League\OAuth2\Client\Provider\Google',
								'options' => [
										'userFields' => ['url', 'aboutMe'],
										'redirectUri' => Router::fullBaseUrl() . '/auth/google',
								]
						],
				],
		]
];
return $config;

permissions.php

<?php 

return ['Users.SimpleRbac.permissions' => [
		[
			'role' => '*',
			'plugin' => 'CakeDC/Users',
			'controller' => '*',
			'action' => '*',
		],
		[
			'role' => 'user',
			'plugin' => 'CakeDC/Users',
			'controller' => 'Users',
			'action' => ['edit', 'view','profile','logout'],
			'allowed' => true,
		],
		[
			'role' => 'user',
			'plugin' => 'CakeDC/Users',
			'controller' => 'Users',
			'action' => '*',
			'allowed' => false,
		],

......

Everytime when I come back from facebook it will show me not authorized to access that location.

How can I debug this?

**Comment by steinkel** [comment]
check the role of the user created, possibly you have to configure the rules in permissions.php to allow access to the specific controller. You could add a permission rule to allow "all" to role = '*' for testing, and then isolate the specific permission you need to add.

**Comment by tgoeminne** [comment]
There is not any account being created.

**Comment by tgoeminne** [comment]
When I follow that tutorial and change the users.php file to

<?php

return [
		'Users.Social.login' => true,
		'OAuth.providers.facebook.options.clientId' => 'xxxxxxxxxxxxxxxxxxx',
		'OAuth.providers.facebook.options.clientSecret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
		//etc
];

?>


Fatal error: Cannot redeclare class CakeDC\Users\Controller\UsersController in vendor/cakedc/users/src/Controller/UsersController.php on line 32

**Comment by steinkel** [comment]
That's weird, could you check with a blank project, follow the tutorial for facebook login and then integrate with your project, looks like you have some issue with your vendors. Sorry I'm not very specific, I'm trying to guess based on your shared code...

**Comment by rochamarcelo** [comment]
Are you using 'dev-master' branch? If so, have you checked the error.log file?

**Comment by tgoeminne** [comment]
Yes, I am using dev-master. everything works except social login does not work. When follow tutorial I get the Error: CakeDC/Users.UsersController could not be found. when clicking facebook button

**Comment by tgoeminne** [comment]
Configure::write('Users.config', ['users']);
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);

When I change this to:

Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
Configure::write('Users.config', ['users']);

Then I no longer see the error for missing controller. Is that normal?

**Comment by tgoeminne** [comment]
Maybe the users config is not being loaded correctly? I just copy pasted it from cakedc folder to config folder.

**Comment by tgoeminne** [comment]
If you place the users.php in src/config should it not overwrite the config file in vendor/cakedc folder?

It appears that this is not happening.

**Comment by rochamarcelo** [comment]
It only use your users.php when you add Configure::write('Users.config', ['users']);

In my users.php I added the facebook info:
 `'facebook' => [
                'className' => 'League\OAuth2\Client\Provider\Facebook',
                'options' => [
                    'graphApiVersion' => 'v2.8',
                    'redirectUri' => Router::fullBaseUrl() . '/auth/facebook',
                    'clientId' => '#####################',
                    'clientSecret' => '########################',
                ]
            ],`

**Comment by tgoeminne** [comment]
Hi,

I tried that too. I don't know previous versions always worked just fine. Everything works apart from the social login. When checking in chrome network I see there is facebook,

then the following:

Request URL:http://www.mywebsite.com/auth/facebook
Request Method:GET
Status Code: 302 Moved Temporarily
Remote Address:111.111.111.111:80 (my ip address)

Is this a problem or normal?

**Comment by tgoeminne** [comment]
Well I have just found what the problem is. The configuration file created in config folder with the name users.php does not load. So instead I have to declare the settings in regular bootstrap.


I had added this line to bootstrap:

Configure::write('Users.config', ['users']);

But the file users.php with this content:

<?php
return [
		'OAuth' => [
				'path' => ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialLogin', 'prefix' => false],
				'providers' => [
						'facebook' => [
								'className' => 'League\OAuth2\Client\Provider\Facebook',
								'options' => [
										'graphApiVersion' => 'v2.8',
										'redirectUri' => 'xxxxxxxxxxxxxxxxx',
										'clientId' => 'xxxxxxxxxxxxxxxxxxxxxxxxx',
										'clientSecret' => 'xxxxxxxxxxxxxxxxxxxxxxxx'
								]
						],
						'google' => [
								'className' => 'League\OAuth2\Client\Provider\Google',
								'options' => [
										'userFields' => ['url', 'aboutMe'],
										'redirectUri' => Router::fullBaseUrl() . '/auth/google',
										'clientId' => 'xxxxxxxxxxxxxxxxxxx',
										'clientSecret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
								]
						],
				],
		]
];
?>

This does not work, instead put in bootstrap directly, then it will work:

Configure::write('OAuth.providers.facebook.options.redirectUri','xxxxxxx');
Configure::write('OAuth.providers.facebook.options.graphApiVersion','v2.8');
Configure::write('OAuth.providers.facebook.options.clientId', 'xxxxxxxxxxxxxx');
Configure::write('OAuth.providers.facebook.options.clientSecret','xxxxxxxxxxxxx');


So the problem is with the configuration file that is not working as intended.....

**Comment by steinkel** [comment]
@tgoeminne did you `return` the configuration array in your users.php file, looks like this is the root issue your config is not being applied...

**Comment by tgoeminne** [comment]
I copied the contents of the file config/users.php from plugin and made the file in my own config folder users.php. But that did not work as I expected...

**Comment by steinkel** [comment]
ok, this line

`Configure::write('Users.config', ['users']);`

Is **before** or after the Plugin::load() ?

**Comment by steinkel** [comment]
Closing this one, please let me know if you have any other issues related to the setup. Thanks,
