### ISSUE TITLE
Error: CakeDC/Users.AccountsController could not be found.

### ISSUE THREAD

**Issue by response2nik** [CakeDC/users#468]
Hi, 
On clicking on list accounts on add ctp getting error
Error: CakeDC/Users.AccountsController could not be found.
Error: Create the class AccountsController below in file: /var/www/nikhil3/vendor/cakedc/users/src/Controller/AccountsController.php

and where I can create separate groups and set different permissions for controllers for separate groups.

Thanks in advance

**Comment by steinkel** [comment]
This link was already removed in the latest release, please upgrade to 4.0.0

You can manage groups and permissions via configuration https://github.com/CakeDC/users/blob/master/Docs/Documentation/SimpleRbacAuthorize.md

Thanks!
