### ISSUE TITLE
unable to migrate mongo db

### ISSUE THREAD

**Issue by response2nik** [CakeDC/users#471]
plz help on this,

Exception: Could not infer database type from driver in [/var/www/nikhil3/vendor/cakephp/migrations/src/ConfigurationTrait.php, line 151]
2016-12-26 05:15:33 Error: [InvalidArgumentException] Could not infer database type from driver
Stack Trace:
#0 /var/www/nikhil3/vendor/cakephp/migrations/src/ConfigurationTrait.php(83): Migrations\Command\Migrate->getAdapterName('Hayko\\Mongodb\\D...')
#1 /var/www/nikhil3/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php(91): Migrations\Command\Migrate->getConfig()
#2 /var/www/nikhil3/vendor/cakephp/migrations/src/ConfigurationTrait.php(206): Phinx\Console\Command\AbstractCommand->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/nikhil3/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(72): Migrations\Command\Migrate->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/nikhil3/vendor/cakephp/migrations/src/ConfigurationTrait.php(165): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/nikhil3/vendor/cakephp/migrations/src/Command/Migrate.php(58): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/nikhil3/vendor/symfony/console/Command/Command.php(255): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/nikhil3/vendor/symfony/console/Application.php(830): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nikhil3/vendor/symfony/console/Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nikhil3/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nikhil3/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(98): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#11 [internal function]: Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#12 /var/www/nikhil3/vendor/cakephp/cakephp/src/Console/Shell.php(466): call_user_func_array(Array, Array)
#13 /var/www/nikhil3/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(130): Cake\Console\Shell->runCommand(Array, true, Array)
#14 /var/www/nikhil3/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(227): Migrations\Shell\MigrationsShell->runCommand(Array, true, Array)
#15 /var/www/nikhil3/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#16 /var/www/nikhil3/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#17 /var/www/nikhil3/bin/cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#18 {main}

thanksin advance.

**Comment by steinkel** [comment]
I don't see any reference to the Users plugin in the stack trace, is this issue related with the Plugin at all?


Thanks,
