### ISSUE TITLE
How change displayfield of users model?

### ISSUE THREAD

**Issue by Josecanalla** [CakeDC/users#472]
Hello, I want to change the displayfield of the users model because it is giving me the ID. In the UsersTable file in the plugin folder there is the username, but it isn't working. I do not change anything of that in the src folder of my app.

My UsersTable.php:

```
public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('users');
        $this->displayField('username');
        $this->primaryKey('id');
        $this->addBehavior('Timestamp');
        $this->addBehavior('CakeDC/Users.Register');
        $this->addBehavior('CakeDC/Users.Password');
        $this->addBehavior('CakeDC/Users.Social');
        $this->hasMany('SocialAccounts', [
            'foreignKey' => 'user_id',
            'className' => 'CakeDC/Users.SocialAccounts'
        ]);
    }
```

**Comment by steinkel** [comment]
Did you configure the plugin to use your Users table? 
Please check  https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md#extending-the-model-tableentity

**Comment by Josecanalla** [comment]
Yes, I do the four things. So after that, how can I change the displayfield of the model?

**Comment by steinkel** [comment]
You can tweak the displayField property of the table class in the initialize method.

**Comment by Josecanalla** [comment]
I do it but it has no effect. 
My UsersTable.php code:

```
public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('users');
        **$this->displayField('username');**
        $this->primaryKey('id');
        $this->addBehavior('Timestamp');
        $this->addBehavior('CakeDC/Users.Register');
        $this->addBehavior('CakeDC/Users.Password');
        ....
```

My MyUsersTable.php code:

```
class MyUsersTable extends UsersTable
{
    use SoftDeleteTrait;
}
```

What is my mistake? Thanks!

**Comment by steinkel** [comment]
Please debug the table object you are using to ensure it's a MyUsers table instance, possibly you are using either an auto-table or the plugin's table instead of yours.

**Comment by Josecanalla** [comment]
This is my mistake. I had a relation between "Users" and other table objects. The relation must have between "MyUsers" and other table objects. I change the relation and now it works! Thanks!
