### ISSUE TITLE
Missing CSRF token cookie

### ISSUE THREAD

**Issue by gnilebein** [CakeDC/users#473]
Hello,

i have problem with the installation of cakeDC. I tried it with a completely new cake installation. I used this howto: https://github.com/CakeDC/users/blob/master/Docs/Documentation/Installation.md

On apache (2.4, PHP 5.5.9) i can't register a new user. I got the followin error message:

`Missing CSRF token cookie`

The same problem occours when i try to login with a superuser i created with command "bin/cake users addSuperuser".

Maybe you can help me to fix this issue?

**Comment by steinkel** [comment]
please could you send me a zip file with the blank project to take a look? with the tests I did I'm able to register new users...

thanks

**Comment by gnilebein** [comment]
Okay, i have two files:

cakephp.tar.gz: [https://share.gnilebein.de/uploads/cakephp.tar.gz](https://share.gnilebein.de/uploads/cakephp.tar.gz) (2,2 MB)
This inclues the cake installation +  dbdump (sqldump.sql)

Complete Virtualbox Image: [https://share.gnilebein.de/uploads/UBUNTU.ova](https://share.gnilebein.de/uploads/UBUNTU.ova) 1,1GB
Includes the complete test installation. RootPW is 12341234, mysqlpw is 1234, DHCP Network

**Comment by steinkel** [comment]
Thank you @gnilebein I'll take a look ASAP (possibly end of the week). If possible please workaround it disabling csrf in this specific action meanwhile...

**Comment by gnilebein** [comment]
Thank you very much.

**Comment by steinkel** [comment]
@gnilebein downloading the .targ.gz file, restoring the dump and using bin/cake server to run the app works fine, so looks like a problem related with the webserver configuration, I'm downloading the .ova and taking a look soon...

**Comment by steinkel** [comment]
@gnilebein did a quick check on the .ova too and you are missing the default apache configuration as required here https://book.cakephp.org/3.0/es/installation.html#apache. 
The important piece is to ensure your document root points to your webroot folder

    DocumentRoot /var/www/html/webroot

Also you should enable `AllowOverride All` for this folder too. This bug looks not related to the plugin itself but to an incorrect apache2+CakePHP configuration.

Thanks,

**Comment by gnilebein** [comment]
Oh my god. Thanks for pointing this out. This is really embarrassing. Sorry for that.

Now it works.
