### ISSUE TITLE
Nginx Ready?

### ISSUE THREAD

**Issue by gnilebein** [CakeDC/users#474]
Hello,

i tried to use CakeDC user plugin with newest cakePHP Version with Nginx. I can install the Plugin, i cn create a user, but i can not login with created user or any superadmin user.

On every login i get the error message "You are not authorized to access that location.".

Thanks for help :-)

Best regards,
Patrick

**Comment by ajibarra** [comment]
Hi @gnilebein, please check this https://github.com/CakeDC/users/blob/master/Docs/Documentation/SimpleRbacAuthorize.md to configure your permissions and authorize users to access your actions.

**Comment by gnilebein** [comment]
I thought th plugins should work out of the box... 

> SimpleRbacAuthorize is configured by default

But nothing happen under nginx. Is there somebody who use this plugins with nginx?

**Comment by gnilebein** [comment]
It was my fault... It is working with Nginx. My docroot does not point to the webroot subfolder.
