### ISSUE TITLE
bug in the UsersTable.php line 49

### ISSUE THREAD

**Issue by steven199136** [CakeDC/users#480]
new version of plugin has serious bug in the UsersTable file line 49. -  $this->table('users');
For now, as you can see, in the initialize method, it directly refer the table named users which is default table for the Users Plugin.

From this issue, when you try to extend the users table by subclassing, it occurs error - Can't find the table "{app}.users".

I think this is serious issue and it should be substitute with the name from the Configure::read('Users.table').

**Comment by steinkel** [comment]
Hi @steven199136 this is not a bug, it's the default table configuration for the UsersTable provided with the plugin.

To correctly extend the model you need to follow instructions detailed in the docs here https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md#extending-the-model-tableentity

Please note the `Configure::read('Users.table')` configuration refers to the Table Class you want to use, not to the database table. The database table can be configured later in the Table class using the `table` method giving you the flexibility to use your own table or reuse the users database table.

Thanks,
