### ISSUE TITLE
Implement a "Link your account to a social account"

### ISSUE THREAD

**Issue by rochamarcelo** [CakeDC/users#491]
Hi guys,

I think it would be awesome if we implement a "Link your account to a social (facebook, google, twitter) account" button, what do you think about it?

**Comment by nkoiumi** [comment]
Hi, 
Is this feature going to be implemented?

**Comment by ajibarra** [comment]
Hi @rochamarcelo this is an interesting feature for the plugin, we will look to include this into a future release. Would you be interested in contributing with this feature?

**Comment by rochamarcelo** [comment]
Hi. actually I had started with something, I will send you the code

**Comment by rochamarcelo** [comment]
@ajibarra please take a look at this repo https://github.com/rochamarcelo/users/commit/7b9915bde69241b1e071c13fd9959ad059e56a69 

That's what I have done. What do you think about it?

**Comment by steinkel** [comment]
thank you!
