### ISSUE TITLE
plugin not working in plugins directory

### ISSUE THREAD

**Issue by surjit** [CakeDC/users#492]
Hi
I moved plugin from vendor directory to plugins directory.
all works good on windows, but when i moved all to Linux it's not loading CakeDC/Users plugin

I tried all installing by composer etc
still not working, it seems bug in cakephp plugin loader with namespace in plugins directory

**Comment by digitalfotografen** [comment]
Moving the plugin from vendor to plugins requires some editing of composer.json (the one in the main app, not the plugin) to load it. The autoload block should look something like this:

    "autoload": {
        "psr-4": {
            "App\\": "src",
            "CakeDC\\Users\\": "./plugins/CakeDC/Users/src",
            "CakeDC\\Users\\Test\\": "./plugins/CakeDC/Users/tests"
        }
    },

Then run composer to update the autoload. I have been using composer install, but maybe composer dumpautoload is sufficient.

**Comment by steinkel** [comment]
@surjit you don't need to move it to plugins, just fork the plugin, modify and then use composer repository configuration to override the plugin with your own fork. Don't forget to contribute back some of the new cool features :+1:
