### ISSUE TITLE
When will support cakephp 3.4

### ISSUE THREAD

**Issue by infokani** [CakeDC/users#495]

**Comment by steinkel** [comment]
Hi, we are fixing a couple tests related with https://github.com/cakephp/cakephp/issues/10208, please expect this to happen soon, thanks

**Comment by steinkel** [comment]
We have a working version compatible with 3.4 in the branch feature/cake34

**Comment by steinkel** [comment]
Closed per #518

**Comment by steinkel** [comment]
check version 5.0.0 just released
