### ISSUE TITLE
rare DB Problem

### ISSUE THREAD

**Issue by Drizzt-IT** [CakeDC/users#496]
Hi,
I've got a rare Problem which I can't get our thumb on.
The Error is that no token is set in the DB for the User after the registration.
The Person is always the same. I tried with a couple of people, but we can't replicate the error.

Any ideas?

Note:
im rather new to cakephp, and I made a complete override of the controller

**Comment by DrizztDarnok** [comment]
I found the problem.
The case:
1. somebody makes a registration,
2. -> does not! activate by email link,
3. resets the password which deletes the token -> why??
In PasswordBehavior.php Line: 129
= Cannot activate any more....

**Comment by groovenectar** [comment]
It does not activate by email link... did you set up the email server information in `config/app.php`? The activation may be an important step there

If we aren't able to reproduce this issue, we might have to close it

**Comment by rochamarcelo** [comment]
Hi,

The token is used for register confirmation and password change confirmation, so you need to ensure that only active users are able to request password reset. We have a configuration for it `Configure::write('Users.Registration.ensureActive', true);`

Closing it.
