### ISSUE TITLE
UserShell::addSuperuser method should be consistent with addUser 

### ISSUE THREAD

**Issue by digitalfotografen** [CakeDC/users#497]
The UserShell::addUser method has options for setting username, email... To make it consistent and logical, add same options to the UserShell::addSuperuser method.

The difference between these methods when all options are used will then be the superuser flag. The default behaviour will still be random password.

**Comment by digitalfotografen** [comment]
There is now a patch for this request.

**Comment by steinkel** [comment]
Closed per #498
