### ISSUE TITLE
JSON view is not allowed by RBAC on any controller with "user" in the name

### ISSUE THREAD

**Issue by alexlambson** [CakeDC/users#503]
I am getting kicked to my Auth::config('loginRedirect') whenever I try to add '.json' to the end of my URL if the controller has 'user' in it. 

I can give full access to my code or any individual files upon request. I am using a super admin and still getting redirected. 

Example: 
root/series.json => works
root/events/index/2.json => works
root/MyUsers/index.json => redirects to loginRedirect
root/UsersEvents/checkin.json => redirects

My Permission:
```
'Users.SimpleRbac.permissions' => [
        [
            'role' => 'admin',
            'controller' => '*',
            'action' => '*'
        ]
]
```

**Comment by chav170** [comment]
Add:
  'extensión' => ['json']

To the permission

**Comment by alexlambson** [comment]
Holy crap I'm retarded
