### ISSUE TITLE
CakePHP not picking up 'Authorize' configuration from users.php

### ISSUE THREAD

**Issue by akkaweb** [CakeDC/users#507]
I am using this plugin in my application, but I am having issues with permission. After debugging it seems CakePHP sees the `authorize` entry from the users.php file, but it does not act on it. See debug image below

![debug](https://cloud.githubusercontent.com/assets/428229/23379591/82836806-fd05-11e6-93d2-464685d459fb.png)

I have followed all the instructions on how to configure this, several times, but I don't see where the issue is. In essence, the file ` users/src/Auth/SimpleRbacAuthorize.php` is not being initialized.

This is how I am configuring it all:

AppController.php

    $this->loadComponent('CakeDC/Users.UsersAuth');

config/users.php

    return [
        'Auth' => [
            'authError' => 'Did you really think you are allowed to see that?',
            'authorize' => [
                'CakeDC/Users.Superuser',
                'CakeDC/Users.SimpleRbac',
            ]
        ]
    ];

    
config/permissions.php

```
return [
    'Users.SimpleRbac.permissions' => [
        [
            'role' => '*',
            'controller' => 'Pages',
            'action' => ['display'],
            'allowed' => true
        ], [
            'role' => '*',
            'controller' => 'Taxes',
            'action' => ['*'],
            'allowed' => true
        ], [
            'role' => '*',
            'prefix' => 'v1',
            'controller' => '*',
            'action' => '*',
            'allowed' => true
        ]
    ]
];
```

**Comment by steinkel** [comment]
Please check https://ide.c9.io/steinkel/users-so-42523209 I've added a similar configuration for it.

IMPORTANT note about authorize, keep in mind CakePHP Configure will **merge** values by default, if you want to override the whole content of authorize in Auth, I would suggest adding this after plugin load, like this

    $this->loadComponent('CakeDC/Users.UsersAuth');
    $this->Auth->config('authorize', [...]);

**Comment by akkaweb** [comment]
Thank you for looking into this. I have done the following without any effects.

    $this->loadComponent('CakeDC/Users.UsersAuth');
    $this->Auth->config('authorize', [
            'CakeDC/Users.Superuser',
            'CakeDC/Users.SimpleRbac',
    ]);

If I am not logged in, everything gets redirected to `/login`, even when I explicitly allow anyone to access the homepage by adding the following to my `permissions.php` file. I still get redirected to `/login`

    [
            'role' => '*',
            'controller' => 'Pages',
            'action' => ['display', 'home'],
            'allowed' => true
    ]

I have even gone as far to "break" `src/Auth/SimpleRbacAuthorize.php` file without any effects at all. Because of if I concluded that CakePHP is not loading CakeDC's Simple RBAC Authorize file at all. I can't figure out why is that happening.

**Comment by steinkel** [comment]
Hi, I think you are confused about 2 concepts:
Page is Allowed by Auth, these pages do NOT require a user logged in to access the content.
Page is allowed by SimpleRbac rule, you need to be logged in, then for ANY role, you get access to the page itself.

If you wish to allow access to users NOT logged in into your application, use
    $this->Auth->allow(['action']);
in beforeFilter callback of your controller.

Thanks,

**Comment by akkaweb** [comment]
Yes. I think that is where the confusion was. I mistakenly thought SimpleRbacAuthorize.php would overall allow me not to use `$this->Auth->allow(['action'])`. I failed to realized that by design Auth only works with [Auth]enticated users. Thanks again!
