### ISSUE TITLE
Removed username field from Table and Used email for login and still forget password is not working

### ISSUE THREAD

**Issue by Amit619** [CakeDC/users#511]
I have used this line in Bootstrap.php
Configure::write('Auth.authenticate.Form.fields.username', 'email');
But forget password still need username i dont know why. It shows the error Token cannot be validated, And when i insert the username field then it send the mail for password reset

**Comment by Amit619** [comment]
I have fixed this by editing PasswordBehviour.php code from
return $this->_table->findByUsernameOrEmail($reference, $reference)->first();
to
return $this->_table->findBy=Email($reference, $reference)->first();

Is this supposed to happen or correct me if i am wrong

**Comment by Tomicapo** [comment]
I'm having the same problem. I don't think this is an adequate solution. Any other thoughts someone?

**Comment by rochamarcelo** [comment]
closing due to activity.
