### ISSUE TITLE
Tests fail when combining test suite with application

### ISSUE THREAD

**Issue by lorenzomaieru** [CakeDC/users#512]
I'm sorry if this is the wrong place to ask this, but I can't figure out if I've managed to install the plugin completely wrong or if I actually stumbled upon a bug here.

As per CakePHP docs [here](https://book.cakephp.org/3.0/en/development/testing.html#combining-test-suites-for-plugins), I attempted combining this plugin's tests into a clean cake app. After adding the <testsuite>, several tests from this plugin seem to be failing.
More specifically, I seem to be getting a lot of these:

`BadMethodCallException: Cannot reconfigure existing key "default"`

Now, I don't know if I'm doing something wrong here as I'm very new to Unit Testing, and I might very well be approaching this whole thing from the wrong angle. If so, please let me know.
But if that isn't the case, then these errors seem to be caused by calling `Email::config` without first calling `Email::drop`,
in [SocialAccountsControllerTest:53](https://github.com/CakeDC/users/blob/5253234119baf9c6da843b881bec711f331c65ff/tests/TestCase/Controller/SocialAccountsControllerTest.php#L53-L56) and [BaseTraitTest:67](https://github.com/CakeDC/users/blob/5253234119baf9c6da843b881bec711f331c65ff/tests/TestCase/Controller/Traits/BaseTraitTest.php#L67-L70)

I tried using `Email::drop` before these lines and that seems to fix the tests, if there even was an issue to begin with. But I'm more inclined to think that I've done something wrong while setting up the plugin.

**Comment by steinkel** [comment]
The problem here could be, the plugin itself is using a fake application configuration to be able to test the plugin alone. Please contribute the changes to the BaseTraitTest and we'll merge them to make your testing easier.

Thank you and :+1: for testing your app this way

**Comment by lorenzomaieru** [comment]
Great, thanks. Just submitted the pull request.
