### ISSUE TITLE
Role data not saved in the database

### ISSUE THREAD

**Issue by chrmina** [CakeDC/users#513]
CakePHP v. 3.4.3
CakeDC Users Plugin v. 4.1.2

I modified the `add.ctp` form to be able to set a specific role to a new user but the role data is not saved in the database. I checked the post data and confirmed that `data['role']` is passed correctly. Here is the `Template\Plugin\CakeDC\Users\Users\add.ctp` code:
```php
<?php
echo $this->Form->create(${$tableAlias});
echo $this->Form->input('username', ['label' => __d('CakeDC/Users', 'Username')]);
echo $this->Form->input('email', ['label' => __d('CakeDC/Users', 'Email')]);
echo $this->Form->input('password', ['label' => __d('CakeDC/Users', 'Password')]);
echo $this->Form->input('first_name', ['label' => __d('CakeDC/Users', 'First name')]);
echo $this->Form->input('last_name', ['label' => __d('CakeDC/Users', 'Last name')]);
echo $this->Form->input('role', [
    'type' => 'select',
    'label' =>  __d('CakeDC/Users', 'Role'),
    'options' => ['u' => 'user', 'e' => 'editor', 'a' => 'admin'],
    'default' => 'u'
]);
echo $this->Form->input('active', ['type' => 'checkbox', 'label' => __d('CakeDC/Users', 'Active')]);
?>
<div class="form-group">
  <?= $this->Form->button(__d('CakeDC/Users', 'Submit'), ['class' => 'btn btn-default']) ?>
</div>
<?= $this->Form->end() ?>
</div>

```
Any clues why this is happening? Possible bug?

Thank you!

**Comment by steinkel** [comment]
role is filtered by the accessible array here https://github.com/CakeDC/users/blob/master/src/Model/Entity/User.php#L35 

The reason is: we don't allow users to override their own role by default. Note you can keep you current form as it is, you only need to assign the role in the controller after the newEntity/pathEntity like

    $entity->role = $this->request->data('role');

**Comment by chrmina** [comment]
Thank you Jorge, worked like a charm!

I have set rules so that only an "admin" can add new accounts. Also disallowed "users" and "editors" from editing their roles by checking if the user is an "admin" in the edit form.

This is ```edit.ctp``` for reference:
```php
<h1 class="page-header">Edit User Form</h1>
<div class="form">
  <?php
    echo $this->Form->create($Users);
    echo $this->Form->input('username');
    echo $this->Form->input('email');
    echo $this->Form->input('first_name');
    echo $this->Form->input('last_name');
    if ($this->request->session()->read('Auth.User.role') == 'admin') {
      echo $this->Form->input('role', [
        'type' => 'select',
        'label' =>  __d('CakeDC/Users', 'Role'),
        'options' => ['user' => 'user', 'editor' => 'editor', 'admin' => 'admin'],
      ]);
      echo $this->Form->input('active');
    }
  ?>
  <div class="form-group">
    <?= $this->Form->button(__d('CakeDC/Users', 'Submit'), ['class' => 'btn btn-default']) ?>
  </div>
  <?= $this->Form->end() ?>
</div>
```

**Comment by lucasthibau** [comment]
@steinkel why not add this option in the next version? Is so simple, but, if I want to keep the plugin updated, I will always have to overwrite it after running a composer update.

**Comment by steinkel** [comment]
as it's a secure default, we are going to keep it in the plugin for now. But you can easily override the users controller in your application, you should never change contents in your vendors or it's going to be a pain to maintain later... check how to do this here > https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md
