### ISSUE TITLE
Overriding template not works in remote server

### ISSUE THREAD

**Issue by Josecanalla** [CakeDC/users#515]
Hello, I override several templates of the plugin and it works OK on localhost. I put the template files in src/Plugin/cakedc/users/Users/login.ctp (for example).

But when upload the app to a remote server, not works. I see the original template. 

What is my mistake? Thanks!

**Comment by chrmina** [comment]
To override the original plugin templates you need to put your templates in `src/Template/Plugin/CakeDC/Users/Users/`.

I assume you use the latest versions of CakePHP and the Users plugin...

**Comment by steinkel** [comment]
Check the casing of the files if you are using windows for development and linux as the target environment. The correct file should be `src/Plugin/CakeDC/Users/Users/login.ctp`

**Comment by Josecanalla** [comment]
Yes, may be a case sensitive problem. The correct path is src/Template/Plugin/CakeDC/Users/Users/ as @chrmina says. Thanks!

Previously, I put in lower case because in vendor folder the folders of the plugin are in lower case.
