### ISSUE TITLE
default_role not changing

### ISSUE THREAD

**Issue by infokani** [CakeDC/users#520]
I added following line to config/users.php but registered user role empty
```
...
 'Auth' => [
        'loginAction' => [
            'plugin' => 'CakeDC/Users',
            'controller' => 'Users',
            'action' => 'login',
            'prefix' => false
        ],
        'authenticate' => [
            'all' => [
                'finder' => 'auth',
            ],
            'CakeDC/Users.ApiKey',
            'CakeDC/Users.RememberMe',
            'Form',
        ],
        'authorize' => [
            'CakeDC/Users.Superuser',
            'CakeDC/Users.SimpleRbac'=>['default_role' => 'members'], // *** modified line ***
        ],
    ],
...
```

**Comment by steinkel** [comment]
Note this configuration para will not affect the way the default role is assigned. The default role is currently assigned by the database as default column value.

It makes sense to add a configuration param to specify the default role.

**Comment by steinkel** [comment]
We have a new configuration param `Users.Registration.defaultRole` added in https://github.com/CakeDC/users/releases/tag/4.2.0
