### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by Satal** [CakeDC/users#524]
I believe the issue where you're unable to install for the latest version of CakePHP is happening again. I managed to get this installed following the instructions in #289 (pretending to be version 3.3.9) but prior to that, I was getting the following error.

```
# composer require cakedc/users
Using version ^4.2 for cakedc/users
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakedc/users 4.2.1 requires cakephp/cakephp >=3.2.9 <3.4.0 -> satisfiable by cakephp/cakephp[3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.9, 3.3.0, 3.3.0-RC1, 3.3.0-beta, 3.3.0-beta2, 3.3.0-beta3, 3.3.1, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9] but these conflict with your requirements or minimum-stability.
    - cakedc/users 4.2.0 requires cakephp/cakephp >=3.2.9 <3.4.0 -> satisfiable by cakephp/cakephp[3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.9, 3.3.0, 3.3.0-RC1, 3.3.0-beta, 3.3.0-beta2, 3.3.0-beta3, 3.3.1, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9] but these conflict with your requirements or minimum-stability.
    - Installation request for cakedc/users ^4.2 -> satisfiable by cakedc/users[4.2.0, 4.2.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by davidxwheatley** [comment]
Experiencing same issue:

composer require cakedc/users
Using version ^4.2 for cakedc/users
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakedc/users 4.2.1 requires cakephp/cakephp >=3.2.9 <3.4.0 -> satisfiable by cakephp/cakephp[3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.9, 3.3.0, 3.3.0-RC1, 3.3.0-beta, 3.3.0-beta2, 3.3.0-beta3, 3.3.1, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9] but these conflict with your requirements or minimum-stability.
    - cakedc/users 4.2.0 requires cakephp/cakephp >=3.2.9 <3.4.0 -> satisfiable by cakephp/cakephp[3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.9, 3.3.0, 3.3.0-RC1, 3.3.0-beta, 3.3.0-beta2, 3.3.0-beta3, 3.3.1, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9] but these conflict with your requirements or minimum-stability.
    - Installation request for cakedc/users ^4.2 -> satisfiable by cakedc/users[4.2.0, 4.2.1].


Installation failed, reverting ./composer.json to its original content.

**Comment by steinkel** [comment]
what version of CakePHP are you trying to install?

please keep in mind we have a 3.4 compatible version currently in develop branch, we will be pushing a release soon

**Comment by davidxwheatley** [comment]
Version 3.4.* .... Understand my mistake .... Appreciate your efforts
