### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by hervethouzard** [CakeDC/users#526]
Hello,

I want to use Google OAuth to connect to my website and I have used the instructions on this page:
https://www.cakedc.com/jorge_gonzalez/2016/10/11/login-with-google-oauth2-in-cakephp-using-cakedc-users-plugin

But each time I try to connect with Google account, I have this error message:
ERR_TOO_MANY_REDIRECTS

What am I doing wrong?
I have already verified several times my code, it is strictly identical to the one you can find on the cited page.

There's nothing in log/debug.log and error.log
In the Google console I have configured http://mysite.com/auth/google as a redirect page.

Bye

**Comment by steinkel** [comment]
The problem was related to missing permission rules blocking access to the home page redirected after Oauth login, please ensure you allow it in permissions.php

**Comment by gerrymcdonnell** [comment]
how do you fix this error, ive the same problem.  i cant visit the site localhost/mysite/pages/home ?

**Comment by hervethouzard** [comment]
As stated n'y @steinkel the file config/permissions.php was missing

**Comment by gerrymcdonnell** [comment]
thanks that worked but why is there 2 "permissions.php" now then? Same goes for users.php

One in the 
C:\xampp\htdocs\cakeuserstest/config/

and one in;
C:\xampp\htdocs\cakeuserstest\vendor\cakedc\users\config
