### ISSUE TITLE
Sign In with google not working Showing "You are not authorized to access that location."

### ISSUE THREAD

**Issue by dkheterpal** [CakeDC/users#531]
Hello everyone,

My name is Deepak and I am trying to integrate CakeDC Plugin from https://github.com/CakeDC/users into my local computer.

When I click on sign in with google button, it goes to a url somehting like:

https://accounts.google.com/o/oauth2/auth?state=6d0c71c86b50648ad8aa01f17562e974&scope=email%20openid%20profile&response_type=code&approval_prompt=auto&redirect_uri=http%3A%2F%2Flocalhost%2Fscreens.cinemesalbeniz.cat%2Fauth%2Fgoogle&client_id=385973950189-d3h8s3ta4m7lesvd7to8g17mgu5ae64l.apps.googleusercontent.com&authuser=-1

And returns back, with a message "You are not authorized to access that location."

I have all the default settings that was provided by github and in config/users.php the client id and secret have been changed to the correct values. The vendor/cakedc/users/config/users.php have the urls set to Router::fullBaseUrl() . '/screens.cinemesalbeniz.cat/auth/google' where my set is set up.

I would really appreciate if anyone can provide any guidance.

Thanks in advance.

Regards,
Deepak

**Comment by dkheterpal** [comment]
Hello everyone,

Can anyone please provide me any suggestions here.

Thank you

**Comment by steinkel** [comment]
Hi Deepak, could you provide some environment to test your issue. Check these example environments for insight on possible issues you could have regarding configuration

https://ide.c9.io/steinkel/users-example
https://ide.c9.io/steinkel/users-example-custom-table

**Comment by cercos** [comment]
I am getting the same thing.  Everything is default.  There isn't a route for "/auth/google" but I see one for "/auth/twitter"  .. I tried setting a route for /auth/google to point at the socialLogin() method and set permissions, the authorization message goes away but Im not logged in.  My google account does have my site listed after I click the allow button, so it's something to do with the redirectUri

**Comment by ajibarra** [comment]
@cercos @dkheterpal have you tried with the latest release?. You should not need to add any route because they are automatically loaded if required. We need to load twitter routing because it uses another library (oauth1). 

Please let me know if we can close this issue.

**Comment by cercos** [comment]
Im fully updated and still receiving the error, I have ignored it temporally . Does this require SSL certificates to be setup?

**Comment by steinkel** [comment]
@cercos please do composer update and test again... CakeDC/Auth was updated. Thanks,

**Comment by cercos** [comment]
Ran composer update, the CakeDC/Auth updated to 2.0 but the 'You are not authorized' error still pops up.  Am I missing a permission possibly?

**Comment by rogerpro** [comment]
Hi @cercos , have you installed this package?

    composer require robthree/twofactorauth:"^1.5.2"

**Comment by cercos** [comment]
@rogerpro Yes.  I installed every package mentioned in the docs just to be sure I wasn't missing something.   I even went back and did a fresh install of everything just to be sure, left everything default and entered my Google API keys but still get the 'You are not authorized error'

**Comment by rogerpro** [comment]
Hi @cercos and @dkheterpal. I found a posible solution.

In addition to have a Oauth2 key and secret, it's mandatory to have Google+ API enabled on Google APIs. You must already have a Google API project from where you copied Oauth2 key and secret.

In this project, enable a Google+ API. You can do it directly going to https://console.developers.google.com/apis/api/plus.googleapis.com/overview and clicking to ENABLE (pay attention that you are on the right project and switch with dropdown menu if needed).

I hope that this may help. I would appreciate feedback from you. Thank you.

**Comment by cercos** [comment]
@rogerpro It works! Spent so much time messing around on settings and permissions trying all kinds of things. Sometimes the simplest oversight causes the most confusion. Thank you for helping out.
