### ISSUE TITLE
Call to undefined method CakeDC\Users\Auth\SocialAuthenticate::_isProviderEnable()

### ISSUE THREAD

**Issue by rochamarcelo** [CakeDC/users#535]
Error in: ROOT/vendor/cakedc/users/src/Auth/SocialAuthenticate.php, line 68

I'm using  "cakedc/users": "^5.0" and "cakephp/cakephp": "^3.4".

Shouldn't  it be _isProviderEnabled instead of _isProviderEnable?

**Comment by jappanappsimity** [comment]
To fix the following error:

- Go to the 'vendor/cakedc/users/src/Auth/SocialAuthenticate.php' -> Line 68 

- Change the '_isProviderEnable' to '_isProviderEnabled'

**Comment by cristiandean** [comment]
https://github.com/CakeDC/users/pull/533

**Comment by steinkel** [comment]
Nice catch guys, there was a typo after a code refactor. I'm adding a unit test to cover it and preparing a patch release.

**Comment by steinkel** [comment]
Fixed in https://github.com/CakeDC/users/releases/tag/5.0.1
