### ISSUE TITLE
AuthLink Helper not showing link - CakeDC Users 5.0

### ISSUE THREAD

**Issue by faiyazalam** [CakeDC/users#538]
When I logged in as superuser, authlink helper is showing all the links which is ok but when I logged in as admin or user, authlink not showing any link.

AppController Code:

```
<?php
//AppController
class AppController extends Controller
{
    
    public $helpers = array(
        'CakeDC/Users.AuthLink',
        );
   
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('CakeDC/Users.UsersAuth');
        $this->loadComponent('Utils.GlobalAuth');
        $this->Auth->config('loginRedirect', array('controller'=>'Courses', 'action'=>'index', 'plugin'=>FALSE));
    }
    }
```
code inside the file permission.php

```
<?php
return [
        'Users.SimpleRbac.permissions' => [
            [
                'role' => 'user',
                'controller' => 'Posts',
                'action' => ['add', 'edit'],
            ],
            [
                'role' => 'admin',
                'controller' => 'Courses',
                'action' => ['index'],
            ],
            [
                'role' => 'admin',
                'controller' => 'Bargains',
                'action' => ['index'],
            ],
            [
                'role' => 'user',
                'plugin' => 'CakeDC/Users',
                'controller' => 'Users',
                'action' => ['profile', 'login', 'logout'],
            ],
            [
                'role' => 'user',
                'controller' => 'Users',
                'action' => ['view'],
            ],
            [
                'role' => 'user',
                'controller' => 'Courses',
                'action' => ['index', 'view', 'edit', 'delete'],
            ],
            
            
            
             [
                 //allow account owner to edit their profile
        'role' => ['user'],
        'controller' => ['MyUsers'],
        'action' => ['edit', 'delete'],
        'allowed' => function($user, $role, \Cake\Http\ServerRequest $request) {
    if('user' == $role)
    {
         $userId = \Cake\Utility\Hash::get($request->getAttribute('params'), 'pass.0');
         return $user['id'] == $userId;
    }
            return false;
        }
    ],
            
            
        ]
    ];
```

Code inside layout file default.ctp:

```<li><?php echo $this->AuthLink->link('Courses', array('controller'=>'courses', 'action'=>'index', 'plugin'=>FALSE));?></li>```

**Comment by steinkel** [comment]
@faiyazalam we've improved SimpleRbac adding a default rule log when debug is true. Please update via composer update your project and check debug.log to check which rule is causing issues. Thanks.

**Comment by faiyazalam** [comment]
Thanks for your response.

Here is the content of debug.log file:

`2017-04-10 17:06:16 Debug: For {"prefix":false,"plugin":false,"extension":false,"controller":"Courses","action":"index","role":"user"} --> Rule matched {"role":"user","controller":"Courses","action":["index","view","edit","delete","add"],"allowed":true} with result = 1`

As a User I am able to access this URL:
`http://localhost/cakephpapp/courses`

but still the link is not showing.

Since on localhost email does not work, I have activated all the users manually from database, does it make any difference?

**Comment by steinkel** [comment]
I don't know if that would make a difference, but `'controller'=>'courses'` should be `'controller'=>'Courses'` in your link url...

**Comment by faiyazalam** [comment]
@steinkel I have changed the link to 'controller'=>'Courses' but still not working.

**Comment by steinkel** [comment]
I was able to reproduce the issue here http://users-538-steinkel.c9users.io/app/ looks like an issue with the reverseRouting of a route inside a subdirectory.

Please try to install your application using a virtualhost pointing to webroot, this should fix the issue, and I'll take a look if this could be an issue in the Router class...

Thanks for reporting it.

**Comment by chav170** [comment]
Try add this at the begin of isAuthorize method in AuthHelper:

```
        // Convert url to array to use special url options
        if (is_string($url)) {
            $url = Router::parse($url);
        }
        $defaultUrlParams = [
            '_base' => false,
        ];
        $url = Hash::merge($defaultUrlParams, $url);
```

Not sure if it is the best approach tough.

**Comment by steinkel** [comment]
closed per #543 

Thank you!

**Comment by steinkel** [comment]
It was merged into master

**Comment by steinkel** [comment]
It was merged into master

**Comment by faiyazalam** [comment]
@steinkel I created virtual host, now it is working. thanks.

  @chav170  I think it is not good idea to do changes in core files. thanks for your response.
