### ISSUE TITLE
Is there a way to extend the register trait

### ISSUE THREAD

**Issue by alexlambson** [CakeDC/users#539]
I am trying to add a variable to the registration page to specify a moderator request. 

EG. Alex wants to be a moderator, so he follows a link to website.com/register/mod and that would mark `requests_moderator` as true upon creating the user. 

I know how to do this all except for extending the traits. Is it possible under the current implementation of the plugin?

**Comment by steinkel** [comment]
Hi @alexlambson you can do this extending the Register trait and using a custom controller, see https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md#extending-the-controller and using your extended trait in case of the default Register trait provided.

Thanks,
