### ISSUE TITLE
RFC: Multiple Tests Fail when defaultLocale is not english

### ISSUE THREAD

**Issue by lorenzomaieru** [CakeDC/users#541]
When using a test suite to integrate the plugin's tests into the app, several test will fail once the locale is changed.
This is mostly due to the string asserts failing to account for the localization of exception messages.

I would like to submit a PR to fix this, but first I would like to know which is the appropriate way of going about it.

Currently most of the exception message asserts are using method annotation, so it's impossible to include `__()` within the test methods to fix the issue; and moving all those annotations to be function calls within the test methods seems like a gigantic error-prone endeavor.

So maybe replacing the `defaultLocale` setting from the test classes's `setUp` method could be the way to go about this?

**Comment by steinkel** [comment]
I would suggest to keep translated only the user facing error messages, and use sprintf for exception messages only displayed to the developer, we were too verbose on translations on the previous versions of the plugin.

Setting a default locale on setUp() would make sense for me.

Thanks!
