### ISSUE TITLE
RFC: _initAuth in UsersAuthComponent allows actions for all controllers

### ISSUE THREAD

**Issue by lorenzomaieru** [CakeDC/users#542]
When loading `UsersAuthComponent` into the `AppController` as shown in the [docs](https://github.com/CakeDC/users/blob/master/Docs/Documentation/Installation.md#load-the-usersauth-component), the method `_initAuth` is called for every other component.
This method then[ calls Auth::allow](https://github.com/CakeDC/users/blob/master/src/Controller/Component/UsersAuthComponent.php#L121-L139) in every controller that uses this component, enabling a bunch of actions by default.

The obvious side effect of this is that if you name an action in another controller with the same name as any of those, it will be inadvertently set to public; which shouldn't be a problem, except that some of those allowed actions have pretty generic names.

wrapping the `_initAuth` call to be only executed if it's called from the "correct" controller requires knowledge of what the correct controller is, since `UsersController` is expected to be extended. So that doesn't seem to work. 

Should users just use Auth::deny on their controllers after adding the component? Perhaps this should be pointed out in the docs?

**Comment by steinkel** [comment]
This behavior was already fixed here https://github.com/CakeDC/users/commit/a2feed6d1882922e1b4c4b0c63656731514a6a49, please upgrade to latest version of the plugin. Thank you for reporting!

**Comment by lorenzomaieru** [comment]
I tried upgrading to 5.0 but it seems to require cakephp 3.4, which no longer supports php 5.5

I'll shoot a request up the management chain to see if that's not a problem. Thanks!

**Comment by steinkel** [comment]
Another reason to upgrade your CakrPHP core :)
