### ISSUE TITLE
Unable to find table class for current entity Error on ChangePassword

### ISSUE THREAD

**Issue by akkaweb** [CakeDC/users#547]
I have this strange issue when using CakeDC Users plugin with CakePHP 3.4.5. Perhaps, this could be a framework issue more than a plugin, but here is the problem.

While using the plugin's provided `change_password.ctp` file, I encounter the following error:

    Unable to find table class for current entity 

The error originates from `<?= $this->Form->create($user); ?>`.  I was able to temporarily fix the issue by making this change `<?= $this->Form->create((object) $user); ?>`, but obviously that is not the solution and I was wondering if there should be a fix thru either the plugin itself or the framework.

**Comment by steinkel** [comment]
could you debug $user to check what's being set to the view?

Thanks,

**Comment by akkaweb** [comment]
I missed your comment. I will test and post the result back here

**Comment by steinkel** [comment]
please reopen when you are able to debug
