### ISSUE TITLE
About RBAC configuration and AuthLink helper

### ISSUE THREAD

**Issue by sasilen** [CakeDC/users#548]
I have tried to follow [blog](https://www.cakedc.com/jorge_gonzalez/2016/02/21/cakedc_users_plugin_for_cakephp_3_-_update) for setting simple RBAC configuration. I guess that I am either missing something or I have misunderstood the usage somehow.

Authentication part goes just fine. Plugin is installed and loaded, login works nicely with socials. 

My configurations in the main app.
bootstrap.php
```Configure::write('Users.config', ['users']);
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
Configure::write('Users.Social.login', true); //to enable social login
Configure::write('Auth.authenticate.Form.fields.username', 'email');
```
AppController.php
```
public $helpers = [
    'CakeDC/Users.AuthLink',
     .
public function initialize()
    {
        parent::initialize();
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('CakeDC/Users.UsersAuth');
```
configuration.php
```return [
    'Users.SimpleRbac.permissions' => [
    .
     [
          'role' => 'user',
          'plugin' => 'sasilen/blog',
          'controller' => 'Posts',
          'action' => ['view','index','edit'],
          'allowed' => true,
      ]
     .
```
If I set following in the blog's AppController, role 'user' as well the others are able to access methods, otherwise not. It looks like that my permissions settings doesn't have any effect at all (its anyways read, because I can change error messages there).
```public function beforeFilter(Event $event)
 {
    $this->Auth->allow(['index','view','add']);
 }
```
I am not really sure should I even configure anything in the plugin AppController and should I write isAuthorized method. According to the blog, not. But my authorization is not working. Can you see, what I am doing wrong? Or give hints how to debug this issue.

Last but not least, I wanted to perform magic in Templates. I want to show links only if those are available for the current role.  I found out that you already have made AuthLinkHelper. 
In the documentation you are still referring the UserHelper which seems to be deprecated, but to the question...
$this->AuthLink->link() works fine, but how am I supposed to use it with delete method?

```<?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $post->id], ['confirm' => __('Are you sure you want to delete # {0}?', $post->id)]) ?>```

There weren't $this->AuthLink->postLink() defined and using $this->AuthLink->link() lacks confirmation in my tests for delete method.

Thanks, this is quite excellent plugin and therefore I want to adapt and understand more about the features it provides.

**Comment by sasilen** [comment]
I found solution for my RBAC issue after debugging CakeDC/users SimpleRbacAuthorize.php file. Seems that with my plugin I cant use sasilen/Blog identifier for the role, just plain Blog. This has been actually quite confusing numerous of times in different occasions, when to use just plugin name and and when it needs vendor. But I guess it's implementation issue.

The last AuthLink with postLink issue remains.

**Comment by yeliparra** [comment]
You could call to $this->AuthLink->isAuthorized() and then call to postLink only if is authorized or override postLink method for FormHelper to check first if it's authorized.

**Comment by steinkel** [comment]
@sasilen you need to use your plugin 'name' as defined in Plugin::load, case sensitive. Also note the latest version includes a handy debug output to help you debug rule issues. Check your `debug.log` file. Thanks,
