### ISSUE TITLE
default permissions missing

### ISSUE THREAD

**Issue by rrd108** [CakeDC/users#549]
Without adding the following to permissions.php the user can not logout and can not view his own profile
`      [
            'role' => '*',
            'controller' => 'Users',
            'action' => ['profile', 'logout'],
        ]`

`$this->User->welcome()` and `$this->User->logout()` also does not work without this.

I think these should be added to the default permissions.

**Comment by steinkel** [comment]
I see these permissions are defined here https://github.com/CakeDC/auth/blob/master/src/Auth/SimpleRbacAuthorize.php#L92 as defaults, but not in the default permission.php file used as a base/example, so we are going to add these permissions to the default file provided by the plugin too for reference. Thanks.

**Comment by steinkel** [comment]
closed per https://github.com/CakeDC/users/pull/551
