### ISSUE TITLE
Query string redirect not working

### ISSUE THREAD

**Issue by alexlambson** [CakeDC/users#552]
Hey guys,

It doesn't look like the plugin is redirecting to the `redirect` variable in the URL query.

I removed my `$this->Auth->loginRedirect()` and I get redirected to `/` anytime I log in. Am I missing something?

**Comment by steinkel** [comment]
Hi @alexlambson, related code is here https://github.com/CakeDC/users/blob/master/src/Controller/Traits/LoginTrait.php#L335 

Should we redirect to somewhere else on successful login?

Thanks,

**Comment by alexlambson** [comment]
CakePHP is putting a query string in the URL now when someone tries to access a page without being logged in. It sends them to `/login?redirect=[the-page-they-tried-to-access]`

I think there should be a way to tell CakeDC/Users to use that URL if it is set. 

I figured out a way to jerry rig it using the session, so I don't necessarily *need* it anymore, but it may be something to consider.

**Comment by steinkel** [comment]
This is what AuthComponent is doing here https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/AuthComponent.php#L780 and we use this function to determine the url to redirect to in https://github.com/CakeDC/users/blob/master/src/Controller/Traits/LoginTrait.php#L335 is this not working for you? Are you using CakePHP 3.4+?

**Comment by alexlambson** [comment]
Yeah, I am on CakePHP 3.4+. 

Let me do some additional testing. Right now it is not working for me when I set my Auth URL.

**Comment by alexlambson** [comment]
Just tested it. If I set `loginRedirect` in `AppController::initialize()` it will always go there regardless of redirect url. If I do not set `loginRedirect` it redirects to `/` upon logging in regardless of redirect URL. 

I have encountered URL redirect issues like this before when I save an entity. Basically, I need to save `$this->request->referrer()` to the session because when I click the submit button on whatever page the new referrer is the action that just submitted to itself. 

Maybe the URL redirect isn't getting carried through when clicking `login`?

**Comment by alexlambson** [comment]
And while I have your attention, can you give me a brief rundown of how to contribute to your project? Do I just fork your code then pull it into an existing project for testing?

I still need to make that `$this->AuthLink->loginButton()` for you guys. Also, can I donate to CakeDC to buy you guys a beer/lunch?

**Comment by steinkel** [comment]
@alexlambson we'll be happy if you donate to CakePHP instead https://nimbus.everhelper.me/client/notes/share/919754/gh64cczbhi64limdn8bc. 

Contributing is easy, fork the plugin and work on a feature branch (don't forget unit tests please) then send a pull request to develop if it's a new feature or master if it's an issue/bugfix. You have a longer explanation here > https://www.cakedc.com/contribution-guidelines

**Comment by alexlambson** [comment]
@steinkel I am confused about how I actually test what I am writing. Should I put this in the `vendor` folder of an existing project, or just bake a simple app into the code I forked?

**Comment by steinkel** [comment]
Ah I understand now, what I usually do is to bake a new project and then symlink the users folder to use my fork, or you can tweak the composer.json to user your fork via 'vcs' configuration... check the 'repositories' config option for composer.json

Thanks

**Comment by alexlambson** [comment]
Ah, so you have `vendors/CakeDC/users` but `users` is a symlink to wherever you have the repo? That's smart!

**Comment by alexlambson** [comment]
@steinkel I am still getting this issue. When I get redirected to the login page, the `?redirect=` is in the URL.

I attached xdebug to the LoginTrait login method and by the time it gets there the `?redirect=` query has been wiped. I cannot find where it is getting wiped out.

**Comment by steinkel** [comment]
So let me understand the issue:
* You are not logged in
* You hit a protected page
* You get redirected to login page via AuthComponent
* When you reach the login page, the `redirect` query param is lost

Right?

**Comment by jtraulle** [comment]
Same here ... so, I subscribe to this issue ;)
Exact same process as @alexlambson but not much luck :/

**Comment by jtraulle** [comment]
Woops, talked too quickly, it works actually.

**Comment by alexlambson** [comment]
I wonder, is there a way to get the query string to stick around after a registration?

Right now it's kind of hard to create the flow of:

1. User clicks link on eg Facebook
2. Ask them to register
3. After register, login and return them to the store page

**Comment by steinkel** [comment]
@alexlambson so this is related with the social login only? 

Please create a new ticket with this use case, we'll take a look. Thanks,

**Comment by alexlambson** [comment]
No, regular login, I'll make a ticket though
