### ISSUE TITLE
Facebook Login Tutorial Broken + Fresh Install Instructions (Not working for me)

### ISSUE THREAD

**Issue by dvelguru** [CakeDC/users#555]
BROKEN TUTORIAL LINK https://www.cakedc.com/jorge_gonzalez/2016/02/21/cakephp_facebook_login_using_cakedc_users_plugin_-_update_3_1_5

OBJECT NOT FOUND
Facebook authentication is working as expected on the Facebook side. But no user or social account is generated, and redirection results in a Object not found! error. I'm using localhost.

**Comment by chav170** [comment]
Hi @dvelguru,

Could you tell me where did you find that link?

The right link to Facebook tutorial is this one:
https://www.cakedc.com/jorge_gonzalez/2016/02/21/cakephp_facebook_login_using_cakedc_users_plugin_update_3_1_5

About OBJECT NOT FOUND error, i see you are using localhost. Do you have the project in a subfolder? 

In that case the redirect url that is generating is probably wrong, something like:
http://localhost/auth/facebook
when it should be
http://localhost/project-name/auth/facebook

To avoid those cases, its better to create a virtual host to point to the webroot folder of the app.

If you are using windows, check the last answer in the following link and create a virtualhost with a name like: project-name.dev (dont forget to update the Facebook app domain)
https://stackoverflow.com/questions/20275044/change-my-hosts-file-to-route-to-a-folder-and-not-an-ip

If after all this, you get an error like:

> Error message: OAuthException: (12) bio field is deprecated for versions v2.8 and higher

You have to upate the api version in you "config/users.php" file like this:

```
return [
    'Users.Social.login' => true,
    'OAuth.providers.facebook.options.graphApiVersion' => 'v2.8',
    'OAuth.providers.facebook.options.clientId' => 'XXXXXXXXX',
    'OAuth.providers.facebook.options.clientSecret' => 'XXXXXXXX',
];
```

**Comment by ajibarra** [comment]
Hi @dvelguru have you try the steps from @chav170? Please try them with the latest release. If you get any other issue please report a new one.
