### ISSUE TITLE
Dynamic roles ?

### ISSUE THREAD

**Issue by Reflej0** [CakeDC/users#556]
Hi, I wanted to know if CakeDC Users allows me to save the permissions of each role in the DB. Then I could assign or edit roles dynamically.

**Comment by steinkel** [comment]
Hi,
Managing permissions in the db is out of the scope of this plugin. 
But you can implement this using a Rule class. The Rule class would get the permissions from the db first and then match the permissions to return true if the user is allowed. You can extend https://github.com/CakeDC/auth/blob/master/src/Auth/Rules/AbstractRule.php and implement the `public function allowed(array $user, $role, ServerRequest $request)` to retrieve the permissions from the db (your table) matching the url from `$request` and the `$role` or `$user['id']` to check if he's allowed.

So the answer to your question is YES :+1:
