### ISSUE TITLE
Persistent authorization with multiple installations

### ISSUE THREAD

**Issue by mychaelo** [CakeDC/users#558]
Case: 2 cakePHP installations, using the same DB.
* website.corp
* events.website.corp, where users with role 'attendee' can view and register at events

The idea is to give the 'attendees' an access to the private sections of the main website, with other possible features. Now, since both installations use the same DB, there's no issue with linking up user accounts. There's however an issue with how to store and fetch session status across these installations. So far the workflow is as follows:
1. User logs in at events.website.corp
2. User follows a link, leading to a website.corp page
3. User needs to log in again on website.corp

Question: how to set this up so that website.corp is aware of events.website.corp authorization (and vice versa)? Should I extend RememberMeComponent to handle a 'foreign' cookie (if that is even possible)?

**Comment by steinkel** [comment]
Hi @mychaelo this is more an architecture decision than a feature you could implement in the scope of this plugin. If I understand correctly you are trying to share the session between 2 CakePHP apps sharing the same DB. 
Maybe the easiest solution would be to configure the session handler in both apps to be shared, for example using Redis or database sessions.

Thanks
