### ISSUE TITLE
Pass user to logout events

### ISSUE THREAD

**Issue by berarma** [CakeDC/users#560]
It would be nice that the user that is logging out would be passed to the beforeLogout and afterLogout event listeners.

The event listener for afterLogout may want to ask "Ok, but who's logged out?". This is particularly true when we want to log when users log in and out.

Before logout it's still easy to get the authenticated user, but after logout it's not. I think it would be nice to have the user data passed to both events.

**Comment by steinkel** [comment]
I agree

**Comment by steinkel** [comment]
closed per #580
