### ISSUE TITLE
URL for user registration has duplicate sub folder

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#563]
On a fresh install with Cake 3.4.7 (running bin/cake server), and CakeDC/Users ^5.0 the user registration url comes out to

    /users/users/register

Shouldn't it be 

    /users/register

?

**Comment by steinkel** [comment]
We actually have no route for register defined in the plugin routes, but it could make sense to add a default one `/register` similar to already existing `/login` and `/logout` but only if registration is allowed.

**Comment by jeffreyroberts** [comment]
I figured this out the other day....

/plugin/controller/action

so it makes sense now, and ya i added a route, just looks a little funny like that as a url =]

**Comment by durbster** [comment]
This caught me out too. I followed the plugin installation instructions on a clean cakephp install, so was confused why some of the links didn't work out of the box. 

I suspected it needed the routes setting up but that felt like I might have made an error setting up the plugin, so a mention in the documentation would have helped.

**Comment by steinkel** [comment]
do you think would be good to add a specific entry in the documentation with the provided routes?

**Comment by medichecks-kd** [comment]
Yes, just a reference somewhere to let devs know the default routes and behaviour. I thought I'd made a mistake when setting up the plugin and went back through the process a couple of times thinking I must have missed something. Thanks.

**Comment by durbster** [comment]
Yes, absolutely. A simple note that explains the default behaviour and routes would be useful. I thought I had made a mistake setting up the plugin so went back through the process a couple of times. Thanks.
