### ISSUE TITLE
How to autologin users after email validations?

### ISSUE THREAD

**Issue by vnt** [CakeDC/users#565]
How to implente autologin user after email validations?

**Comment by steinkel** [comment]
The email validation logic is done here > https://github.com/CakeDC/users/blob/master/src/Controller/Traits/UserValidationTrait.php#L39 and I see this code could be hard to extend as it's a trait used by another trait, so I think the best approach could be adding a new event you can inject from the outside `afterEmailTokenValidation` to autologin the user, we could provide it as a configuration option too.

**Comment by vnt** [comment]
When will this feature be available?

**Comment by steinkel** [comment]
closed per #937
