### ISSUE TITLE
Authentication adapter "CakeDC/Auth.ApiKey" was not found. 

### ISSUE THREAD

**Issue by shravanuchil** [CakeDC/users#570]
url : http://139.59.26.52
I have overridden ApiKeyAuthentication.
$config['Auth']['authenticate']['CakeDC/Users.ApiKey'] = [ 'type' => 'header'];

I am getting **"Authentication adapter "CakeDC/Auth.ApiKey" was not found. "** error.

please let me know the solution for this.

**Comment by steinkel** [comment]
What version of the plugin are you using?

Keep in mind the ApiKeyAuthenticate class is now here https://github.com/CakeDC/auth/blob/master/src/Auth/ApiKeyAuthenticate.php

**Comment by shravanuchil** [comment]
I have installed latest version through composer.
ApiKeyAuthenticate.php is present in same location which you have mentioned.

$config['Auth']['authenticate']['CakeDC/Auth.ApiKey'] = [ 'type' => 'header'];
this has been added plugins/cakedc/users/config/users.php
hope i have added to the correct place.
is there any other setting required in this ?

**Comment by steinkel** [comment]
not really, check the available options here: https://github.com/CakeDC/auth/blob/master/Docs/Documentation/ApiKeyAuthenticate.md Thanks

**Comment by shravanuchil** [comment]
$this->Auth->config('storage', 'Memory');
    $this->Auth->config('unauthorizedRedirect', 'false');
    $this->Auth->config('checkAuthIn', 'Controller.initialize');
    $this->Auth->config('loginAction', false);


Above lines added to the AppController.php

**Comment by shravanuchil** [comment]
do I need to set api_key value manually at any place ?

**Comment by steinkel** [comment]
in users table and then based on your configuration in the `header`

**Comment by makamo** [comment]
PLease fix [the configuration doc](https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md#default-authenticate-and-authorize-objects-used)
**CakeDC/Auth.ApiKey** is not an **Authorize** Class but an **Authenticate** Class

**Comment by emiliano-idata** [comment]
hello, I have an application working with the plugin cakedc users, I have two diferent roles, I need the same users can enter the site through a security token, is this possible with the api key and token?

ApiKeyAuthenticate? some example, thanks a lot.

**Comment by steinkel** [comment]
We identify 1 token with 1 user, and each user has 1 role. You could create a roles table, belongsTo Users and then write your own authorization adapter, keep in mind the responsibility of the ApiKeyAuthenticate is to identify the user via token, later on you can check permissions based on your custom Authorization objects...

**Comment by mbenjemaa** [comment]
https://github.com/CakeDC/auth/blob/master/src/Auth/ApiKeyAuthenticate.php
file not found.

I got the error: Authentication adapter "CakeDC/Users.ApiKey" was not found.
I use Cakephp 3.7

**Comment by Devin0231577** [comment]
> https://github.com/CakeDC/auth/blob/master/src/Auth/ApiKeyAuthenticate.php
> file not found.
> 
> I got the error: Authentication adapter "CakeDC/Users.ApiKey" was not found.
> I use Cakephp 3.7

Use "CakeDC/**Auth**.ApiKey" instead of "CakeDC/**Users**.ApiKey"
