### ISSUE TITLE
Feature request to please change registration email subject

### ISSUE THREAD

**Issue by nkoiumi** [CakeDC/users#572]
Hiya,

First off is there anyway to extend the plugin that would allow us to change the hardcoded subject below in the EmailSender

```
public function sendValidationEmail(EntityInterface $user, Email $email = null)
    {
        $this
            ->getMailer(
                'CakeDC/Users.Users',
                $this->_getEmailInstance($email)
            )
            ->send('validation', [$user, __d('CakeDC/Users', 'Your account validation link')]);
    }
```
our client needs the words [Unclassified] appended to the beginning of the email. If not would it be possible to update this method so that we might be able to set the subject in the user.php config file?

Thank you!

**Comment by steinkel** [comment]
I agree, we already have a ticket with the request to make the emails more configurable here #476, I'm going to close this one and refer to that ticket for adding the subject configurable too. Thanks for reporting!
