### ISSUE TITLE
Quick Question on Change Password

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#578]
The password field is being populated with the encrypted password of the user, what line can I put behind the scenes to blank out the password?

I tried

    $user->password = '';

but it still populated it...

**Comment by jeffreyroberts** [comment]
or maybe there is a 

    'populate' => false 

or something I can add to 

    <?php echo $this->Form->control('password', ['label' => false, 'type' => 'password', 'placeholder' => 'Password', 'class' => 'form-control']); ?>

**Comment by jeffreyroberts** [comment]
Maybe

    'type' => 'password'

should never be populated?

**Comment by steinkel** [comment]
Sorry, populated in which page? Looks like it's your browser doing it?

**Comment by jeffreyroberts** [comment]
i dont think its the browser

http://i64.tinypic.com/2zsnp6x.png

**Comment by jeffreyroberts** [comment]
tinypic must have removed the pic... the password that is being populated on the change_password.ctp page in the name='password' input is the encrypted password from the database

**Comment by jeffreyroberts** [comment]
![screen shot 2017-07-07 at 12 43 46 pm](https://user-images.githubusercontent.com/2320614/27976299-db9fee16-6333-11e7-97a8-bc289acef365.png)

**Comment by jeffreyroberts** [comment]
look at that, screenshots on github, sweet

**Comment by jeffreyroberts** [comment]
I changed it to type text to reveal the password

**Comment by steinkel** [comment]
Could you share the controller action and view code for your change password page?

I've just tested it here and the user's password is never populated by the browser

https://nimbus.everhelper.me/client/notes/share/1003785/iss0k1fi22qpmtntextk

You have a working example here https://ide.c9.io/steinkel/users-34-example

Even more than that, the password is not being retrieved from the database in the changePassword  method in PasswordManagementTrait, as we create the entity using newEntity, not reading the user. 

Thanks,

**Comment by jeffreyroberts** [comment]
I added it to the Profile page as a tab....

![screen shot 2017-07-07 at 8 38 26 pm](https://user-images.githubusercontent.com/2320614/27981072-418d35c4-6354-11e7-8833-032004173f81.png)

Then modded the ProfileTrait

    trait ProfileTrait
    {
    
        /**
         * Profile action
         * @param mixed $id Profile id object.
         * @return mixed
         */
        public function profile($id = null)
        {
            $loggedUserId = $this->Auth->user('id');
    
            if (!Configure::read('Users.Profile.viewOthers') || empty($id)) {
    
                $id = $loggedUserId;
            }
    
            $user = $this->getUsersTable()->newEntity();
    
            if (!empty($id)) {
                $user->id = $this->Auth->user('id');
                $validatePassword = true;
                //@todo add to the documentation: list of routes used
                $redirect = Configure::read('Users.Profile.route');
            } else {
                $user->id = $this->request->session()->read(Configure::read('Users.Key.Session.resetPasswordUserId'));
                $validatePassword = false;
                if (!$user->id) {
                    $this->Flash->error(__d('CakePHPKitchen/CakeAdminUsers', 'User was not found'));
                    $this->redirect($this->Auth->config('loginAction'));
    
                    return;
                }
                //@todo add to the documentation: list of routes used
                $redirect = $this->Auth->config('loginAction');
            }
            $this->set('validatePassword', $validatePassword);
    
            $isCurrentUser = false;
    
            try {
                $appContain = (array)Configure::read('Auth.authenticate.' . AuthComponent::ALL . '.contain');
                $socialContain = Configure::read('Users.Social.login') ? ['SocialAccounts']: [];
                $user = $this->getUsersTable()->get($id, [
                        'contain' => array_merge((array)$appContain, (array)$socialContain)
                    ]);
                $this->set('avatarPlaceholder', Configure::read('Users.Avatar.placeholder'));
                if ($user->id === $loggedUserId) {
                    $isCurrentUser = true;
                }
            } catch (RecordNotFoundException $ex) {
                $this->Flash->error(__d('CakePHPKitchen/CakeAdminUsers', 'User was not found'));
    
                return $this->redirect($this->request->referer());
            } catch (InvalidPrimaryKeyException $ex) {
                $this->Flash->error(__d('CakePHPKitchen/CakeAdminUsers', 'Not authorized, please login first'));
    
                return $this->redirect($this->request->referer());
            }
    
            $table = $this->loadModel();
            $tableAlias = $table->alias();
            $entity = $table->get($id, [
                'contain' => []
            ]);
    
            $this->set($tableAlias, $entity);
            $this->set('tableAlias', $tableAlias);
            $this->set(compact('user', 'isCurrentUser'));
            $this->set('_serialize', ['user', 'isCurrentUser', $tableAlias, 'tableAlias']);
        }
    }

My question is, how do I go about blanking out the password from behind the scenes, I believe @steinkel has hinted to creating a newEntity instead of reading the user, thing is, I have the edit page on the profile page as a tab as well, so, not really sure what the best solution is, any ideas? =]

**Comment by jeffreyroberts** [comment]
Ive gone over the Password Management Trait, I understand now that you create a new user entity and then set the user id... Im guessing based off of that example, I could go through and enter all the user vars except for the password and it "should" work, however, if that is the case, then blanking the password, "should" work as well, with

    $user->password = '';

so with that said, im guessing, since $user->password = ''; does not blank out the password, that the inputs are populated in some other manner, is this the case?

**Comment by jeffreyroberts** [comment]
Im guessing at this time that

        $table = $this->loadModel();

        $tableAlias = $table->alias();

        $entity = $table->get($id, [
            'contain' => []
        ]);

        $this->set($tableAlias, $entity);

the above code is responsible for populating the inputs, is something like

    $entity->password = '';

possible?

**Comment by jeffreyroberts** [comment]
Here is my most up-to-date function

        public function profile($id = null)
        {
            $loggedUserId = $this->Auth->user('id');
    
            if (!Configure::read('Users.Profile.viewOthers') || empty($id)) {
    
                $id = $loggedUserId;
            }
    
            $user = $this->getUsersTable()->newEntity();
    
            if (!empty($id)) {
                $user->id = $this->Auth->user('id');
                $validatePassword = true;
                //@todo add to the documentation: list of routes used
                $redirect = Configure::read('Users.Profile.route');
            }
    
            $isCurrentUser = false;
    
            try {
                $appContain = (array)Configure::read('Auth.authenticate.' . AuthComponent::ALL . '.contain');
                $socialContain = Configure::read('Users.Social.login') ? ['SocialAccounts']: [];
                $user = $this->getUsersTable()->get($id, [
                        'contain' => array_merge((array)$appContain, (array)$socialContain)
                    ]);
                $this->set('avatarPlaceholder', Configure::read('Users.Avatar.placeholder'));
                if ($user->id === $loggedUserId) {
                    $isCurrentUser = true;
                }
            } catch (RecordNotFoundException $ex) {
                $this->Flash->error(__d('CakePHPKitchen/CakeAdminUsers', 'User was not found'));
    
                return $this->redirect($this->request->referer());
            } catch (InvalidPrimaryKeyException $ex) {
                $this->Flash->error(__d('CakePHPKitchen/CakeAdminUsers', 'Not authorized, please login first'));
    
                return $this->redirect($this->request->referer());
            }
    
            $user->password = '';
    
            $table = $this->loadModel();
            $tableAlias = $table->alias();
            $entity = $table->get($id, [
                'contain' => []
            ]);
    
            $this->set('validatePassword', $validatePassword);
            $this->set($tableAlias, $entity);
            $this->set('tableAlias', $tableAlias);
            $this->set(compact('user', 'isCurrentUser'));
            $this->set('_serialize', ['user', 'isCurrentUser', $tableAlias, 'tableAlias']);
        }

**Comment by jeffreyroberts** [comment]
I think i need to read more about entities, because im doing a beforeRender and grabbing the user details to display the avatar, etc... then i get to the profile trait and I re-grab the user, but anything that is auto-populated is auto-populated with the most recent grabbed user, and the user details like avatar and such dont change which is awesome, so i guess i got some reading to do, any ideas at all is greatly appreciated, i had life event several years ago, and my brain doesnt function as well anymore unfortunately, but im trying to get back into coding, i sorta woke up a bit today and realized i didnt need half that code, i was just throwing stuff together, its all part of the recovery process for me i guess, so I really truly appreciate your patience with me, i think im going to go back to the forum and start a new thread, thank you so much for your help and contributions to the community

**Comment by steinkel** [comment]
@jeffreyroberts you actually don't need to delete the existing user password in the entity, just tweak the `$this->Form->control('password', ['type' => 'password', 'value' => ''])` control on the view template.

Thank you for reporting these questions, this could be helpful for others!

**Comment by jeffreyroberts** [comment]
word! that did it =] thank you!
