### ISSUE TITLE
How do I access the variables in a form?

### ISSUE THREAD

**Issue by jpforte** [CakeDC/users#579]
This is a newbie question but, how do I access the Users fields in a template?

I have a nav bar that I want to display the user. I have tried $this->User->last_name but that outputs nothing, however $this->User->logout;  does gerate a logout link.

**Comment by steinkel** [comment]
Hi @jpforte you'll need to set the user entity first from the controller using `$this->set('user', $user);` then you have a `user` variable accessible in the template you could use to display the required information.

Thanks,
