### ISSUE TITLE
Various Notes for Newbies or those with questions

### ISSUE THREAD

**Issue by jcharlesmorris** [CakeDC/users#58]
I'm testing each function in this application because I'm going to be using it in an project.  I thought I would point out a few of my findings.  Community members,  please correct my usage if I miss-speak.  My intention is to help someone who has run into similar issues.
# Users Controller
###### Change

<pre>'from' => 'noreply@' . env('HTTP_HOST'),</pre>

###### To

<pre>'from' => Configure::read('App.defaultEmail'),</pre>

# Email template

I ran into an issue using the default email password reset template.  I have copied all of the email templates to /app/View/Plugin/users/Emails/.  

If you are using the routes from the readme you will need to:
###### Change

<pre>echo Router::url(array('admin' => false, 'plugin' => 'users', 'controller' => 'users', 'action' => 'reset_password', $token), true);</pre>

###### To

<pre>echo Router::url(array('controller' => 'users', 'action' => 'reset_password', $token), true);</pre>

###### Or

Simply customize the templates to your liking.
# Readme Notes
###### This

<pre>

App::uses('User', 'Users.Model');
class AppUser extends User {
    public $useTable = 'users';
}

</pre>

###### Should Be This

<pre>
App::import('Model', 'Users.User');
class AppUser extends User {
    public $useTable = 'users';
    public $alias = 'User';
</pre>

## Changing login redirect and other _setupAuth() stuff

I created a AppUsersController.php with the following:

<pre>
App::uses('UsersController', 'Users.Controller');
class AppUsersController extends UsersController {
  public $name = 'Users';

  public function __construct($request = null, $response = null) {
    parent::__construct($request, $response);
    $this->User = ClassRegistry::init('AppUser');
  }

  public function beforeFilter() {
    parent::beforeFilter();
    
  }

  public function _setupAuth() {
    parent::_setupAuth();

    $this->Auth->autoRedirect = false;
    $this->Auth->loginRedirect = '/admin/users/users';
    $this->Auth->loginRedirect = '/login';

  }
</pre>

Please note that I am inheriting the model a little different than the docs suggest by doing this:

<pre>
$this->User = ClassRegistry::init('AppUser');
</pre>

Then added the following to my routes:

<pre>
  //Used to extend the users controller
  Router::connect('/users', array('plugin' => null, 'controller' => 'AppUsers'));
  Router::connect('/users/:action/*', array('plugin' => null, 'controller' => 'AppUsers', 'action' => 'index'));
</pre>

**Comment by adam-je** [comment]
This plugin makes me want to revert to CakePHP 2.x. So frustrated as I have to rebuild my whole app and start learning 2.x

**Comment by tuffz** [comment]
@adam-je: i can't understand why the master branch is an unstable version, too.

**Comment by adam-je** [comment]
@tuffz have you managed to get it working or found any other plugin that can at least multi-user Access Control?

I have looked at @burzum 's Cakephp User Tools (https://github.com/burzum/cakephp-user-tools) Just not sure if it supports multi-users though I've seen ['role' => 'admin'] in the code, docs are quiet on this.

**Comment by steinkel** [comment]
@adam-je you are welcome to contribute any documentation improvements, we'll review and merge them

@tuffz the master branch is stable, we added a note to the README recently to let others know there is a 3.x ALPHA branch available if you are interested.

Thank you,
