### ISSUE TITLE
Redirect Users to Custom Pages by Role

### ISSUE THREAD

**Issue by tarek85** [CakeDC/users#581]
Hi, 
I cannot find where I can configure the link after a user was logged in.
I have differents roles in my app and I want each role  be redirected to his own homepage.
How is it possible in this plugin. Sorry I'm a newbies!!
Thanks!

**Comment by chav170** [comment]
Hi @tarek85, you can add the redirect logic as an event, like this:

Create the file "src/config/events.php" with the following content:

```
<?php
use CakeDC\Users\Controller\Component\UsersAuthComponent;
use Cake\Event\Event;
use Cake\Event\EventManager;

EventManager::instance()->on(
    UsersAuthComponent::EVENT_AFTER_LOGIN,
    ['priority' => 99], // set last in the priority queue in case you add more events to AFTER_LOGIN
    function (Event $event) {
        if ($event->data['user']['role'] === 'admin') {
            return ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'index'];
        }
        if ($event->data['user']['role'] === 'user') {
            return ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'profile'];
        }

        // other roles will be redirected to the url configured at 'Auth.loginRedirect' in "src/config/users.php"
    }
);
```

And add at the end of the file "src/config/bootstrap.php" the line:

```
require_once 'events.php';
```

You can learn more about events here: https://book.cakephp.org/3.0/en/core-libraries/events.html

And you can see the events available in the plugin in this file: https://github.com/CakeDC/users/blob/master/src/Controller/Component/UsersAuthComponent.php
