### ISSUE TITLE
Twitter Avatar not showing - wrong suffixed avatar image url

### ISSUE THREAD

**Issue by donnigundala** [CakeDC/users#582]
as my knowledge twitter avatar image suffixes has been changed and no longer using *_square suffix.
and this causing the twitter avatar image not displayed/not found.

please update/change the CakeDC/Users twitter image suffixes at SocialBehaviour to

*_bigger,
*_normal,

![screenshot from 2017-07-25 15-27-51-code](https://user-images.githubusercontent.com/13811899/28562813-f5c50bb4-714d-11e7-9b0a-965dc686c2d3.png)

**Comment by steinkel** [comment]
closed per #614 and merged into develop already
