### ISSUE TITLE
The "Auth" alias has already been loaded with the following config

### ISSUE THREAD

**Issue by urfusion** [CakeDC/users#583]
I have a running website which is using `tinyauth` now I want to integrate Facebook login. 
I follow the instructions mention in 
https://www.cakedc.com/jorge_gonzalez/2016/02/21/cakephp_facebook_login_using_cakedc_users_plugin_update_3_1_5

Now I am getting following error.

`The "Auth" alias has already been loaded with the following config: array ( 'authenticate' => array ( 'all' => array ( 'finder' => 'auth', 'userModel' => 'CakeDC/Users.Users', ), 0 => 'CakeDC/Auth.ApiKey', 1 => 'CakeDC/Auth.RememberMe', 2 => 'Form', 3 => 'CakeDC/Users.Social', ), 'authorize' => array ( 0 => 'CakeDC/Auth.Superuser', 1 => 'CakeDC/Auth.SimpleRbac', ), 'ajaxLogin' => NULL, 'flash' => NULL, 'loginAction' => array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'login', 'prefix' => false, ), 'loginRedirect' => NULL, 'logoutRedirect' => NULL, 'authError' => NULL, 'unauthorizedRedirect' => true, 'storage' => 'Session', 'checkAuthIn' => 'Controller.startup', ) which differs from array ( 'authorize' => array ( 0 => 'Controller', ), 'authenticate' => array ( 'Authenticate.Advance' => array ( 'lockout' => array ( 'retries' => '3', 'expires' => '5 minutes', 'file_path' => 'prevent_brute_force', ), 'remember' => array ( 'enable' => '1', 'key' => 'RememberMe', 'expires' => '1 month', ), 'fields' => array ( 'username' => 'email', 'password' => 'password', ), 'scope' => array ( 'Users.status' => true, ), ), ), 'loginAction' => array ( 'controller' => 'Users', 'action' => 'login', ), 'loginRedirect' => array ( 'controller' => 'Dashboard', 'action' => 'index', ), 'logoutRedirect' => array ( 'controller' => 'Users', 'action' => 'login', ), 'unauthorizedRedirect' => false, 'authError' => 'Did you really think you are allowed to see that?', )`

**Comment by steinkel** [comment]
Hi @urfusion this plugin manages the loading of Auth component internally by default, but you can configure how Auth should work checking the configuration here > https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md#default-authenticate-and-authorize-objects-used also you could decide to manage the AuthComponent your own, you have an option to completely disable Auth loading from inside CakeDC/Users here https://github.com/CakeDC/users/blob/master/config/users.php#L22 so you can define `auth` to false, and previously load the AuthComponent with your custom configuration. Thanks!
