### ISSUE TITLE
Having 302 Redirects when using ApiKeyAuthenticate

### ISSUE THREAD

**Issue by akkaweb** [CakeDC/users#592]
I am trying to use ApiKey to authorize access to my API by sending the key in the Header of the request. While testing, it seems it is redirecting a breaking. If at some point I add `$this->Auth->allow()`, then all is good.

The endpoint I am using is `/v1/order-export/orders`, which basically calls a `orders` method. The OrderExport controller extends an ApisController. Below are the files I am using:

Controller/V1/OrderExportsController.php

    class OrderExportController extends ApisController {

Controller/ApisController.php

    namespace App\Controller;

    use App\Controller\AppController;

    class ApisController extends AppController {
        public function initialize() {
            parent::initialize();

            $this->Auth->config('authenticate', [
                'CakeDC/Users.ApiKey' => [
                    'type' => 'header',
                    'require_ssl' => false
                ]
            ]);

            $this->Auth->config('storage', 'Memory');
            $this->Auth->config('unauthorizedRedirect', 'false');
            $this->Auth->config('checkAuthIn', 'Controller.initialize');
            $this->Auth->config('loginAction', false);
        }
    }

Controller/AppController.php

    public function initialize() {

        parent::initialize();

        $this->loadComponent('CakeDC/Users.UsersAuth');

        $this->Auth->config('authorize', [
            'CakeDC/Users.Superuser',
            'CakeDC/Users.SimpleRbac',
        ]);

**Comment by sharkooon** [comment]
Well, i'm having the same issue. On test machine (mamp, macos) no problem using api_key. But on production server CentOs, same configuration... it redirects (302) to login page. After changing it to ApiKey it worked.. but still weird!
ModSecurity off
