### ISSUE TITLE
Inconsistent logged user check order when submitting a form

### ISSUE THREAD

**Issue by rogerpro** [CakeDC/users#593]
When submitting a form, if the session timed out, the form data is lost and the app shows two flash error messages:

1. You are not authorized to access that location.
2. You are already logged in

The blank form appears with no data and the sent data has not been processed.

"You are not authorized to access that location." comes from [\Cake\Controller\Component\AuthComponent::_setDefaults()](https://github.com/cakephp/cakephp/blob/3.4.13/src/Controller/Component/AuthComponent.php#L496)

"You are already logged in" comes from 
[\CakeDC\Users\Controller\Traits\LoginTrait::login()](https://github.com/CakeDC/users/blob/5.0.3/src/Controller/Traits/LoginTrait.php#L191)

I'm using the latest versions of:

- CakePHP 3.4.13
- CakeDC/users 5.0.3

### What you did
I baked a brand new app with a single table database (table 'things').
I installed and configured CakeDC/users.
Those first steps are already done on [this app](https://github.com/rogerpro/testusers). Just do `git clone git@github.com:rogerpro/testusers.git`, run `composer install`, configure a database and run `bin/cake migrations migrate` to try it in a few minutes.

I configured the app to have a very short session timeout of only 1 minute, just for testing purposes.
In `config/app.php`
```
    'Session' => [
        'defaults' => 'php',
        'timeout' => 1
    ],
```

I created an admin user with `bin/cake users addSuperuser`

I logged in.

I went to `/things` in the browser.

I clicked on the 'New Thing' menu item.

I waited for more than a minute.

I submitted the form.

### What happened
Two flash error messages appeared:
1. You are not authorized to access that location.
2. You are already logged in

The form became blank.

No data was saved.

### What you expected to happen
I expected that the data was saved,

a success flash message with "The thing has been saved.",

and to be redirected to the index action (/testusers/things).

## Conclusion

It looks that AuthComponent is rejecting the form submission because of the time out, just after redirecting to login. The user will be logged again without the need to refill the login form. And when logging, for some reason LoginTrait will realize that the user is already logged in.

Appartently, the fix is just to try to log in again before raising the flash error message.

**I would be happy to submit a PR to fix this issue. I studied the behavior of the plugin with the CakePHP core, but I would appreciate a tip to where should the issue come from.**

Note: the issue happens either using the Security & Csrf components or not.

**Comment by brundlefly** [comment]
I too am encountering this issue.
