### ISSUE TITLE
Can I just create my own role type, or am I missing something?

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#597]
I have the following

        [
            'role' => ['member'],
            'controller' => ['Billing'],
            'action' => ['cancel'],
            'allowed' => true,
        ],

I am logged in with a user that has role = 'member', however, I am getting Unauthorized access....

If I put role => '*', then it works, so I am guessing its not recognizing my role as member, or do I need to whitelist member somewhere?

**Comment by steinkel** [comment]
Yes, you can create your own roles, check the logged in user has the right role. Logout and login to ensure the right role is updated in session.

Thanks,
