### ISSUE TITLE
cakedc/auth version constraint

### ISSUE THREAD

**Issue by jtraulle** [CakeDC/users#601]
https://github.com/CakeDC/users/blob/c0897ae5fec39ff4788bad81348ee26a80386440/composer.json#L31

Shouldn't it be **^2.0** ?

Still can't update to [cakephp/cakephp](/cakephp/cakephp) 3.5 right now because [cakedc/users](/cakedc/users) 5.1 requires [cakedc/auth](/cakedc/auth) ^1.0 and that [cakedc/auth](/cakedc/auth) ^1.0 requires [cakephp/cakephp](/cakephp/cakephp) **~3.4.0** and not **^3.4.0**

**Comment by jtraulle** [comment]
Workaround in the meantime : 
```
"cakedc/users": "^5.1",
"cakedc/auth": "2.0 as 1.1.0",
```

**Comment by steinkel** [comment]
This is done in develop already https://github.com/CakeDC/users/blob/develop/composer.json#L31 it'll be pushed to master on next release...

Thanks,

**Comment by jtraulle** [comment]
Thanks :)
