### ISSUE TITLE
Clean installation on CakePHP 3.5.1 causes too many redirects

### ISSUE THREAD

**Issue by wschwarte** [CakeDC/users#604]
I installed CakePHP 3.5.1. I installed Users (with dev-develop). Migrated the database. Created an account. Validated the email. Then I tried to login but i get a 'too many redirects' error. 

Not sure what causes the error. Should this version be fully compatible with 3.5.1?

**Comment by steinkel** [comment]
It looks like a permissions issue, please check debug.log file, a log with the failed rule should be there helping you to debug the issue.

I've been using the plugin (dev-develop branch) with 3.5.1 for some time without issues, and here is a running environment you can clone https://ide.c9.io/steinkel/users-35-example using latest develop branch.

Thanks, please reopen if you detect any other issue...

**Comment by steinkel** [comment]
I did another pass on this issue, and the problem is related to projects missing a permissions.php file, we are fixing this one in develop now

**Comment by steinkel** [comment]
Please check again, do a composer install we've just released a fix in CakeDC/Auth plugin to correctly read the default permissions when no file in project...

Thanks

**Comment by wschwarte** [comment]
Yes, it is working now on a clean install.
