### ISSUE TITLE
CakePHP 3.5.1 cakedc/users install problem

### ISSUE THREAD

**Issue by phpraven** [CakeDC/users#605]
Hi, 
When i try to install cakedc/users im getting this error:

`  Problem 1
    - cakedc/auth 1.1.0 requires cakephp/cakephp ~3.4.0 -> satisfiable by cakephp/cakephp[3.4.0, 3.4.0-RC1, 3.4.0-RC2, 3.4.0-RC3, 3.4.0-RC4, 3.4.0-beta1, 3.4.0-beta2, 3.4.0-beta3, 3.4.0-beta4, 3.4.1, 3.4.10, 3.4.11, 3.4.12, 3.4.13, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9] but these conflict with your requirements or minimum-stability.
    - cakedc/auth 1.0.2 requires cakephp/cakephp ~3.4.0 -> satisfiable by cakephp/cakephp[3.4.0, 3.4.0-RC1, 3.4.0-RC2, 3.4.0-RC3, 3.4.0-RC4, 3.4.0-beta1, 3.4.0-beta2, 3.4.0-beta3, 3.4.0-beta4, 3.4.1, 3.4.10, 3.4.11, 3.4.12, 3.4.13, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9] but these conflict with your requirements or minimum-stability.
    - cakedc/auth 1.0.1 requires cakephp/cakephp ~3.4.0 -> satisfiable by cakephp/cakephp[3.4.0, 3.4.0-RC1, 3.4.0-RC2, 3.4.0-RC3, 3.4.0-RC4, 3.4.0-beta1, 3.4.0-beta2, 3.4.0-beta3, 3.4.0-beta4, 3.4.1, 3.4.10, 3.4.11, 3.4.12, 3.4.13, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9] but these conflict with your requirements or minimum-stability.
    - cakedc/auth 1.0.0 requires cakephp/cakephp ~3.4.0 -> satisfiable by cakephp/cakephp[3.4.0, 3.4.0-RC1, 3.4.0-RC2, 3.4.0-RC3, 3.4.0-RC4, 3.4.0-beta1, 3.4.0-beta2, 3.4.0-beta3, 3.4.0-beta4, 3.4.1, 3.4.10, 3.4.11, 3.4.12, 3.4.13, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9] but these conflict with your requirements or minimum-stability.
    - cakedc/users 5.1.0 requires cakedc/auth ^1.0 -> satisfiable by cakedc/auth[1.0.0, 1.0.1, 1.0.2, 1.1.0].
    - Installation request for cakedc/users ^5.1 -> satisfiable by cakedc/users[5.1.0].
`

Is there any fix for this issue ? Thanks for any help

**Comment by steinkel** [comment]
Duplicated #596 we'll publish a release soon, meanwhile please use `dev-develop` branch which is compatible with 3.5.x thanks!

**Comment by Oxicode** [comment]
+1
