### ISSUE TITLE
User::updateToken should be updated.

### ISSUE THREAD

**Issue by alysson-azevedo** [CakeDC/users#608]
Currently the User entity uses `Text::uuid()` to generate the token. [See](https://github.com/CakeDC/users/blob/master/src/Model/Entity/User.php#L158-L164).
But this [commit](https://github.com/cakephp/cakephp/commit/28d6c35d534ffc97950d087efd829223f4aabeba) says it should use `Security::randomBytes()`

**Comment by steinkel** [comment]
closed per #609
