### ISSUE TITLE
Extending the Model , can't save data in my_users table

### ISSUE THREAD

**Issue by blackstar-7** [CakeDC/users#613]
i followed exactly the docs for extending the model  and use my own table my_users 
but it still save the data in users table ! 
in my database i have 3 tables : **users** , **my_users** , **social_accounts**  
im keeping users table for now just for testing .
in my **config\bootstrap.php** 
```
 Configure::write('Users.config', ['users']);
 Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]); 
```
in my **config\users.php** : 

```
return [
    'Users.table' => 'MyUsers',
];
```
in  **src/Model/Table/MyUsersTable.php** : 
```
namespace App\Model\Table;

use CakeDC\Users\Model\Table\UsersTable;

/**
 * Users Model
 */
class MyUsersTable extends UsersTable
{
}
```
in **src/Model/Entity/MyUser.php**

```
namespace App\Model\Entity;

use CakeDC\Users\Model\Entity\User;

class MyUser extends User
{
}
```

- so when new user is register , data is stored in users table not in my_user table !
- and even if  the data is stored in my_users  there is a foreign key associated to social_accounts i tried to change that in mysql,  and in the plugin code  (SociaAccountsTables) but then i get more errors ! 

can anyone give  me some nots that im missing ?  thanks

**Comment by steinkel** [comment]
@blackstar-7 extending the table is a common action we do in every version. We also have a working example you can review and use in case there is an issue while loading your configuration or setting the right parameters.

Please check https://ide.c9.io/steinkel/users-example-custom-table 

Thanks,

**Comment by chav170** [comment]
@blackstar-7 
You are extending UsersTable, and users table is doing this:

`$this->setTable('users');`

Try adding the following to src/Model/Table/MyUsersTable.php:

```
public function initialize(array $config)
{
    parent::initialize($config);
    $this->setTable('my_users');
}
```

**Comment by blackstar-7** [comment]
@chav170  i did that and it give me this Database Error : 
![db](https://user-images.githubusercontent.com/13630972/30752794-4ae9c59a-9fb5-11e7-883f-5451386ed4d4.png)
i understand there is an association between users table and social_accounts table
 do i have to create a new association between my_users and social_accounts ?

**Comment by blackstar-7** [comment]
thank you @steinkel  @chav170  it  works i only need to add   $this->setTable('my_users');

**Comment by steinkel** [comment]
nice!
