### ISSUE TITLE
AJAX for login, register, change password?

### ISSUE THREAD

**Issue by cercos** [CakeDC/users#615]
Any plans to have AJAX support for the login, register and change password actions?  I'm having trouble figuring out how to get validation errors with a form submitted via AJAX using the plugin.

**Comment by steinkel** [comment]
Hi @cercos we could provide an example about how to do this, but basically errors would be processed via javascript, unless you return an html form "with" the errors rendered from the backend.

**Comment by steinkel** [comment]
closed per #789
