### ISSUE TITLE
get an error when using  $this->Auth->setUser($user) 

### ISSUE THREAD

**Issue by blackstar-7** [CakeDC/users#617]
usualy after editing a user info i call` $this->Auth->setUser($user)`  to save user info to session 
but i get this error after refreshing the page : 
![se](https://user-images.githubusercontent.com/13630972/30828364-6830c7b6-a235-11e7-9aab-5f25d409cd2c.png)
is there anyway to  work around this ? 
in   **override edit action**  : 

```
    public function edit() 
    {
       
       if ($this->request->is(['ajax','post'])) { 
         $id = $this->Auth->user('id');
         $user = $this->Users->get($id); 

         $user = $this->Users->patchEntity($user, $this->request->getData());
          
         if ($this->Users->save($user)) {
         
          $this->Auth->setUser($user);
          
          $this->response->body('success');
          return $this->response;
         }

          $this->response->body(json_encode($user->getErrors()));
          return $this->response;
        }
    }
```

**Comment by rochamarcelo** [comment]
The method setUser expects an array.

Try this: $this->Auth->setUser($user->toArray());

**Comment by blackstar-7** [comment]
thank you very much @rochamarcelo
