### ISSUE TITLE
Prevent user login the same time in differents computers

### ISSUE THREAD

**Issue by joserafael** [CakeDC/users#618]
Please I need someone to recommend me and tell me how best to prevent a user from entering at the same time from two different browsers or from two computers. This is to prevent the already created accounts will be exchanged.

Thank you.

**Comment by steinkel** [comment]
Hi, I would create a unique token, based on the users fingerprint (user agent, ip address, etc) and store it in the database on login. Then lock logins to a time window, for example 5 minutes, so you cannot login again while there is another recent login with a different fingerprint in the db. Thanks,

**Comment by joserafael** [comment]
Thank you @steinkel I will override the function login
