### ISSUE TITLE
uuid NULL with Sqlite driver

### ISSUE THREAD

**Issue by kevinliteon** [CakeDC/users#620]
When i add a superadmin with cli and Sqlite driver: 
```
bin/cake users add_superuser -u superadmin -p superadmin
Superuser added:
Id: 1
Username: superadmin
Email: superadmin@example.com
Role: superuser
Password: superadmin
```
uuid is not generated and i get a null:
![screenshot_20171009_111448](https://user-images.githubusercontent.com/3115254/31331557-1570df80-ace3-11e7-93ed-dfe0f7d5a9bd.png)

its seems a problem with migration plugin (phinx?), it generate a id without length for id

```
CREATE TABLE users
(
  id              CHAR
    PRIMARY KEY,
  username        VARCHAR(255),
  email           VARCHAR(255),
  password        VARCHAR(255),
  first_name      VARCHAR(50),
  last_name       VARCHAR(50),
  token           VARCHAR(255),
  token_expires   DATETIME,
  api_token       VARCHAR(255),
  activation_date DATETIME,
  tos_date        DATETIME,
  active          BOOLEAN      DEFAULT 0 NOT NULL,
  is_superuser    BOOLEAN      DEFAULT 0 NOT NULL,
  role            VARCHAR(255) DEFAULT 'user',
  created         DATETIME,
  modified        DATETIME,
  secret          VARCHAR(32),
  secret_verified BOOLEAN
);

```
my versions: 
php                                         7.1
cakedc/auth                            2.0.2
cakedc/users                          5.2.0
cakephp/cakephp                   3.5.3
cakephp/migrations                1.7.1

**Comment by steinkel** [comment]
In this case you'll need to either specify `char(36)` on the id to let CakePHP know it's going to be an uuid or use an autonumeric int id to let the database generate the id for you...

**Comment by steinkel** [comment]
closing this one, let me know if you had any other issues. Thanks,
