### ISSUE TITLE
Q: How do i check if a user is logged in?

### ISSUE THREAD

**Issue by AsukaYuki** [CakeDC/users#633]
Hello everybody,
i feel stupid for asking this, but i want to check if a user is logged in. 
If true i want to add a menu item to my navbar.

```
<?php if ($this->User->isLoggedIn()) : ?>
    <li><?= $this->Html->link('Userarea', '/profile') ?>
        <ul>
            <li><?= $this->Html->link('Logout', '/logout')?></li>
        </ul>
    </li>
<?php endif; ?>

```

I thought there must be already a function in UserHelper.php to check this, but i didnt found one.

I copied a part from "welcome" and changed it a bit into:
```
    public function isLoggedIn(){
        $userId = $this->request->session()->read('Auth.User.id');
        if (empty($userId)) {
            return false;
        }
        return true;
    }
```
Is there somewhere a function which already does this? 
Have i overlook something?

**Comment by steinkel** [comment]
Hi, you can access the logged in user data via AuthComponent, check related documentation here https://book.cakephp.org/3.0/en/controllers/components/authentication.html#accessing-the-logged-in-user

Thanks,
