### ISSUE TITLE
permissions.php not read until logged in

### ISSUE THREAD

**Issue by sasilen** [CakeDC/users#634]
Probably again a stupid question, but I just don't get what happened. 

After some modification to my app or composer update, my Authentication stopped working. I have tried to install everything from the scratch using different CakeDC/Users repositories (dev-master, dev-develop, 5.2) But always situation is same.

Basically authentication works and after successful authentication everything works just like it should. But when I logout I cannot even read Pages/Display which should be allowed in the permissions.php. I can even mess up file so that it's not php syntax anymore, but there are no errors, no nothing untile I lok in (looks like file is not read when not logged in). After login I see that file is messed up.

How could I debug this kind of issue? Or is there something obvious what I have missed or doing wrong?

**Comment by steinkel** [comment]
What means "it should be allowed in permissions.php" keep in mind permissions.php only handles authorization AFTER the user is logged in, to enable public access on any of your actions use `AuthComponent::allow` function. Thanks,
