### ISSUE TITLE
Advice on unit testing: how to mock logged in state

### ISSUE THREAD

**Issue by emersonthis** [CakeDC/users#635]
Great plugin!
I just got it up and running in my app. I'm still tinkering with the configurations, but one thing I notice immediately is that some of my page tests written before the plugin now fail because the response codes changed to redirects (for auth). At some point I'll need a way to simulate a logged-in user state. What's the recommended way to do this?

**Comment by steinkel** [comment]
Thank you!
You can take a look at mocking the auth component in the book https://book.cakephp.org/3.0/en/development/testing.html#testing-actions-that-require-authentication and grab some example code from there...
