### ISSUE TITLE
Unable to override the Controller

### ISSUE THREAD

**Issue by rajasinghroot** [CakeDC/users#636]
Dear Team,

I followed the given instructions to override the controller, But it's not working. Actually, all the time it's taking plugin controller only not considering overrides controller.

Extending the Controller

You want to use one of your controllers to handle all the users features in your app, and keep the login/register/etc actions from Users Plugin,

First create a new controller class:

<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Model\Table\MyUsersTable;
use Cake\Event\Event;
use CakeDC\Users\Controller\Component\UsersAuthComponent;
use CakeDC\Users\Controller\Traits\LoginTrait;
use CakeDC\Users\Controller\Traits\RegisterTrait;

class MyUsersController extends AppController
{
    use LoginTrait;
    use RegisterTrait;

//add your new actions, override, etc here
}
Don't forget to update the Users.controller configuration in users.php

    'Users' => [
        // ...
        // Controller used to manage users plugin features & actions
        'controller' => 'MyUsers',
        // ...
Note you'll need to copy the Plugin templates you need into your project src/Template/MyUsers/[action].ctp

Any suggestion, please?

**Comment by steinkel** [comment]
Could you please describe "it's not working" a bit more, please paste your current configuration file, your extended controller etc to be able to help you.

Thanks,

**Comment by steinkel** [comment]
Closing this one, please open a new ticket with some context we can use to help you in the future. Thanks,
