### ISSUE TITLE
UserTable Behaviors are not loading properly on fresh install

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#640]
The initialize method of the UsersTable does not seem to be executed...

I placed a die statement in the initialize method and it did not die...

Any ideas why that might be happening?

Using 
     CakePHP 3.5.8
     CakeDC\Users 6.0.0

**Comment by jeffreyroberts** [comment]
I have created a repo to demonstrate the issue at hand...

https://github.com/jeffreyroberts/CakeDC-Users-Behavior-Issue

**Comment by jeffreyroberts** [comment]
The above repo is fresh clone of cakephp/app, I then composer require cakedc/users, then I setup the app.php and /register route...

![screen shot 2017-12-16 at 11 46 04 am](https://user-images.githubusercontent.com/2320614/34072526-dd0482d8-e256-11e7-866c-e820d5dc9ffb.png)

**Comment by jeffreyroberts** [comment]
I must be doing something wrong, I have tried multiple versions of cakephp/cakephp and cakephp/app and I continue to get this error... I have a copy of this working in another project, so I dont understand why its not working in this one...

**Comment by jeffreyroberts** [comment]
I have also tried multiple versions of cakedc/users ...

**Comment by steinkel** [comment]
I just did a quick setup of a blank project and installed cakedc/users via composer + plugin load + AppController initialize and works correctly, could you share your current config?

About the repo, you don't have a UsersTable created under https://github.com/jeffreyroberts/CakeDC-Users-Behavior-Issue/tree/master/src/Model/Table and you are specifying a custom UsersTable in your config/users.php file, so the problem with missing features... either remove that line in your users.php config or add a custom UsersTable to fix it.

Thanks,

**Comment by jeffreyroberts** [comment]
@steinkel Thank you so much
