### ISSUE TITLE
Docs for implementing ACL with Rbac on Users plugin

### ISSUE THREAD

**Issue by rudy1976s** [CakeDC/users#641]
Hello
I need to be able to have multiple roles for users: mt scenario is pretty like a newspaper redaction where there are different roles which can be playued by same person: an author of a specified matter could be redactor of one another and so on.
Could you please write some docs to how to ?
Thank you

Rudy

**Comment by rogerpro** [comment]
Hi @rudy1976s . I'll write a howto about this topic and then publish the link here. Greetings,

**Comment by rogerpro** [comment]
Here's the article, @rudy1976s:

https://www.cakedc.com/roger_campanera/2018/01/26/integrating-users-and-acl-plugins-in-cakephp

I hope it will help :)

**Comment by ugurcanb** [comment]
Sorry to bring the issue to surface again i think blog post should be updated to work with Cakephp4 and latest version of the plugin.
