### ISSUE TITLE
Can not overwrite messages when session timeout.

### ISSUE THREAD

**Issue by TAECakeDC** [CakeDC/users#645]
We have been config session timeout [1 minute] under cake 3.x, after session timeout we can not overwrite message [CakeDC Users] shown screen login form.

This is Bug or missing config.

Thanks.

**Comment by steinkel** [comment]
hi @TAECakeDC are you related with CakeDC? I don't remember you from our company channel :open_mouth: 

Regarding your session issue, keep in mind the logged in user, and the flash messages are stored in the Session. Once the session expires this reference is lost and you can't access it from the following requests...
