### ISSUE TITLE
Remember me checked but cant have persistent session after social login 

### ISSUE THREAD

**Issue by blackstar-7** [CakeDC/users#648]
persistent session worke fine when i logged in with email and password 
but when i use facebook or  google i lost my session once i close my browser 
i have the remember me cookie active and checked 
in my login page : 
```
   if (Configure::read('Users.RememberMe.active')) {
                           
      echo $this->Form->control(Configure::read('Users.Key.Data.rememberMe'), [
      'type' => 'checkbox',
       'label' => __d('CakeDC/Users', 'Remember me'),
       'checked' => Configure::read('Users.RememberMe.checked')
             ]);
                                    
    } 

```
in my users.php : 

```
        'RememberMe' => [
            // configure Remember Me component
            'active' => true,
            'checked' => true,
            'Cookie' => [
                'name' => 'remember_me',
                'Config' => [
                    'expires' => '1 month',
                    'httpOnly' => true,
                ]
            ]
        ],
```
can anyone help me please

**Comment by steinkel** [comment]
Hi @blackstar-7 what you would expect from remember-me in this use case? Could you describe what's your expected behavior?

Thanks,

**Comment by blackstar-7** [comment]
well i want to have a persistent session after the user logged in using social login 
so next time when he visite the app he dont have to click on "sign in with facebook / google"
is not that what remember_me is for ?!

**Comment by rogerpro** [comment]
May be fixed by https://github.com/CakeDC/auth/pull/20

**Comment by steinkel** [comment]
Please reopen if not fixed by the suggested PR
