### ISSUE TITLE
can not redirect pages/view after loading $this->loadComponent('CakeDC/Users.UsersAuth')

### ISSUE THREAD

**Issue by sunil-makwana008** [CakeDC/users#649]
i have installed cake php then i have installed cakeDC/users.
i have load component in app controller.
now i can not go to pages/view on '/' it redirects to '/login'
in default SimpleRbac pages/view is allowed to all then why i can't redirect to '/' to 'pages/view' ?
what is the problem ?

**Comment by steinkel** [comment]
Hi @sunil-makwana008 keep in mind authorization != authentication. The rules you are writing in permissions.php are configuring the RBAC Authorization, this happens AFTER authentication so you need a logged in user. If you want a page accessible by not logged in users you need to tell CakePHP to bypass authentication, via https://book.cakephp.org/3.0/en/controllers/components/authentication.html#making-actions-public
