### ISSUE TITLE
How do you apply table relationships to the plugin's UserTable Model

### ISSUE THREAD

**Issue by Juergen-Airscout** [CakeDC/users#653]
Prior to attempting to use this plugin I had a simplistic User Table with no controller outlining the associations between the user table and the other models. After installing the plugin I started running into issues with CakePHP stating that the "Users is not associated with Organizations". Long story short I found that if I add my table relationships to the plugin UserTable.php it started working again. So it appeared that my model was either not being used or being overridden. it's bad practice to modify a plugin directly so I started looking into extending the plugin. I did not want to change the table name but unfortunately, the model kept looking for a table that matched the model name. I am out of ideas at this stage and I am wondering what I'm missing. Attached are the relevant portions of code.

My original user model
UsersTable.php
```
<?php
// src/Model/Table/UsersTable.php
namespace App\Model\Table;

use Cake\ORM\Table;

class UsersTable extends Table
{
    public function initialize(array $config)
    {
        $this->addBehavior('Timestamp');

        //link the users table to the flights (pilot) table
        $this->hasMany('PilotFlights', [
                'className' => 'flights'
            ])
            ->setForeignKey('pilot_user_id');
        //link the users table to the flights (observer) table
        $this->hasMany('ObserverFlights', [
                'className' => 'flights'
            ])
            ->setForeignKey('observer_user_id');
        //link the users table to the organizations table
        $this->belongsTo('organizations');
        //link the users table to the organization_type_data_collectors table
        $this->hasMany('organization_type_data_collectors')
            ->setForeignKey('point_of_contact_user_id'); 
    }
}

```
The model I attempted to build to extend the plugin's User model
ManageUsersTable.php
```
<?php
// src/Model/Table/UsersTable.php
namespace App\Model\Table;

use CakeDC\Users\Model\Table\UsersTable;

class ManageUsersTable extends UsersTable
{
    public function initialize(array $config)
    {
        //link the users table to the flights (pilot) table
        $this->hasMany('PilotFlights', [
                'className' => 'flights'
            ])
            ->setForeignKey('pilot_user_id');
        //link the users table to the flights (observer) table
        $this->hasMany('ObserverFlights', [
                'className' => 'flights'
            ])
            ->setForeignKey('observer_user_id');
        //link the users table to the organizations table
        $this->belongsTo('organizations');
        //link the users table to the organization_type_data_collectors table
        $this->hasMany('organization_type_data_collectors')
            ->setForeignKey('point_of_contact_user_id'); 
    }
}
```

Additionally, for some reason, I am having issues with the UserHelper ... the links only work on the root page but on none of the controller pages.

Thanks

**Comment by martonmiklos** [comment]
I am facing with the same problem (exactly both the Model both the links) so if you have any solution please let me know. Thanks in advance!

**Comment by rochamarcelo** [comment]
@martonmiklos @Juergen-Airscout please refer to  https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md

Pass the new table configuration to Users Plugin Configuration
config/bootstrap.php

Configure::write('Users.config', ['users']);
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
Then in your config/users.php

return [
    'Users.table' => 'MyUsers',
];
