### ISSUE TITLE
Extending the Controller

### ISSUE THREAD

**Issue by notom** [CakeDC/users#655]
Hey guys,

So, I followed the steps in the document [here](https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md), but with no luck. The problem is that the login form still uses the UserController instead of the custom one.

Here is my user.php config file:
```
return [
    'Users.controller' => 'MyUsers',
```

And my bootstrap:

```
Configure::write('Users.config', ['users']);
Plugin::load('CakeDC/Users', ['routes' => true , 'bootstrap' => true]);
Configure::write('Users.Token.expiration', 86400); // 24h
```

I also tried composer `dump-autoload` and `cake cache clear-all` after I set the new controller.

**Comment by notom** [comment]
Here is my custom controller:
```
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use CakeDC\Users\Controller\Component\UsersAuthComponent;
use CakeDC\Users\Controller\Traits\LinkSocialTrait;
use CakeDC\Users\Controller\Traits\LoginTrait;
use CakeDC\Users\Controller\Traits\ProfileTrait;
use CakeDC\Users\Controller\Traits\ReCaptchaTrait;
use CakeDC\Users\Controller\Traits\RegisterTrait;
use CakeDC\Users\Controller\Traits\SimpleCrudTrait;
use CakeDC\Users\Controller\Traits\SocialTrait;

class MyUsersController extends AppController
{
    /*use LinkSocialTrait;
    use LoginTrait;
    use ProfileTrait;
    use ReCaptchaTrait;
    use RegisterTrait;
    use SimpleCrudTrait;
    use SocialTrait;*/

    public function login()
    {
        var_dump("TEST");
        die();
    }
}
```

So, I'm expecting error or at least a "TEST" and nothing more when I try to login.

**Comment by steinkel** [comment]
Note you are still using AuthComponent, if you really want to access this login action, ensure you disable AuthComponent OR set this action as allowed.

You have a complete source code example here https://c9.io/steinkel/users-example-custom-table

**Comment by malikperang** [comment]
Hi @steinkel , I have the same issue eventhough I'd remove the AuthComponent class.
Plus I got this error as well `' Undefined property: UsersController::$Auth in /var/www/cakephp/vendor/cakedc/users/src/Controller/Traits/LoginTrait.php on line 192 '`.

what's your advice?

Thanks

**Comment by steinkel** [comment]
Please gist your code and related configuration.

**Comment by malikperang** [comment]
What I did just now is  baked a plugin named UserAcl and follows the instructions given  here:
https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md

below is my gist
https://gist.github.com/malikperang/a1cabfabc1ef08c57ef6720e9043b3b0
@steinkel

**Comment by steinkel** [comment]
It looks like your base controller is not loading the UsersComponent (so not loading the AuthComponent)

**Comment by steinkel** [comment]
the controller is inside a plugin?

**Comment by malikperang** [comment]
yes @steinkel

**Comment by steinkel** [comment]
then controller name should be Plugin.ControllerName but I'm not sure it's going to work in this case, please test it and let me know to take a look if not working properly, thanks!
