### ISSUE TITLE
Configuration not properly loaded in config/users.php

### ISSUE THREAD

**Issue by rogerpro** [CakeDC/users#656]
After copying the default config to the app with `cp vendor/cakedc/users/config/users.php config/` it's supposed that all keys can be overrided.

But this is not working when trying not to use some authentication and authorization methods.

For instance, with a `config/users.php` file as:
```
$config = [
    'Auth' => [
        'authenticate' => [
            'all' => [
                'finder' => 'auth',
            ],
            'CakeDC/Auth.RememberMe',
            'Form',
        ],
        'authorize' => [
            'CakeDC/Auth.SimpleRbac',
        ],
    ],
];

return $config;
```

When debugging within the app we'll notice that some other objects are included in `AuthComponent::_authenticateObjects` and `AuthComponent::_authorizeObjects` (i.e. `CakeDC/Auth.ApiKey`, `CakeDC/Auth.Superuser`).

One workaround is to config it in `config/bootstrap.php` with:
```
Configure::write('Auth.authenticate', [
    'all' => [
        'finder' => 'auth',
    ],
    'CakeDC/Auth.RememberMe',
    'Form',
]);

Configure::write('Auth.authorize', [
    'CakeDC/Auth.SimpleRbac'
]);
```

It works, but I think people is confident with setting all config in `config/users.php`.

This may be caused by an `unset()` inside a `foreach` when loading app config.

As an additional issue, this works in `config/bootstrap.php` but not in `config/bootstrap.local.php`

Thanks @rochamarcelo for reporting.

**Comment by steinkel** [comment]
I'm afraid this is the way it works for auth, the keys get merged and previous keys are preserved in the auth object configuration.
