### ISSUE TITLE
Change the emailFormat of the forgot password emails

### ISSUE THREAD

**Issue by martonmiklos** [CakeDC/users#664]
First of all thank you very much for this plugin it helps me a lot!

I have not found any way to specify in which format should the forgot password e-mails sent. 

I would propose to introduce a new configuration subkey Mailer and add an emailFormat subkey to it. 
Or if I have missed the possibility of configuration please let me know.

**Comment by steinkel** [comment]
Hi @martonmiklos we have specific docs covering how to customize emails sent here https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md#updating-the-emails thanks!

**Comment by martonmiklos** [comment]
Hey,
Thank you and I apologise for missing it!
