### ISSUE TITLE
Extending model / Change users table

### ISSUE THREAD

**Issue by rfhsorna** [CakeDC/users#666]
Hi all,

I have a problem extending the model, respective changing the users table. 

I followed the instructions from docs: https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md

My configuration looks like:

**bootstrap.php:**
```
Configure::write('Users.config', ['users']);
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
```

**config/users.php:**
```
return [
'Users.table' => 'HcpUsers'
];
```

**src/Model/Entity/HcpUsers.php:**
```
<?php

namespace App\Model\Entity;

use CakeDC\Users\Model\Entity\User;

class HcpUsers extends User
{

}
```
**src/Model/Table/HcpUsersTable.php:**
```
<?php

namespace App\Model\Table;

use CakeDC\Users\Model\Table\UsersTable;

/**
* Users Model
*/
class HcpUsersTable extends UsersTable
{
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->setTable('hcp_users');
    }
}
```

Actually, it's working fine, but when trying to reset a users password, I always get the following error:
```
 Call to undefined method Cake\ORM\Entity::updateToken() 
 Error in: ROOT/vendor/cakedc/users/src/Model/Behavior/PasswordBehavior.php, line 70
```

If I change configuration back to default users table (CakeDC/Users.Users), it's working....

Does anybody knows, how to get rid of this error? I'm already desperate... 

And why is it needed, to set the table in src/Model/Table/HcpUsersTable.php once more? I thought, setting it in config/users.php should be enough?

Thanks!

**Comment by rochamarcelo** [comment]
Entities classes names are singular PascalCased, so in your case, is HcpUser not HcpUsers
