### ISSUE TITLE
JSON View

### ISSUE THREAD

**Issue by viniciusbig** [CakeDC/users#674]
Hello, 

This is not an issue with the plugin I guess, but I've looked for an answer and I couldn't find the correct way to do this. (sorry to open this here)

I'm overwriting the index.ctp with my own layout and I have a data table using javascript to get data from the backend in an AJAX request (I have copied index.ctp to my theme plugin).

So I would like to get data in the index controller in a JSON format. How can I accomplish that using the CakeDC/Users plugin?

Do I have to add the `$this->loadComponent('RequestHandler');` line in the controller, right? Where can I add this?

Does anyone have an example or a tip to show me the right way?

Thanks in advance,

**Comment by rochamarcelo** [comment]
Hi @viniciusbig ,

You need to enable data views in you app controller and enable json extenson in your routes.php file.

Enable json extenson in your routes.php

Router::scope('/users', function ($routes) {
    $routes->setExtensions(['json']);
});

Enable data views in your AppController

```
public function initialize()
{
    $this->loadComponent('RequestHandler');
} 
```

Now you can access the actions with json extension in ajax request, something like /users/users.json

You could also get help at:

http://telegram.me/cakephpbr
https://cakesf.slack.com

**Comment by impronta48** [comment]
Hi @rochamarcelo , 
do you think this will work also for 9.0? 
I've tried but I always get

http://kbc.drupalvm.test/users/users.json
The action users.json is not defined in UsersController

http://kbc.drupalvm.test/users/index.json
The action index.json is not defined in UsersController

What am I doing wrong?
Thanks
Massimo
