### ISSUE TITLE
About user id format

### ISSUE THREAD

**Issue by parobit** [CakeDC/users#675]
Hello everybody,

I am very grateful if you could explain me why User ID column has format CHAR(36) like this
`c5447c81-393f-4cf1-ba03-dd476c70898d` and not normal interger.

**Comment by medero** [comment]
I would guess maybe so it forces people to really update the schema as integer would be more commonly used, otherwise people would be less inclined to look at the schema?

**Comment by steinkel** [comment]
You can guess the id of an user if using integers, but uuids are much harder to guess.
