### ISSUE TITLE
Fixtures not autloaded correctly.

### ISSUE THREAD

**Issue by makakken** [CakeDC/users#676]
I'm experiencing Problems using Fixtures in Test Cases in my App using the __'plugin.CakeDC/Users.users'__ Fixture.

Is it possible there is a Bug in the autoloader?

```
"autoload-dev": {
        "psr-4": {
            "CakeDC\\Users\\Test\\": "tests",
            "CakeDC\\Users\\Test\\Fixture\\": "tests"
        }
    }
```

Should'nt it be "CakeDC\\Users\\Test\\Fixture\\": "tests **/Fixture**" ???

**Comment by rochamarcelo** [comment]
This should not be an issue, but if you're using the plugin fixtures in your model test class you will need to add the following to your composer file: "CakeDC\\Users\\Test\\": "./vendor/cakedc/users/tests"
