### ISSUE TITLE
CakeDC Users Reset Password Permission Denied

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#680]
I am using the following for permissions for reseting a password, however, i am still getting permission denied...

    [
        'role' => '*',
        'controller' => ['Users'],
        'plugin' => 'CakeDC/Users',
        'action' => ['resetPassword'],
        'allowed' => true
    ]

Is this correct?

**Comment by steinkel** [comment]
In this case, check debug.log output, it will list the action denied, you can compare youru controller, plugin, etc coming from the request params and match them using a rule, for example:

```
2017-12-01 18:45:39 Debug: For {"prefix":null,"plugin":null,"extension":null,"controller":"Posts","action":"view","role":"user"} --> Rule matched {"role":["user"],"controller":["Posts"],"action":["view"],"bypassAuth":true,"allowed":true} with result = 1

**Comment by jeffreyroberts** [comment]
It's not creating a log entry

**Comment by jeffreyroberts** [comment]
![screen shot 2018-05-29 at 4 10 50 pm](https://user-images.githubusercontent.com/2320614/40682979-2a8b9b92-635b-11e8-90f6-54ddbf32d690.png)
![screen shot 2018-05-29 at 4 10 59 pm](https://user-images.githubusercontent.com/2320614/40682981-2a9f8e68-635b-11e8-9e8e-ed550684d5f9.png)
![screen shot 2018-05-29 at 4 11 06 pm](https://user-images.githubusercontent.com/2320614/40682982-2ab222d0-635b-11e8-85c8-86b5915f71cd.png)

**Comment by jeffreyroberts** [comment]
My apologies, I was serving the site from a different machine, and didnt even realize it...
