### ISSUE TITLE
What does overriding the Users.controller do exactly?

### ISSUE THREAD

**Issue by dondosh** [CakeDC/users#687]
I'm not sure what is does, because even without changing the configuration value, I can use my own controller and applying trait from the plugin.

Do using routes from the plugin, it should use my custom controller action?

My problem is that /users/users/view/{id} is still accessible when I override it in my controller. /myusers/view/{id}.

There something I don't understand.

**Comment by steinkel** [comment]
The "Users.controller" config param is mainly used here > https://github.com/CakeDC/users/blob/master/src/Controller/Component/UsersAuthComponent.php#L119
To provide a set of allowed actions for required actions.

If you want to restrict access to the plugin controllers, remove the `'routes' => true` option from `Plugin::load` and configure your required routes from your application. You can also remove loading of plugin routes to remove basic plugin based routes.
