### ISSUE TITLE
permissions config loading

### ISSUE THREAD

**Issue by AokuYuki** [CakeDC/users#690]
**My problem:**
I get flash message "You are not authorized to access that location." in my controller.
If i set `$this->Auth->allow() `inside the controller, i can access it. 
But this controller should not be public. Only logged in users may access it.
But as soon as i set `$this->Auth->deny()`  or leave it, i get the flash error message.

Registration and login works fine.
I can access pages from: `src/Controller/PagesController.php `

**What i did**
1 composer require cakedc/users
2 created the tables
3 loaded the plugin:
```
Configure::write('Users.config', ['users']);
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
```
4 loaded the component in my src/Controller/AppController.php: 
`$this->loadComponent('CakeDC/Users.UsersAuth');`

**Found the Problem source!**
The config file `permissions `was not loaded. I dont know if the plugin should load it itself or if its just my fault for forgetting to load it. 
In the documentation i did not see any hint for manually loading it.
My `config/permissions.php` looks now like this.

```
...
Configure::write('Users.config', ['users']);
Configure::load('permissions');
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
```
 Edit:
I think i know where i made my error and why the config permissions didnt get loaded. 
I loaded the `$this->loadComponent('CakeDC/Users.UsersAuth', $config);` with wrong configs.
After loading it without any config it loads the permissions just fine.

**Comment by steinkel** [comment]
Thank you for updating the issue with the solution!
