### ISSUE TITLE
Creation of an afterRegisterConfirm

### ISSUE THREAD

**Issue by rudy1976s** [CakeDC/users#696]
It would be extremely useful to have an afterRegisterConfirm event to be fired when user validate registration by clicking the link sent by email.
There should be a lot of activities to be set just for **one time** when people confirm registration: setup storage accounts, setup several stuffs, without the need to carry the afterLogin events with checking logics that would add unuseful  workload at that time.
The afterLogin is fired often, and adding logic there would need to setup further logic to determine if the above mentioned activities have already been set up.

**Comment by steinkel** [comment]
I agree, this would be a good one to add...

**Comment by rudy1976s** [comment]
Any news regarding this feature ?

**Comment by steinkel** [comment]
Not yet, as we're working on the refactor to use cakephp/authentication now, once we finish the refactor we'll pick new features to add to the new version. Thanks,

**Comment by rudy1976s** [comment]
Thank you !!

**Comment by steinkel** [comment]
closed per #937
