### ISSUE TITLE
Google reCaptcha configuration

### ISSUE THREAD

**Issue by rudy1976s** [CakeDC/users#707]
Could ypu please provide more Google reCaptcha configuration options? it could be very useful add the following options to parameters:

- data-theme
- data-size
- data-tab-index

**Comment by chokri** [comment]
Hi, I did some changes by adding data-theme, data-size and data-tab-index here
https://github.com/CakeDC/users/commit/e347871a092c8572e9fa01619a02cbb167bc1e27#diff-9b9616b739357f078c99e315e3e43cd9L149

**Comment by steinkel** [comment]
merged into develop, thank you!
