### ISSUE TITLE
Resend token validation unexpected email sent

### ISSUE THREAD

**Issue by eniacom** [CakeDC/users#714]
Hi,
we try to use action below to receive a new validation token to confirm activation account but we receive reset password email insted

` ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'resendTokenValidation'] `

I try to fix it:
in user/src/Controller/Traits/UserValidationTrait.php we use this (at line 91, 92)

` // get user from users table
$user = $this->getUsersTable()->findByUsernameOrEmail($reference, $reference)->first();
            if ($this->getUsersTable()->resendValidationEmail($user, [ // invoke resendValidationEmail instead resetToken
                'token_expiration' => Configure::read('Users.Token.expiration'), // pass token_expiration argument requested by resendValidationEmail `

instead of

`if ($this->getUsersTable()->resetToken($reference, [
                'expiration' => Configure::read('Users.Token.expiration'),`

resetToken function invoke `sendResetPasswordEmail()` but we would like that:
1. register function should be send validation account email if requested by config
2. if user forgot password should be invoke requestResetPassword to obtain token to reset password
3. if user forgot to validate account should be invoke requestResetToken or requestValidationAccount (like you prefer) to obtain email with link for account validation

What do you think about?

Thank in advace.
Filippo

**Comment by steinkel** [comment]
We've grouped these 2 statuses (users not validated yet, and users resetting their password) for simplicity.

I understand the feature requested is to ensure the first email validation token workflow and status (including the emails sent) vs the reset password workflow are kept separated, so you can manage the events and copy of each email, right?

**Comment by jtraulle** [comment]
This is fixed by #685 in develop 😉

**Comment by steinkel** [comment]
closing per #685
