### ISSUE TITLE
Can I add a single entry in users table without extending the plugin ?

### ISSUE THREAD

**Issue by apirahim** [CakeDC/users#716]
I want to add a small entry to the Users table which is "Balance" (integer)

I read the extending part in the documentation and I honestly got dizzy from all the modifications that I have to do

I don't want to rewrite the whole thing just for a small entry, Is there anyway I can add it to the table with minumum modification or rename another entry that I don't need, like "tos_date" or something

**Comment by steinkel** [comment]
Yes, you can add extra columns to your users table, the only point here would be possibly overriding the templates to add the new columns in your forms...
