### ISSUE TITLE
Can login using Google, but not Facebook

### ISSUE THREAD

**Issue by fin-k** [CakeDC/users#720]
Please help, I can login using google but it fails when login with facebook. I tried to debug it and found on  ```function _createSocialUser($data, $options = [])``` when login with facebook $data variable has empty link: 
![image](https://user-images.githubusercontent.com/10423383/45307913-75997a00-b54a-11e8-8f76-b83ba86c1937.png)

And I found that this link is used in social_accounts table and it cannot be empty.

**Comment by cjbars** [comment]
Facebook no longer provides a link to the profile. As a temporary solution, I made a listener for the event 'Users.Component.UsersAuth.beforeSocialLoginUserCreate', and just fill the link with the # symbol.
I placed this code in the bootstrap:

```php
\Cake\Event\EventManager::instance()
    ->on(
        'Users.Component.UsersAuth.beforeSocialLoginUserCreate',
        function(Cake\Event\Event $event){
            $data = $event->getData('userEntity');
            array_map(
                function($item){
                    $item->link = ($item->link === null) ? '#' : $item->link;
                    return $item;
                },
                $data->social_accounts
            );
            return $data;
        }
    );
```

But this solution smells a little bit

**Comment by fin-k** [comment]
Ok thanks, it works.
