### ISSUE TITLE
Change domain names in PO files to 'cake_d_c/users'

### ISSUE THREAD

**Issue by steinkel** [CakeDC/users#730]
Fix the domain name in po files and templates to match the convention

**Comment by jtraulle** [comment]
For now, we have :
```
src/Locale/
├── ar_OM
│   ├── Users.mo
│   └── Users.po
├── es
│   ├── Users.mo
│   └── Users.po
├── fr_FR
│   ├── Users.mo
│   └── Users.po
├── hu_HU
│   ├── Users.mo
│   └── Users.po
├── it_IT
│   ├── Users.mo
│   └── Users.po
├── pl
│   ├── Users.mo
│   └── Users.po
├── pt_BR
│   ├── Users.mo
│   └── Users.po
├── sv
│   ├── Users.mo
│   └── Users.po
├── tr_TR
│   ├── Users.mo
│   └── Users.po
└── Users.pot
```

If I understand well, it should become :

```
src/Locale/
├── ar_OM
│   └── cake_d_c
│       ├── users.mo
│       └── users.po
└── cake_d_c
      └── users.pot
```

and so on ... or

```
src/Locale/
└── cake_d_c
       ├── ar_OM
       │   ├── users.mo
       │   └── users.po
       └── users.pot
```

and so on ... 

I concede I am a bit puzzled with the slash in the plugin name :P

If this is just about creating new directories and renaming po/mo files and pot catalogue, I can do that as a PR @steinkel

**Comment by steinkel** [comment]
Thank you!

We've already done that in a major refactor we're preparing to integrate with the new authentication plugins

We're doing review and docs and pushing it to develop soon...

**Comment by jtraulle** [comment]
Great :) Can't wait :P

**Comment by rochamarcelo** [comment]
Change done and merged into develop branch
