### ISSUE TITLE
Fail social auth

### ISSUE THREAD

**Issue by pablogupi** [CakeDC/users#736]
Hi!
I using this plugin and works fine in my project, excepts when login using Facebook or Google.
I publish my web and configure Facebook in Google apis. After logging in particular platform, when redirect to my site a timeout happens. Url stuck in https: //*****.es/auth/google? State = or https: //*/auth/facebook? Code =. Two minutes after, appears You are not athorized to access that location message. I upgrade plugin v7 to v8 and I try to quit all permissions, but not work.
What can happen? Thanks a lot

error.log 
Facebook
 Error: Error getting an access token / retrieving the authorized user's profile data. Error message: cURL error 7: Failed to connect to graph.facebook.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to graph.facebook.com port 443: Connection timed out 
Google
Error: Error getting an access token / retrieving the authorized user's profile data. Error message: cURL error 28: Connection timed out after 150000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 150000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by jtraulle** [comment]
Facebook Graph API may be unavailable from time to time.
Do you still have the issue ?
You can check the system status here : https://developers.facebook.com/status/dashboard/

**Comment by jtraulle** [comment]
Have you also checked that this is not related to a firewall issue ? Is your server allowed to make outgoing connections to port 443 ?

**Comment by pablogupi** [comment]
It was definitely because it is a restricted server. We had to enable communication with the Google and Facebook urls. In addition to opening https ports. Thank you!
