### ISSUE TITLE
CakeDC/users and new cakephp/authentication and cakephp/authorization middleware

### ISSUE THREAD

**Issue by jtraulle** [CakeDC/users#738]
Hi there,

Not really an issue but I was wondering what was your position about new [cakephp/authentication](https://github.com/cakephp/authentication) and [cakephp/authorization](https://github.com/cakephp/authorization) middleware now that they are released as stable.

How does your plugin will evolves with these new middleware ? Do you plan to make use of them in a future version/update ?

**Comment by steinkel** [comment]
We're working now on a major version using the new plugins, and also refactoring the social authentication and others. We're at the final stage of this change and will send it to develop branch soon...

**Comment by groovenectar** [comment]
Have there been a lot of roadblocks on this @steinkel ? I'm about to give the develop branch a look, see what's there and try to determine what can be added

**Comment by steinkel** [comment]
not really :) @rochamarcelo did most of the work with the new plugins, and we've been holding the release to use develop branch in a couple more internal projects to test it internally before release, but it's OK to use...

**Comment by groovenectar** [comment]
Yay, nice, thanks for the info @steinkel!
