### ISSUE TITLE
support for CakePHP 3.7

### ISSUE THREAD

**Issue by rrd108** [CakeDC/users#742]
I know this is just came out, but is there any scheduled day for support CakePHP 3.7?

**Comment by rrd108** [comment]
After downgrading to CakePHP 3.6 and all dependencies I am able to log in again.

**Comment by rrd108** [comment]
I am using email as the username field. At `FormAuthenticate.php` on line 60 the check fails.

**Comment by groovenectar** [comment]
Wow, so surprising the breaking changes from 3.6 to 3.7. Surely there is something unintended going on, some breaking changes that were not intended. I'm going to try downgrading to 3.6 as well and see if the routes work again

**Comment by rrd108** [comment]
I just get the normal `Username or password incorrect` error message like if the user mistypes the password. As I understand it is because `FormAuthenticate.php` do the comparison for the `username` and not for the `email`, so as username is not privided it always fail.

**Comment by arcmovex** [comment]
Hi,
I've tested this issue and found out that there is nothing wrong.
I'm able to login using username or email.
I only encountered deprecated warnings for the new implementation of plugins using src/Application.php.

I'm using CakePHP 3.7 and CakeDC/Users 8.0 with PHP version 7.2.13.

**Comment by groovenectar** [comment]
I think I found the issue in my case. I have been using it in a Vagrant instance. It seems that trying some various optimizations, such as enabling NFS, really made things wonky in the most seemingly random ways.

I just restored CakePHP 3.7, and did a composer update. I was having an issue then that was different than before, the webserver was timing out with no errors. When I disabled NFS, not only was the site loading, but now the login page is appearing. So now I'm not able to see what the errors were before.

Note that I also did a `composer update`. With that said, now I have no idea why it started working between something with Vagrant, or something with an update to composer.

**Comment by rrd108** [comment]
I can confirm the plugin works fine with CakePHP 3.7, however at least in my case the behavious is strange.

# Case 1
In my `bootstrap.php` I have the following
`Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);`
and in `app.php` I set `debug` to `false` than I can log in.

If I set `debug` back to `true` I can not log in.

# Case 2
In my `bootstrap.php` I replace `Plugin::load` as it is deprecated
`Application::addPlugin('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);`

If I set `debug` either to `true` or to `false`, I can not log in.

As I investigated it it seems that `LoginTrait` calls `AuthComponent`'s `identify` method, what calls its  `constructAuthenticate` method.

At `AuthComponent` line 851 is
`$authenticate = Hash::normalize((array)$this->_config['authenticate']);`

$this->_config['authenticate'] looks differently in the successful cases and in the unsuccessfull cases.

Unsuccessfull
```
[
 'Form' => ['fields' => ['username' => 'email']],
  'all' => ['finder' => 'auth', 'userModel' => 'AppUser'],
  0 => 'CakeDC/Auth.ApiKey',
  1 => 'CakeDC/Auth.RememberMe',
  2 => 'Form'
]
```
In this case `normalize` empties the array's `Form` tag.

Successfull
```
[
  'all' => ['finder' => 'auth', 'userModel' => 'AppUser'],
  0 => 'CakeDC/Auth.ApiKey',
  1 => 'CakeDC/Auth.RememberMe',
  2 => 'Form'
 'Form' => ['fields' => ['username' => 'email']],
]
```

**Comment by arcmovex** [comment]
Thanks for sharing the scenarios.
Did you use a custom user model?
The problem might be with your custom user model. I'm not sure but if the problem is about authentication then model might be the cause because it sanitize the data.

Might want to check if the original user model is working fine.

**Comment by rrd108** [comment]
Yes, I am using a custom user model, and it is the same what I used with CakePHP 3.6

```
<?php
namespace App\Model\Table;
use CakeDC\Users\Model\Table\UsersTable as CakeUsersTable;
use Cake\Validation\Validator;
use Cake\Core\Configure;

class AppUsersTable extends CakeUsersTable{

	public function initialize(array $config)
	{
		parent::initialize($config);
		$this->setDisplayField('email');
	}

	public function validationDefault(Validator $validator)
	{
		$validator = parent::validationDefault($validator);
		$username = Configure::read('Auth.authenticate.Form.fields.username');
		if ($username === 'email') {
			$validator->remove('username');
			$validator->allowEmpty('username');
		}
		return $validator;
	}
}
```

**Comment by rrd108** [comment]
Hm....

It seems this is an error in my setup. If I change the error level to `E_ALL & ~E_USER_DEPRECATED` I can log in on case-1 and can not login in case-2.

I like programming for this wtf moments. :D

**Comment by saeideng** [comment]
check log and see that you are receiving bellow warning or no
`Cannot modify header information - headers already sent by`

**Comment by rrd108** [comment]
Yes I got these errors.

**Comment by saeideng** [comment]
do you use latest debug_kit?
login works with session , and if you can not send a header , so you can not log-in 
debug_kit can catch all deprecation-warnings , so you should not see this warning on output

**Comment by saeideng** [comment]
use new style of loading a plugin

**Comment by rrd108** [comment]
I have the latest debugkti (3.17.0) installed.
If I set to the new way of loading plugin and change what you mentioned above I still can not log in.
But I am ok for now with this, so I close the issue.
