### ISSUE TITLE
Deprecation in 3.7.0

### ISSUE THREAD

**Issue by Xbirdfr** [CakeDC/users#745]
On fresh install, both cakephp and cakedc/users, got this on migrate : 

_[ ./bin/cake migrations migrate -p CakeDC/Users ]_

Deprecated Error: Plugin::bootstrap() is deprecated. This method will be removed in 4.0.0. -vendor/cakephp/cakephp/src/Core/Plugin.php, line: 173

**Comment by arcmovex** [comment]
Hi,
AFAIK, CakeDC is preparing a new version to support CakePHP ^3.7.*
I suggest to use the stable and supported versions of cakephp and cakedc/users for now. 
You can easily update both using composer later on.

**Comment by n0mad01** [comment]
config/bootstrap.php
`$this->addPlugin('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);`
