### ISSUE TITLE
I cannot accessing user registration pages and post-user-registration pages 

### ISSUE THREAD

**Issue by okaprinarjaya** [CakeDC/users#747]
Hi,

For example, i can't access :
 -  `/users/users/request-reset-password` 
 -  `/users/users/register`
and other pre and post user's registration things pages
because of these lines of code
lines: 122 to 125.

https://github.com/CakeDC/users/blob/master/src/Controller/Component/UsersAuthComponent.php#L122-L125 i don't understand what the purpose of checking equality of plugin and controller? You know, if i remove these lines of code:

```
 list($plugin, $controller) = pluginSplit(Configure::read('Users.controller'));
 if ($this->getController()->getRequest()->getParam('plugin', null) === $plugin &&
$this->getController()->getRequest()->getParam('controller') === $controlle) {
```

ALL of those pages can be accessed! 

Notes: I change the default users controller to my custom controller by following this tutorial: 
https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md#extending-the-controller

Please help me. 

Thank you :)

**Comment by rochamarcelo** [comment]
If you are using a custom controller you should access /my-custom-users/register.

**Comment by saeideng** [comment]
in `users.php` use/set like :point_down: 
```php
    'Users' => [
        // ...
        // Controller used to manage users plugin features & actions
        'controller' => 'PLuginName.MyUsers',
```
