### ISSUE TITLE
jQuery Ajax Request Returns UsersHelper Could Not Be Found

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#751]
I have the following Javascript

    <script>
        function postToGallery(plate_id, gallery_id, comment) {
    
            var json_arr = {};
            json_arr["plate"] = plate_id;
            json_arr["gallery"] = gallery_id;
            json_arr["comment"] = comment;
            json_arr["_Token"] = "<?= $this->request->getParam('_csrfToken') ?>";
    
            var data = JSON.stringify(json_arr);
            var loading = $("#a-gallery-loader");
            var closeLoader = $('#close-gallery-loader');
    
            $(document).ajaxStart(function () {
                loading.click();
            });
    
            $(document).ajaxStop(function () {
                closeLoader.click();
            });
    
            $.ajax({
                type: "POST",
                headers: {
                    "X-CSRF-Token": "<?= $this->request->getParam('_csrfToken') ?>"
                },
                dataType: 'json',
                url: "/research_station/gallery/add",
                data: data,
                processData: false,
                success: function(msg) {
                    $("#success-modal").click();
                }
            });
        }
    </script>

Then I have the following Controller Action

    public function galleryAdd() {
        if($this->request->getMethod() != "POST") {
            return $this->redirect('/research_station/');
        }
        $plate_id = $this->request->getData('plate');
        $gallery_id = $this->request->getData('gallery');
        $this->render('ajax', 'ajax');
    }

When I set the datatype: 'json', in the above javascript, I get the following error

{
    "message": "Helper class UsersHelper could not be found.",
    "url": "\/research_station\/gallery\/add",
    "code": 500,
    "file": "\/var\/www\/html\/app\/vendor\/cakephp\/cakephp\/src\/View\/HelperRegistry.php",
    "line": 127
}

If I remove the datatype of json, the error goes away...

I put a die statement in at different locations in the controller action, and it seems that the $this->render method is the one looking for the UsersHelper for some reason...

Any ideas on what I am doing wrong?

**Comment by rochamarcelo** [comment]
Hi @jeffreyroberts,

Have you solved this? You need to make sure Users helper is loaded inside your AjaxView class.
