### ISSUE TITLE
Username or password is incorrect

### ISSUE THREAD

**Issue by motsmanish** [CakeDC/users#756]
CakePHP 3.6
CakeDC/Users: 8.0

When the plugin is loaded in bootstrap, it works fine.
`Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);`

But gives incorrect username password error when loaded in Application.php
`$this->addPlugin('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);`

**Comment by igorfelluga** [comment]
same here, look like if you set 
`Configure::write('Auth.authenticate.Form.fields.username', 'email');`
it doesn't take, I tried to set it in mu users.php
`    'Auth' => [
        'authenticate' => [
            'Form'=>[
	            'finder'=>'auth',
                'fields'=>['username'=>'email']
            ]
        ],
        'storage' => [
	        'className' => 'Session',
	        'key' => 'Auth.User'
        ]
    ],`
no way, I setted in users.php of plugin and it's work

**Comment by steinkel** [comment]
How are you loading your custom configuration? try debugging your custom configuration file to ensure it's being loaded...

**Comment by igorfelluga** [comment]
it's loaded because I use MyUsers for some custom fields and I debugged to be sure 200%

**Comment by steinkel** [comment]
Could it be another part of your configuration overriding this value later on?
Check the applied configuration here > https://github.com/CakeDC/users/blob/master/src/Controller/Component/UsersAuthComponent.php#L119

Also, another path to debug this issue is to set the `Users.auth` key to `false` and load AuthComponent yourself in your AppController, right before loading UsersComponent, and set your desired configuration.

Thanks,

**Comment by motsmanish** [comment]
Btw, the issue I raised is not related to the issue raised by another dev.

**Comment by igorfelluga** [comment]
Sorry for delay but I was busy in another project.
I tested and configuration looks ok. I tried many times enabling 
`Configure::write('Auth.authenticate.Form.fields.username', 'email');`
login not work, when I comment out it it's work correctly and it take configuration from my users.php.

I tried too enable 
`Configure::write('Auth.authenticate.Form.fields.username', 'email');`
and debug configuration in https://github.com/CakeDC/users/blob/master/src/Controller/Component/UsersAuthComponent.php#L119 looks ok but not login.

**Comment by rochamarcelo** [comment]
At Application::bootstrap you need to add: 
``
        $this->addPlugin(\CakeDC\Users\Plugin::class);
        Configure::write('Users.config', ['users']);

```

**Comment by wawanabnan** [comment]
I wonder I follow installation step but can't login cause username and password is incorrect.
Sure I add below code in application.php

$this->addPlugin(\CakeDC\Users\Plugin::class);
        Configure::write('Users.config', ['users']);

Would you please help me?

**Comment by rochamarcelo** [comment]
@wawanabnan Please provide the steps you have done to install, and include the added codes; also have you used the plugin migrations and how have you created users.

You should be able to create a new issue to discuss this

**Comment by rochamarcelo** [comment]
@wawanabnan please post your config/users.php (replace any sensitive information with **** ) probably something wrong with your config file.

**Comment by wawanabnan** [comment]
@rochamarcelo yes, I follow your instruction and the problem is in config/users.php. I copied the users config from project where I use social login (google Auth).

Case close, many thank for your guide.
