### ISSUE TITLE
U2fTrait is now a hard dependency

### ISSUE THREAD

**Issue by TekkCraft** [CakeDC/users#765]
The [following change](https://github.com/CakeDC/users/commit/73518c7a028c8af3e17d4c5a3cc2b3d14aa25436#diff-cb81d2cce7b484b8094f8a71bccad184R189) made it necessary to add the U2fTrait to one's UsersController, which makes it kind of a hard dependency.

Since we do not use U2f authentication, I would like to be not forced to add this in my code.

**Comment by steinkel** [comment]
That sounds reasonable to me, we'll remove the hard requirement in our next release

**Comment by ravage84** [comment]
Thanks, @steinkel 
For anybody looking for a solution, the error we encountered was:

> "Method '**getU2fAuthenticationChecker**' not found in class", or something like that.

**Comment by rochamarcelo** [comment]
Closing since we have a pull request for this.

Thank you.
