### ISSUE TITLE
url double users, why?

### ISSUE THREAD

**Issue by udarts** [CakeDC/users#771]
I just started using this plugin and it looks promising, I do have one question, why is there a double users in the url?
For example: users/users/register

That doesn't make sense. Am I missing something or could this be done better?

**Comment by saeideng** [comment]
`users/users/register`
first `users` is your plugin path
and second if your controller name 

https://github.com/CakeDC/users/blob/62996ca21accddb328ad799e2fb29d8c345998ac/config/routes.php#L14-L16
