### ISSUE TITLE
Update social avatar

### ISSUE THREAD

**Issue by NabilSnigdho** [CakeDC/users#802]
If the profile pic is changed in the social account, is the avatar url is updated(after login) in users table? I don't think it is(can't find something like that in codes). Wheather updated or not how to force update the avatar link?

**Comment by rochamarcelo** [comment]
Social account is not updated. For now you could override the socialLogin method in your custom UsersTable model.

**Comment by rochamarcelo** [comment]
Sent pull request: https://github.com/CakeDC/users/pull/805
