### ISSUE TITLE
Cannot use reCaptcha

### ISSUE THREAD

**Issue by amontrope** [CakeDC/users#810]
The login and register pages show a URL mismatch error when submitting with reCaptcha enabled.

**Comment by steinkel** [comment]
Please could you refer which version are you using and what's your current configuration for recaptcha (hide the keys)? Thanks,

**Comment by amontrope** [comment]
### Versions
_cakedc/users_: 8.4.0
_cakephp/cakephp_: 3.8.1
_google/recaptcha_: 1.2.2

### Configs
_registration_: true
_login_: true
_theme_: dark

**Comment by amontrope** [comment]
I think the issue is unlocking the response field in the User helper rather than in the template.

**Comment by checkmatesolo** [comment]
checkmatesolo

---------- Forwarded message ---------

**Comment by amontrope** [comment]
Does this mean I guessed right?

**Comment by rochamarcelo** [comment]
@amontrope have you solved this issue? It seems you not accessing the same URL you configure in 
https://www.google.com/recaptcha

**Comment by amontrope** [comment]
@rochamarcelo kind of. I got around the issue by unlocking the "g-recaptcha-response" field on the form and removing it from the User helper. So on the register page it looks like
```php
      if (Configure::read('Users.reCaptcha.registration')) {
        echo $this->User->addReCaptcha();
        $this->Form->unlockField('g-recaptcha-response');
      }
```
and the helper looks like 
```php
namespace CakeDC\Users\View\Helper;

class UserHelper extends Helper
{
    public function addReCaptcha()
    {
        if (!Configure::read('Users.reCaptcha.key')) {
            return $this->Html->tag('p', __d('CakeDC/Users', 'reCaptcha is not configured! Please configure Users.reCaptcha.key'));
        }
        $this->addReCaptchaScript();

        return $this->Html->tag('div', '', [
            'class' => 'g-recaptcha',
            'data-sitekey' => Configure::read('Users.reCaptcha.key'),
            'data-theme' => Configure::read('Users.reCaptcha.theme') ?: 'light',
            'data-size' => Configure::read('Users.reCaptcha.size') ?: 'normal',
            'data-tabindex' => Configure::read('Users.reCaptcha.tabindex') ?: '3',
        ]);
    }
}
```
It might be caused by the security component taking extra measures but I am unsure.

**Comment by rochamarcelo** [comment]
I could not reproduce the issue. I would say it's something related to Form Helper but not sure.

**Comment by amontrope** [comment]
That could be it. Thanks for pointing that out. Closing because this doesn't seem like a issue with this plugin.
