### ISSUE TITLE
addPlugin causes routing problems when the plugin is extended ?

### ISSUE THREAD

**Issue by BenoKop** [CakeDC/users#813]
CakeDC/Users 8.4.0
CakePHP 3.7.9

Hello all !

After updating a project, I wanted to load the plugin the new way through the Application.php file:

<pre>
Application::addPlugin('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
Configure::write('Users.config', ['users']);
Configure::write('Auth.loginRedirect', ['plugin' => null, 'controller' => 'Home', 'action' => 'dashboard']);
Configure::write('Users.Email.mailerClass', \App\Mailer\MyUsersMailer::class);
</pre>

The plugin is loaded but in some cases I'm getting weird errors.

For some reason, we extended the plugin by creating another controller in which I imported some CakeDC/Users traits. (Login, Register)

When I attempted to access to '/users/users/request-reset-password' it just said that i'm not allowed to access to this url that is supposed to be allowed to all.

So I tried to get into the code to see what could be the problem, I found that this condition is not getting true anymore:

<pre>
Controller/Component/UsersAuthComponent.php

list($plugin, $controller) = pluginSplit(Configure::read('Users.controller'));
        if ($this->getController()->getRequest()->getParam('plugin', null) === $plugin &&
            $this->getController()->getRequest()->getParam('controller') === $controller
        ) {
            $this->getController()->Auth->allow([
                // LoginTrait
                'twitterLogin',
                'login',
                'socialEmail',
                'verify',
                // RegisterTrait
                'register',
                'validateEmail',
                // PasswordManagementTrait used in RegisterTrait
                'changePassword',
                'resetPassword',
                'requestResetPassword',
                // UserValidationTrait used in PasswordManagementTrait
                'resendTokenValidation',
                // Social
                'endpoint',
                'authenticated',

                'u2f',
                'u2fRegister',
                'u2fRegisterFinish',
                'u2fAuthenticate',
                'u2fAuthenticateFinish',
            ]);
        }
</pre>

So I decided to load the plugin through the bootstrap.php file and it is working again.

Is it a misconfiguration on my side or a bug ?

Thanks.

**Comment by amontrope** [comment]
I realize that may not be well explained but from cakephp 3.7 and up, loading plugins in the bootstrap file will bring up a deprication warning. Plugins are added in your Application file.

```php
// In src/Application.php

namespace App

use Cake\Http\BaseApplication;

class Application extends BaseApplication
{

    public function bootstrap()
    {
        $this->addPlugin('CakeDC/Users', ['bootstrap' => true, 'routes' => true]);

        // Call parent to load bootstrap from files.
        parent::bootstrap();

         // Other code you may have
    }

    // Rest of the file...
}
```

Or you can try opening your project root in terminal and type:

```bash
bin/cake plugin load CakeDC/Users -br
```

**Comment by BenoKop** [comment]
Yeah I realize that my solution will be deprecated in the v4...
I tried your solution and it is still not working as I want, thanks for the reply !

**Comment by rochamarcelo** [comment]
@BenoKop since your app has extended the controller and changed the config 'Users.controller' you should access the action from your controller, so instead of  '/users/users/request-reset-password' you should access '/my-custom-users/request-reset-password' .

**Comment by rochamarcelo** [comment]
You can load the plugin in you Application::bootstrap:

```class Application extends BaseApplication 
{
    public function bootstrap()
    {
        parent::bootstrap();

        // Load a plugin with a vendor namespace by 'short name'
        $this->addPlugin('CakeDC/Users');
        Configure::write('Users.config', ['users']);
    }
}```

When you define config 'Users.controller'  we expect user to access the configure controller not the plugin controller. Hence closed this issue.

**Comment by BenoKop** [comment]
Thanks for the reply !
I adapted all my routes and templates to my extended controller and it fact, it is working how I want right now !
