### ISSUE TITLE
Fresh Install, Permissions Not Loading

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#816]
I just setup a new CakePHP Application, The first thing I did was setup a new index page and then installed was the CakeDC/Users Plugin

According to the [Documentation](https://github.com/CakeDC/auth/blob/master/Docs/Documentation/SimpleRbacAuthorize.md)...

> there is an example file you can copy into your config/permissions.php under the Plugin's config directory.

I have copied that file into my app/config directory, and I have modified the action from display to index

    //all roles allowed to Pages/display
    [
        'role' => '*',
        'controller' => 'Pages',
        'action' => 'index',
    ]

I have created an index.ctp file under Template/Pages and have created a index function in the Pages Controller, I have also modified the routes.php to display index for / instead of home

Before installing the CakeDC/Users plugin, I was able to view the index.ctp on / 

However now, the index page of the site is requiring a login...

Please Advise

**Comment by steinkel** [comment]
Hi @jeffreyroberts, this file is configuring your Authorization, keep in mind Authorization happens AFTER Authentication, so these permissions affect logged in users.

To configure actions outside of required authentication, you'll need to use `Auth::allow` or use the special key `bypassAuth` if you use `RbacMiddleware`...
