### ISSUE TITLE
Error after installing to cakephp 3.7 project

### ISSUE THREAD

**Issue by cercos** [CakeDC/users#819]
`Invalid config for 'GoogleAuthenticator.checker', '' does not implement 'CakeDC\Users\Auth\TwoFactorAuthenticationCheckerInterface'`

Everything is default, I have installed this on 7 other cakephp projects and never had this error and everything checks out.  I followed the stack trace and can't seem to find a problem.

**Comment by rochamarcelo** [comment]
Which version of the plugin are you using?

Please check the base users.php at https://github.com/CakeDC/users/blob/master/config/users.php

Make sure you are not setting a custom configuration for Users.

See that we need this config:

```
'GoogleAuthenticator' => [
        'checker' => \CakeDC\Users\Auth\DefaultTwoFactorAuthenticationChecker::class,
        'verifyAction' => [
            'plugin' => 'CakeDC/Users',
            'controller' => 'Users',
            'action' => 'verify',
            'prefix' => false,
        ],
    ],

```

**Comment by rochamarcelo** [comment]
Also try removing  vendor folder and run composer install again

**Comment by cercos** [comment]
I deleted vendor and ran composer install but same error.  I copied the users.php file from vendor config folder and my users.php config for GoogleAuthenticator matches
```
    'GoogleAuthenticator' => [
        'checker' => \CakeDC\Users\Auth\DefaultTwoFactorAuthenticationChecker::class,
        'verifyAction' => [
            'plugin' => 'CakeDC/Users',
            'controller' => 'Users',
            'action' => 'verify',
            'prefix' => false,
        ],
    ],
```

**Comment by cercos** [comment]
I also have Authenticator disabled so I don't even know why it's checking

**Comment by rochamarcelo** [comment]
@cercos  to load the plugin add this to your Application::bootstrap

```
$this->addPlugin(\CakeDC\Users\Plugin::class);
//Load your custom users.php file, ignore if you don't have one
Configure::write('Users.config', ['users']);
```
