### ISSUE TITLE
login with email

### ISSUE THREAD

**Issue by rrd108** [CakeDC/users#820]
This is related to #742 I managed to track it down more after run into the same issue on CakePHP 3.8

My setup is the following.

1. In my `Application.php` `bootstrap` function I load the plugin and set config values.

```php
Configure::write('Users.config', ['users']);
$this->addPlugin('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
Configure::write('Auth.authenticate.Form.fields.username', 'email');

```
2. My `login.ctp` is changed, so I have `email` instead of `username`.

**BUG DESCRIPTION**

The user can not log in with the proper credentials.

**REASON**

The plugin in its `users.php` file define the `$config` array. In this `Auth.authenticate => Form` is defined.

Than this default array is merged with the values what I defined, inculding the fields value. The resulting array is something like this at `vendor/cakephp/cakephp/src/Controller/Component/AuthComponent.php` line 850.

```php
[
'authenticate' =>
   [
      'Form' => ['fields' => ['username' => 'email']],
      'all',
      0 => 'CakeDC/Auth.ApiKey',
      1 => 'CakeDC/Auth.RememberMe',
      2 => 'Form'
   ]
]
```

Here `Hash::normalize()` is called and as we have a duplicated `Form` key, the second empty one overwrites the first, so we loose our field setting.

**SUGGESTED FIX**

In `cakedc/users/config/users.php` line 153 is

`'Form'`

should be replaced with this:

`'Form' => []`

By this it can be overwritten by user given data.

**Comment by rochamarcelo** [comment]
@rrd108  I quick fix would be 
```
Configure::write('Auth.authenticate', [
   'Form'  => [
        'fields' => ['username' => 'email']
   ],
   'CakeDC/Auth.RememberMe' => [],
]); 
```

**Comment by rrd108** [comment]
@rochamarcelo your suggested fix does not work for me.

**Comment by rochamarcelo** [comment]
Hi,

Please make sure that you have updated your login template file to use email instead of password and that your custom configuration was defined at Application::pluginBootstrap see 

https://github.com/CakeDC/users-example/blob/case/custom_username_field/src/Application.php#L69 and 

https://github.com/CakeDC/users-example/blob/case/custom_username_field/src/Template/Plugin/CakeDC/Users/Users/login.ctp

**Comment by rrd108** [comment]
Adding `pluginBootstrap` solved my issue.
Thanks
