### ISSUE TITLE
Missing route -> socialEmail

### ISSUE THREAD

**Issue by youchief** [CakeDC/users#825]
When you try to go to an other route without logged in. You've got this : 

Error A route matching "array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialEmail', 'prefix' => 'admin', '_ext' => NULL, )" could not be found.

**Comment by groovenectar** [comment]
@youchief You're getting that on *any* other route? Is this the latest version? Is it a fresh install, or adding to an existing project? When you're logged in, it doesn't do that?

**Comment by rochamarcelo** [comment]
Sent pull request https://github.com/CakeDC/users/pull/829
