### ISSUE TITLE
logout link exception on using route prefix

### ISSUE THREAD

**Issue by rrd108** [CakeDC/users#826]
I am using route prefix in my `config/routes.php`

```php
Router::prefix('admin', function (RouteBuilder $routes) {
    $routes->fallbacks(DashedRoute::class);
});
```

Than in one of my templates files I have the logout link

```php
<?= $this->User->logout('logout', ['prefix' => false]) ?>
```

This throws a missing route exception.

> Error: A route matching "array ( 'plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'logout', 'prefix' => 'admin', '_ext' => NULL, )" could not be found.

It seems that the `prefix` parameter is ignored.

**Comment by rochamarcelo** [comment]
Sent pull request
