### ISSUE TITLE
Extending UsersController, Overriding Login, Login not firing

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#827]
Hello, 

First, let me apologize, I am not sure why this isn't working, I have followed the documentation, and for whatever reason, I can not seem to get the overrided login function to fire...

If I put a die('1') in config/users.php and a die('0') in vendor/cakedc/users/config/users.php, the die('0') fires, if i remove the die('0'), then the die('1') fires, so it appears that the config/users.php is being loaded correctly...

Now, in config/users.php, I have the following

     $config = [
         'Users' => [
             // Table used to manage users
             'table' => 'CakeDC/Users.Users',
            // Controller used to manage users plugin features & actions
            'controller' => 'MyUsers',

And in src/Controller/MyUsersController.php I have

     <?php

     namespace App\Controller;

     use App\Controller\AppController;
     use Cake\Event\Event;
     use CakeDC\Users\Controller\Component\UsersAuthComponent;
     use CakeDC\Users\Controller\Traits\LoginTrait;
     use CakeDC\Users\Controller\Traits\RegisterTrait;

     class MyUsersController extends AppController
     {
         use LoginTrait;
         use RegisterTrait;

         public function login()
         {
             die('2');

However, die('2') doesn't seem to fire when visiting /login

Any ideas on how I can get this to work?

**Comment by jeffreyroberts** [comment]
If I update config/routes.php with

     Router::connect('/login', ['controller' => 'MyUsers', 'action' => 'login']);

It works, but should I need to do that? I don't recall seeing that in the documentation...

**Comment by groovenectar** [comment]
@jeffreyroberts Can you paste the line you have in `Application.php` to load the configuration? That is likely what is determining which config file to use

**Comment by groovenectar** [comment]
As far as getting the custom controller to take, I can't figure that part out either. It seems you are having a similar issue that I'm facing here: https://github.com/CakeDC/users/issues/823

But we can at least make sure you can get the config file loading as expected

**Comment by jeffreyroberts** [comment]
I am using CakePHP 3.7.1, so I am loading the plugin via bootstrap

    Configure::write('Users.config', ['users']);
    Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);

From what I can tell, the config/users.php file is loading after the vendor/..../config/users.php file, so I think that part is working correctly

**Comment by groovenectar** [comment]
So with this syntax:

    Configure::write('Users.config', ['users']);

It should load `config/users.php`

And with this:

    Configure::write('Users.config', ['Users.users']);

It should load `vendor/..../config/users.php` (with the Plugin syntax)

I thought that might be where the confusion was, but now I see that it is not...

Here is the line in `vendor/.../config/bootstrap.php` where it's loading the config:

    Configure::load('CakeDC/Users.users');
    collection((array)Configure::read('Users.config'))->each(function ($file) {
        Configure::load($file);
    });
    TableRegistry::getTableLocator()->setConfig('Users', ['className' => Configure::read('Users.table')]);
    TableRegistry::getTableLocator()->setConfig('CakeDC/Users.Users', ['className' => Configure::read('Users.table')]);

Personally I'm not even sure how it reads them in the order that it does, then, but it sounds like that part is ultimately working

Looking through at it again, I think that I now see where it is supposed to determine what controller to use...

`./vendor/cakedc/users/src/Utility/UsersUrl.php` method `actionUrl()`:

    /**
     * Get an user action url
     *
     * @param string $action user action
     * @param array $extra extra url attributes
     *
     * @return array
     */
    public function actionUrl($action, $extra = [])
    {
        $prefix = false;
        $controller = Configure::read('Users.controller', 'CakeDC/Users.Users');
        list($plugin, $controller) = pluginSplit($controller);
        $plugin = $plugin ? $plugin : false;

        return compact('prefix', 'plugin', 'controller', 'action') + $extra;
    }

I will have to dig into this code with some debugging more ASAP

**Comment by rochamarcelo** [comment]
Hi, 

when you create a custom controller you will have a new url for it, in your case it should be /my-users/login

Note you'll need to copy the Plugin templates you need into your project src/Template/MyUsers/[action].ctp
