### ISSUE TITLE
Username or password is incorrect

### ISSUE THREAD

**Issue by rrd108** [CakeDC/users#831]
I have a CakePHP 3.8.5 application on PHP 7.3.10 CakeDC/Users 8.5.1

The application uses email address to login. On my development server allis fine, but on the production server I can not log in. Regitration works, password change works, the changed hash update the paricular user, but login attemps gives `Username or password is incorrect` error message.

As I can not reproduce it on the dev server I am cluless what can cause the issue.

Any idea?

**Comment by rochamarcelo** [comment]
Does this happens to any user?

Try creating a new user at console and test again 

```cake users add_user```

Also check if you don't have any additional condition is used like 'users.active'

**Comment by rrd108** [comment]
> cake users add_user

This one created an example user and it also can not log in, I get the same error.

**Comment by rochamarcelo** [comment]
Please share your users.php file and any manual config change related to users (like `Configure::write('Users.controller', 'MyController');`

Also are you using a custom finder for auth?

**Comment by rrd108** [comment]
It seems that this issue is caused by #820

If I apply the fix what I mentioned there I am able to log in. 

`/config/users.php`

```php
<?php
return [
	'Users.table' => 'AppUsers',
]; 
```

`/src/Model/Table/AppUsersTable.php`

```php
namespace App\Model\Table;
use CakeDC\Users\Model\Table\UsersTable as CakeDCUsersTable;
use Cake\Validation\Validator;
use Cake\Core\Configure;

class AppUsersTable extends CakeDCUsersTable{

	public function initialize(array $config)
	{
		parent::initialize($config);
		$this->setDisplayField('email');
	}

	public function validationDefault(Validator $validator)
	{
		$validator = parent::validationDefault($validator);
		$username = Configure::read('Auth.authenticate.Form.fields.username');
		if ($username === 'email') {
			$validator->remove('username');
			$validator->allowEmpty('username');
		}
		return $validator;
	}
}
```

`/src/Application.php`

```php
public function bootstrap()
{
    parent::bootstrap();

    if (PHP_SAPI === 'cli') {
        $this->bootstrapCli();
    }

    Configure::write('Users.config', ['users']);
    $this->addPlugin('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
    Configure::write('Auth.authenticate.Form.fields.username', 'email');
}
```

`/src/Controller/AppController.php`

```php
public function initialize()
{
    parent::initialize();

    $this->loadComponent('RequestHandler', [
        'enableBeforeRedirect' => false,
    ]);
    $this->loadComponent('Flash');

    $this->loadComponent('CakeDC/Users.UsersAuth');
}
```

**Comment by rochamarcelo** [comment]
The issue was reported as fixed at https://github.com/CakeDC/users/issues/820
