### ISSUE TITLE
On login failure, redirects to /users/users/login, how to override that url

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#832]
I have extended the UsersController and overridden the login action, my login route is now '/login', and on login failure it redirects to '/users/users/login'... I am attempting to override the loginAction to correct this behavior, I have tried

    $this->Auth->configShallow('loginAction', '/login');

and

    'Auth' => [
        'loginAction' => [
            'controller' => 'Users',
            'action' => 'login',
            'prefix' => false
        ]
    ]

However, both seems to result in the login url being

     /login?redirect=%2Fusers%2Fusers%2Flogin

Any ideas how I can get the route to be /login for login failures?

**Comment by rochamarcelo** [comment]
@jeffreyroberts You will need to update your routes to point yours login action to /login.

See some example at https://github.com/CakeDC/users/blob/master/config/routes.php

It may look like 
```
 Router::connect('/login', ['plugin' => false, 'controller' => 'Users', 'action' => 'login']);
```
