### ISSUE TITLE
Loda Config Files From Plugin

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#835]
I am creating a dashboard plugin that uses CakeDC/Users. For me to distribute my plugin, I have to distribute it with an App Skeleton because the config files that extend your config files have to be located in the app/config directory...

I would really like to be able to load your config files from not only my plugin, but plugins that extend my plugin as well.

For instance, instead of loading the config from app/config, load them from the following locations

plugins/MyPlugin/config/users.php
plugins/MyPlugin/config/permissions.php
plugins/MyPluginExtension/config/permissions.php
plugins/MyPluginExtension2/config/permissions.php

This will allow me to distribute just my plugin and my plugin extensions, without the user having to add anything to the app skeleton. 

Thank you

Jeffrey

**Comment by jeffreyroberts** [comment]
I guess maybe they would have to add something to the AppController in the app skeleton, but the least amount of stuff for them to add the better

**Comment by rochamarcelo** [comment]
The config files don't need to be inside app/config it can be in your custom plugin.
Configure::load allows to load config files from plugin, and we use it. Add this in your bootstrap to use your custom users.php file:

```
$this->addPlugin(\CakeDC\Users\Plugin::class);
Configure::write('Users.config', ['MyPlugin.users']);
```

**Comment by jeffreyroberts** [comment]
Yes, but that means, that my plugin isn't plug and play, it requires configuration inside the app, which I am trying to avoid

**Comment by rochamarcelo** [comment]
I'm not saying that you must only add this in app, you should be able to add this in any plugin.

Check plugin objects https://book.cakephp.org/3/en/plugins.html#plugin-objects

**Comment by jeffreyroberts** [comment]
ohhhhh interesting, thank you so much =]
