### ISSUE TITLE
Upgrade to CakePHP 4.0.0-alpha1

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/users#838]
Any plans to upgrade to CakePHP 4.0.0-alpha1?

I'd like to start upgrading my Dashboard Skeleton, it requires CakeDC/Users, so Im sort stuck with testing until you guys upgrade the users plugin =]

Got a date for the upgrade yet? =]

ps: love what you guys are doing, thank you so much for your efforts =]

**Comment by rochamarcelo** [comment]
Please check 9.next branch. The plugin release will not be before CakePHP 4 stable release.
