### ISSUE TITLE
HTTP Basic authentication

### ISSUE THREAD

**Issue by rrd108** [CakeDC/users#839]
How can I use this plugin along with CakePHP's default Auth Component. I need Basic / Digest authentication for api calls.

It seems that if I load both components the config values owerwrites eash others.

**Comment by rrd108** [comment]
just found out that your plugin provides an api key authorization what serves my purpose. I think this is missing from your plugin's documentation.

**Comment by rochamarcelo** [comment]
okay, good to know it works for you. Thank you.
