### ISSUE TITLE
Potential issue in `config/routes.php`

### ISSUE THREAD

**Issue by groovenectar** [CakeDC/users#840]
https://github.com/CakeDC/users/blob/ecdedc841b288192fb6b34e102c219946addffd2/config/routes.php#L16

```php
$baseUsersPath = UsersUrl::isCustom() ? '/users-base' : '/users';
Router::plugin('CakeDC/Users', ['path' => $baseUsersPath], function (RouteBuilder $routes) {
    $routes->fallbacks('DashedRoute');
});
```

Using a custom controller, the `users-base` path comes through in the validation email...

If I change that to this:

```php
Router::plugin('CakeDC/Users', ['path' => '/'], function (RouteBuilder $routes) {
    $routes->fallbacks('DashedRoute');
});
```
Then it works fine... Trying to figure out what's going on here

**Comment by rochamarcelo** [comment]
So, it seems that email is using a wrong url.

**Comment by groovenectar** [comment]
It should be default or very lighted extended default setup for testing, I'll have to check...

**Comment by rochamarcelo** [comment]
This was fized on https://github.com/CakeDC/users/pull/852
