### ISSUE TITLE
Register user with token expired

### ISSUE THREAD

**Issue by rudy1976s** [CakeDC/users#842]
I have the following scenario: user register by filling form, then system sends confirmation link  via email.
User forgot to click and token expires: since table already has that user , saved with active = 0, is it possibile for user to register again ? It seems no, because the email is already registered in the table , although active is set to 0 and validation raise error regarding email.
I had unfortunately this scenario detected a lot of time

Is there a workaround , or something which is not described in docs ?

Thank you

Rudy

**Comment by rochamarcelo** [comment]
Hi,

As informed in slack, you could create a new action to resend the confirmation link.

Thanks.
