### ISSUE TITLE
[9.0.0] Problem with CookieAuthenticator / RememberMe feature

### ISSUE THREAD

**Issue by jtraulle** [CakeDC/users#849]
Hello,

I am trying to upgrade from 8.x to 9.x but I encounter a minor issue with the CookieAuthenticator I think (it replaces RememberMe component in 9.x).

If I refresh the page when the session is expired but Remember Me check box were previously checked, the page is successfully refreshed but the user is not properly authenticated (`$this->getRequest()->getSession()->read('Auth');` in my views returns `null`).

If I refresh the page again (second time), the session is restored successfully and `Auth` is populated in session.

Do you know what could cause that behavior ?

Thanks for your help :slightly_smiling_face: 

PS : apologies if this issue belongs more in the [CakeDC/auth](https://github.com/CakeDC/auth) repository (I was not sure where to report it).

**Comment by rochamarcelo** [comment]
That is a strange behavior, we need to look into it.

**Comment by jtraulle** [comment]
Thanks for your reply @rochamarcelo :slightly_smiling_face: 
You can ping me on slack if you need more info :wink:

**Comment by rochamarcelo** [comment]
@jtraulle please access the identity attribute instead. ```$this->getRequest()->getAttribute('identity')```

**Comment by rochamarcelo** [comment]
Authentication plugin only persist to session after the middleware handles the request (normally after controller action action). See https://github.com/cakephp/authentication/blob/d9442bc1e9abdf3a6ad66dd596d75c30b957e8c8/src/Middleware/AuthenticationMiddleware.php#L128
