### ISSUE TITLE
Reset password -- No context provider found for value of type string

### ISSUE THREAD

**Issue by groovenectar** [CakeDC/users#854]
https://github.com/CakeDC/users/blob/a77b2ca795fda75164a01430eaf8f9b6bd6c8d81/templates/Users/request_reset_password.php#L3

`$this->Form->create()` is apparently supposed to take an entity, or `null` as the argument... Here's the error:

![image](https://user-images.githubusercontent.com/595446/71738599-12111b00-2e25-11ea-964a-f5478554e182.png)

It seems that in 3.x that requirement wasn't super visible: https://github.com/cakephp/cakephp/issues/13493#issuecomment-570640461

**Comment by rochamarcelo** [comment]
Fixed in #855
