### ISSUE TITLE
Error when create users addSuperuser

### ISSUE THREAD

**Issue by wawanabnan** [CakeDC/users#859]
I install cakephp 4 then  follow step by step tutorial on  https://github.com/CakeDC/users/blob/master/Docs/Documentation/Installation.md

But I am stuck when run command :  

bin/cake users addSuperuser

Please help, the Result is :
bin/cake users addSuperuser
Exception: Unknown method "generateUniqueUsername" called on Cake\ORM\Table
In [/var/www/html/myapp/vendor/cakephp/cakephp/src/ORM/Table.php, line 2538]

2020-01-15 22:46:33 Error: [BadMethodCallException] Unknown method "generateUniqueUsername" called on Cake\ORM\Table in /var/www/html/myapp/vendor/cakephp/cakephp/src/ORM/Table.php on line 2538
Stack Trace:
- /var/www/html/myapp/vendor/cakedc/users/src/Shell/UsersShell.php:300
- /var/www/html/myapp/vendor/cakedc/users/src/Shell/UsersShell.php:114
- /var/www/html/myapp/vendor/cakephp/cakephp/src/Console/Shell.php:502
- /var/www/html/marketool.me/public_html/vendor/cakephp/cakephp/src/Console/CommandRunner.php:354
- /var/www/html/marketool.me/public_html/vendor/cakephp/cakephp/src/Console/CommandRunner.php:168
- /var/www/html/marketool.me/public_html/bin/cake.php:12

thank for help.

**Comment by rochamarcelo** [comment]
Please inform the plugin version used.

**Comment by luke3butler** [comment]
@rochamarcelo This error happens on 9.0.2 while following the guide for [extending the Model/Entity](https://github.com/CakeDC/users/blob/9.next/Docs/Documentation/Extending-the-Plugin.md).

When using the default Model/Entity within CakeDC/Users this error doesn't happen, but adding the following to config/users.php (and adding the correct Model and Entity files to the application) will trigger this issue.

```
return [
    'Users.table' => 'MyPluginName/MyUsers',
    // I also tried this, since it should work as an alternative
    'Users.table' => 'MyPluginName\Users\MyUsersTable',
];
```

After running it through a debugger it looks like UsersTable->initialize() is not getting called, so none of the behaviors are getting added and "generateUniqueUsername" just happens to be the first behavior method that is called.

I did verify that UsersTable->initialize() gets called when using the default configuration without an extended Model/Entity.

**Comment by luke3butler** [comment]
So this is user error, not necessarily anything wrong with this plugin.

When TableLocator can't find the model/class, [it assigns the current (Cake\ORM\Table) class by default](https://github.com/cakephp/cakephp/blob/4.next/src/ORM/Locator/TableLocator.php#L198).

I was able to fix this issue by correcting my Users.table config to match how this plugin defines the default table.

```
return [
    'Users.table' => 'MyOrg/Users.MyUsers',
];
```

**Comment by luke3butler** [comment]
So this is user error, not necessarily anything wrong with this plugin.

When TableLocator can't find the model/class, [it assigns the current (Cake\ORM\Table) class by default](https://github.com/cakephp/cakephp/blob/4.next/src/ORM/Locator/TableLocator.php#L198).

I was able to fix this issue by correcting my Users.table config to match how this plugin defines the default table.

For example, if you're using a plugin (instead of the base app) to extend, you'll need to define it like this:

```
return [
    'Users.table' => 'MyOrg/Users.MyUsers',
];
```
