### ISSUE TITLE
Auth session is not expiring

### ISSUE THREAD

**Issue by gooseleggs** [CakeDC/users#866]
I am using this plugin in CakePhp 3.8.  It is working fine, except that it is not expiring authentication between browser restarts, or after any length of time.

In app.php I have

```
    'Session' => [
        'defaults' => 'php',
        'timeout' => 30
    ],
```
In Appcontroller.php I have
```
        $this->loadComponent('RequestHandler', [
            'enableBeforeRedirect' => false,
        ]);
        $this->loadComponent('Flash');
        $this->loadComponent('CakeDC/Users.UsersAuth');
        $this->Auth->setConfig('loginRedirect', '/customer');
```
and nothing else really anywhere else.  I have just loaded the Users plug using the integrated Auth setup.  

Where would I look to resolve this?

**Comment by rochamarcelo** [comment]
It seems that you have check the check box for 'remember me'  feature or you php environment is not allowing that session customization

**Comment by rochamarcelo** [comment]
Closing it due to inactivity. Thank you.
