### ISSUE TITLE
Helper Plugin User->welcome() returns '' due to empty session after login

### ISSUE THREAD

**Issue by matthttam** [CakeDC/users#868]
I'm using a pretty new Cakephp4 installation and I have the CakeDC/users plugin installed with basic configurations.

`	'Users' =>
	[
		'Registration' => [
			'active' => false
		],
		'Tos' => [
			'required' => false
		],
		'Social' => [
			'login' => true
		], ...`

I've loaded the helper function in my Appveiw as well
`
public function initialize(): void
    {
        parent::initialize();
        $this->loadHelper('CakeDC/Users.User');
    }
`

I signed in with my superadmin and tried to use the $this->Users->welcome() helper function but it returned an empty string. After looking at it, the welcome function is trying to call:
`$userId = $this->getView()->getRequest()->getSession()->read('Auth.User.id');`

However if I debug($this->getRequest()->getSession()); directly from my page view I only see:
`object(Cake\Http\Session) {
	[protected] _engine => null
	[protected] _started => true
	[protected] _lifetime => (int) 1440
	[protected] _isCLI => false
}`

Why is there no user information in my session? Or does this method need to be rewritten?

**Comment by rochamarcelo** [comment]
Sent pull request #869

**Comment by rochamarcelo** [comment]
Thank you.
