### ISSUE TITLE
Redirect loop with debug plugin

### ISSUE THREAD

**Issue by infokani** [CakeDC/users#870]
When i first time enabled users plugin, i got lots of URL errors with users plugin prefix. It looks every template file URLs got users plugin prefix. So i set all URLs with plugin false then i got another problem redirect loop. I set debug false then no loop. I think users plugin affecting URLs. How do i solve it.
Sorry my poor English

**Comment by rochamarcelo** [comment]
Hi,

first you need to set permissions to DebugKit actions in your config/permissions.php

```
[
            'role' => '*',
            'plugin' => 'DebugKit',
            'controller' => '*',
            'action' => '*',
            'bypassAuth' => true,
],

```

About links getting the prefix from users plugin, you need to set `'plugin' => false,` in normal links, this is the normal behavior in CakePHP.

**Comment by infokani** [comment]
ok. Tnx i will try
