### ISSUE TITLE
CakeDC keeps redirecting to login page

### ISSUE THREAD

**Issue by linkinted** [CakeDC/users#871]
Hello,

I'm running a fresh installation of CakePHP4.0.4 with CakeDC Users plugin 9.0.1.

The page /events keeps redirecting me to the login page. Underneath the relevant code... What am I doing wrong here?
Also my DebugKit isn't working, because it is redirecting to the login page.

Application.php

	<?php
	declare(strict_types=1);
	
	namespace App;
	
	use Cake\Core\Configure;
	use Cake\Core\Exception\MissingPluginException;
	use Cake\Error\Middleware\ErrorHandlerMiddleware;
	use Cake\Http\BaseApplication;
	use Cake\Http\MiddlewareQueue;
	use Cake\Routing\Middleware\AssetMiddleware;
	use Cake\Routing\Middleware\RoutingMiddleware;

	class Application extends BaseApplication /*implements AuthenticationServiceProviderInterface*/
	{
	    /**
	     * Load all the application configuration and bootstrap logic.
	     *
	     * @return void
	     */
	    public function bootstrap(): void
	    {
	        parent::bootstrap();
	        if (PHP_SAPI === 'cli') {
	            $this->bootstrapCli();
	        }
	        if (Configure::read('debug')) {
	            Configure::write('DebugKit.forceEnable', true);
	            $this->addPlugin('DebugKit');
	        }
	        // Load more plugins here
	        $this->addPlugin(\CakeDC\Users\Plugin::class);
	    }

AppController.php

	<?php
	declare(strict_types=1);

	namespace App\Controller;
	
	use Cake\Core\Configure;
	use Cake\Controller\Controller;

	class AppController extends Controller
	{
	    public function initialize(): void
	    {
	        parent::initialize();
	
	        $this->loadComponent('RequestHandler');
	        $this->loadComponent('Flash');
		$this->loadComponent('CakeDC/Users.Setup');

EventsController.php

	<?php
	declare(strict_types=1);
	namespace App\Controller;
	
	use Cake\Utility\Hash;	class EventsController extends AppController
	{
	    public function beforeFilter(\Cake\Event\EventInterface $event)
	    {
	        parent::beforeFilter($event);
	        $this->Authentication->allowUnauthenticated(['index']);
	    }

**Comment by rochamarcelo** [comment]
Hi @linkinted,

we use RBAC permissions, so, you need to create a config/permissions.php (https://github.com/CakeDC/users/blob/master/config/permissions.php)  file with permissions to your actions.

**Comment by linkinted** [comment]
@rochamarcelo 

Yes, but if I want a page to be accessible without login in, how do I do that?

**Comment by rochamarcelo** [comment]
Just add a bypass in permissions.php

```[
            'role' => '*',
            'controller' => 'MyController',
            'action' => ['actionOne', 'actionTrue'],
            'bypassAuth' => true,
], ```

**Comment by linkinted** [comment]
Thanks, that worked.
Is that in the Documentation somewhere, because didn't see it...

**Comment by robertkendrick** [comment]
CakePHP 4.0.5 and CakeDC/Users 9.0.2
Debug Kit not functional whe logged out.
It loops in the LoginTrait::login() 10 times 

cake server output
[Mon Apr 13 18:54:30 2020] [::1]:54669 [200]: GET /debug_kit/js/jquery.js?_=1586800464861
[Mon Apr 13 18:54:30 2020] [::1]:54669 Closing
[Mon Apr 13 18:54:30 2020] [::1]:54671 Accepted
[Mon Apr 13 18:54:30 2020] [::1]:54671 [200]: GET /debug_kit/js/toolbar-app.js?_=1586800464862
[Mon Apr 13 18:54:30 2020] [::1]:54671 Closing
[Mon Apr 13 18:54:31 2020] [::1]:54673 Accepted
[Mon Apr 13 18:54:37 2020] [::1]:54673 Closing
[Mon Apr 13 18:54:43 2020] [::1]:54682 Accepted
[Mon Apr 13 18:54:48 2020] [::1]:54682 Closed without sending a request; it was probably just an unused speculative preconnection
[Mon Apr 13 18:54:48 2020] [::1]:54682 Closing
[Mon Apr 13 18:54:48 2020] [::1]:54683 Accepted
[Mon Apr 13 18:54:48 2020] [::1]:54684 Accepted
[Mon Apr 13 18:54:50 2020] [::1]:54683 Closing
[Mon Apr 13 18:54:53 2020] [::1]:54684 Closed without sending a request; it was probably just an unused speculative preconnection
[Mon Apr 13 18:54:53 2020] [::1]:54684 Closing
[Mon Apr 13 18:54:53 2020] [::1]:54693 Accepted
[Mon Apr 13 18:54:55 2020] [::1]:54693 Closing
[Mon Apr 13 18:54:57 2020] [::1]:54702 Accepted
[Mon Apr 13 18:55:02 2020] [::1]:54702 Closed without sending a request; it was probably just an unused speculative preconnection
[Mon Apr 13 18:55:02 2020] [::1]:54702 Closing
[Mon Apr 13 18:55:05 2020] [::1]:54704 Accepted
[Mon Apr 13 18:55:08 2020] [::1]:54704 Closing
[Mon Apr 13 18:55:14 2020] [::1]:54713 Accepted
[Mon Apr 13 18:55:18 2020] [::1]:54713 Closing
[Mon Apr 13 18:55:18 2020] [::1]:54722 Accepted
[Mon Apr 13 18:55:18 2020] [::1]:54722 [200]: GET /debug_kit/js/jquery.js?_=1586800464863
[Mon Apr 13 18:55:18 2020] [::1]:54722 Closing
[Mon Apr 13 18:55:18 2020] [::1]:54724 Accepted
[Mon Apr 13 18:55:18 2020] [::1]:54724 [200]: GET /debug_kit/js/toolbar-app.js?_=1586800464864
[Mon Apr 13 18:55:18 2020] [::1]:54724 Closing
[Mon Apr 13 18:55:31 2020] [::1]:54727 Accepted
[Mon Apr 13 18:55:33 2020] [::1]:54727 Closing
[Mon Apr 13 18:55:33 2020] [::1]:54736 Accepted
[Mon Apr 13 18:55:33 2020] [::1]:54736 [200]: GET /debug_kit/js/jquery.js?_=1586800464865
[Mon Apr 13 18:55:33 2020] [::1]:54736 Closing
[Mon Apr 13 18:55:33 2020] [::1]:54738 Accepted
[Mon Apr 13 18:55:34 2020] [::1]:54738 [200]: GET /debug_kit/js/toolbar-app.js?_=1586800464866
[Mon Apr 13 18:55:34 2020] [::1]:54738 Closing
[Mon Apr 13 18:56:36 2020] [::1]:54741 Accepted
[Mon Apr 13 18:56:38 2020] [::1]:54741 Closing
[Mon Apr 13 18:56:38 2020] [::1]:54750 Accepted
[Mon Apr 13 18:56:40 2020] [::1]:54750 Closing
[Mon Apr 13 18:56:40 2020] [::1]:54759 Accepted
[Mon Apr 13 18:56:40 2020] [::1]:54760 Accepted
[Mon Apr 13 18:56:40 2020] [::1]:54759 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:56:40 2020] [::1]:54761 Accepted
[Mon Apr 13 18:56:41 2020] [::1]:54760 [200]: GET /css/cake.css
[Mon Apr 13 18:56:41 2020] [::1]:54761 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:56:41 2020] [::1]:54759 Closing
[Mon Apr 13 18:56:41 2020] [::1]:54760 Closing
[Mon Apr 13 18:56:41 2020] [::1]:54761 Closing
[Mon Apr 13 18:56:41 2020] [::1]:54765 Accepted
[Mon Apr 13 18:56:43 2020] [::1]:54765 Closing
[Mon Apr 13 18:56:43 2020] [::1]:54774 Accepted
[Mon Apr 13 18:56:45 2020] [::1]:54774 Closing
[Mon Apr 13 18:56:45 2020] [::1]:54783 Accepted
[Mon Apr 13 18:56:45 2020] [::1]:54783 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:56:45 2020] [::1]:54784 Accepted
[Mon Apr 13 18:56:45 2020] [::1]:54786 Accepted
[Mon Apr 13 18:56:46 2020] [::1]:54784 [200]: GET /css/cake.css
[Mon Apr 13 18:56:46 2020] [::1]:54786 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:56:46 2020] [::1]:54783 Closing
[Mon Apr 13 18:56:46 2020] [::1]:54784 Closing
[Mon Apr 13 18:56:46 2020] [::1]:54786 Closing
[Mon Apr 13 18:56:46 2020] [::1]:54789 Accepted
[Mon Apr 13 18:56:48 2020] [::1]:54789 Closing
[Mon Apr 13 18:56:48 2020] [::1]:54798 Accepted
[Mon Apr 13 18:56:50 2020] [::1]:54798 Closing
[Mon Apr 13 18:56:50 2020] [::1]:54807 Accepted
[Mon Apr 13 18:56:51 2020] [::1]:54807 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:56:51 2020] [::1]:54808 Accepted
[Mon Apr 13 18:56:51 2020] [::1]:54810 Accepted
[Mon Apr 13 18:56:51 2020] [::1]:54808 [200]: GET /css/cake.css
[Mon Apr 13 18:56:51 2020] [::1]:54810 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:56:51 2020] [::1]:54807 Closing
[Mon Apr 13 18:56:51 2020] [::1]:54808 Closing
[Mon Apr 13 18:56:51 2020] [::1]:54810 Closing
[Mon Apr 13 18:56:51 2020] [::1]:54813 Accepted
[Mon Apr 13 18:56:53 2020] [::1]:54813 Closing
[Mon Apr 13 18:56:53 2020] [::1]:54822 Accepted
[Mon Apr 13 18:56:55 2020] [::1]:54822 Closing
[Mon Apr 13 18:56:55 2020] [::1]:54831 Accepted
[Mon Apr 13 18:56:55 2020] [::1]:54831 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:56:55 2020] [::1]:54832 Accepted
[Mon Apr 13 18:56:55 2020] [::1]:54834 Accepted
[Mon Apr 13 18:56:56 2020] [::1]:54832 [200]: GET /css/cake.css
[Mon Apr 13 18:56:56 2020] [::1]:54834 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:56:56 2020] [::1]:54831 Closing
[Mon Apr 13 18:56:56 2020] [::1]:54832 Closing
[Mon Apr 13 18:56:56 2020] [::1]:54834 Closing
[Mon Apr 13 18:56:56 2020] [::1]:54837 Accepted
[Mon Apr 13 18:56:58 2020] [::1]:54837 Closing
[Mon Apr 13 18:56:58 2020] [::1]:54846 Accepted
[Mon Apr 13 18:57:00 2020] [::1]:54846 Closing
[Mon Apr 13 18:57:00 2020] [::1]:54855 Accepted
[Mon Apr 13 18:57:00 2020] [::1]:54855 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:57:00 2020] [::1]:54856 Accepted
[Mon Apr 13 18:57:00 2020] [::1]:54857 Accepted
[Mon Apr 13 18:57:01 2020] [::1]:54856 [200]: GET /css/cake.css
[Mon Apr 13 18:57:01 2020] [::1]:54857 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:57:01 2020] [::1]:54855 Closing
[Mon Apr 13 18:57:01 2020] [::1]:54856 Closing
[Mon Apr 13 18:57:01 2020] [::1]:54857 Closing
[Mon Apr 13 18:57:01 2020] [::1]:54861 Accepted
[Mon Apr 13 18:57:03 2020] [::1]:54861 Closing
[Mon Apr 13 18:57:03 2020] [::1]:54871 Accepted
[Mon Apr 13 18:57:05 2020] [::1]:54871 Closing
[Mon Apr 13 18:57:05 2020] [::1]:54880 Accepted
[Mon Apr 13 18:57:05 2020] [::1]:54880 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:57:05 2020] [::1]:54882 Accepted
[Mon Apr 13 18:57:05 2020] [::1]:54883 Accepted
[Mon Apr 13 18:57:05 2020] [::1]:54882 [200]: GET /css/cake.css
[Mon Apr 13 18:57:06 2020] [::1]:54883 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:57:06 2020] [::1]:54880 Closing
[Mon Apr 13 18:57:06 2020] [::1]:54882 Closing
[Mon Apr 13 18:57:06 2020] [::1]:54883 Closing
[Mon Apr 13 18:57:06 2020] [::1]:54886 Accepted
[Mon Apr 13 18:57:08 2020] [::1]:54886 Closing
[Mon Apr 13 18:57:08 2020] [::1]:54895 Accepted
[Mon Apr 13 18:57:10 2020] [::1]:54895 Closing
[Mon Apr 13 18:57:10 2020] [::1]:54904 Accepted
[Mon Apr 13 18:57:10 2020] [::1]:54904 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:57:10 2020] [::1]:54906 Accepted
[Mon Apr 13 18:57:10 2020] [::1]:54907 Accepted
[Mon Apr 13 18:57:10 2020] [::1]:54906 [200]: GET /css/cake.css
[Mon Apr 13 18:57:10 2020] [::1]:54907 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:57:10 2020] [::1]:54904 Closing
[Mon Apr 13 18:57:10 2020] [::1]:54906 Closing
[Mon Apr 13 18:57:10 2020] [::1]:54907 Closing
[Mon Apr 13 18:57:10 2020] [::1]:54910 Accepted
[Mon Apr 13 18:57:12 2020] [::1]:54910 Closing
[Mon Apr 13 18:57:12 2020] [::1]:54919 Accepted
[Mon Apr 13 18:57:15 2020] [::1]:54919 Closing
[Mon Apr 13 18:57:15 2020] [::1]:54928 Accepted
[Mon Apr 13 18:57:15 2020] [::1]:54928 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:57:15 2020] [::1]:54929 Accepted
[Mon Apr 13 18:57:15 2020] [::1]:54930 Accepted
[Mon Apr 13 18:57:15 2020] [::1]:54929 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:57:15 2020] [::1]:54930 [200]: GET /css/cake.css
[Mon Apr 13 18:57:15 2020] [::1]:54928 Closing
[Mon Apr 13 18:57:15 2020] [::1]:54929 Closing
[Mon Apr 13 18:57:15 2020] [::1]:54930 Closing
[Mon Apr 13 18:57:15 2020] [::1]:54936 Accepted
[Mon Apr 13 18:57:17 2020] [::1]:54936 Closing
[Mon Apr 13 18:57:17 2020] [::1]:54945 Accepted
[Mon Apr 13 18:57:19 2020] [::1]:54945 Closing
[Mon Apr 13 18:57:19 2020] [::1]:54954 Accepted
[Mon Apr 13 18:57:20 2020] [::1]:54954 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:57:20 2020] [::1]:54955 Accepted
[Mon Apr 13 18:57:20 2020] [::1]:54956 Accepted
[Mon Apr 13 18:57:20 2020] [::1]:54955 [200]: GET /css/cake.css
[Mon Apr 13 18:57:20 2020] [::1]:54956 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:57:20 2020] [::1]:54954 Closing
[Mon Apr 13 18:57:20 2020] [::1]:54955 Closing
[Mon Apr 13 18:57:20 2020] [::1]:54960 Accepted
[Mon Apr 13 18:57:20 2020] [::1]:54956 Closing
[Mon Apr 13 18:57:22 2020] [::1]:54960 Closing
[Mon Apr 13 18:57:22 2020] [::1]:54969 Accepted
[Mon Apr 13 18:57:24 2020] [::1]:54969 Closing
[Mon Apr 13 18:57:24 2020] [::1]:54978 Accepted
[Mon Apr 13 18:57:24 2020] [::1]:54978 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:57:24 2020] [::1]:54980 Accepted
[Mon Apr 13 18:57:24 2020] [::1]:54981 Accepted
[Mon Apr 13 18:57:25 2020] [::1]:54980 [200]: GET /css/cake.css
[Mon Apr 13 18:57:25 2020] [::1]:54981 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:57:25 2020] [::1]:54978 Closing
[Mon Apr 13 18:57:25 2020] [::1]:54980 Closing
[Mon Apr 13 18:57:25 2020] [::1]:54981 Closing
[Mon Apr 13 18:58:11 2020] [::1]:54987 Accepted
[Mon Apr 13 18:58:24 2020] [::1]:54987 Closing
[Mon Apr 13 18:58:24 2020] [::1]:54989 Accepted
[Mon Apr 13 18:58:35 2020] [::1]:54989 Closing
[Mon Apr 13 18:58:35 2020] [::1]:54991 Accepted
[Mon Apr 13 18:58:36 2020] [::1]:54991 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:58:36 2020] [::1]:54992 Accepted
[Mon Apr 13 18:58:36 2020] [::1]:54993 Accepted
[Mon Apr 13 18:58:36 2020] [::1]:54992 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:58:36 2020] [::1]:54993 [200]: GET /css/cake.css
[Mon Apr 13 18:58:36 2020] [::1]:54991 Closing
[Mon Apr 13 18:58:36 2020] [::1]:54992 Closing
[Mon Apr 13 18:58:36 2020] [::1]:54993 Closing
[Mon Apr 13 18:58:36 2020] [::1]:54997 Accepted
[Mon Apr 13 18:58:36 2020] [::1]:54997 Closing
[Mon Apr 13 18:58:36 2020] [::1]:54999 Accepted
[Mon Apr 13 18:58:41 2020] [::1]:54999 Closing
[Mon Apr 13 18:58:41 2020] [::1]:55003 Accepted
[Mon Apr 13 18:58:41 2020] [::1]:55004 Accepted
[Mon Apr 13 18:58:41 2020] [::1]:55003 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:58:41 2020] [::1]:55006 Accepted
[Mon Apr 13 18:58:41 2020] [::1]:55004 [200]: GET /css/cake.css
[Mon Apr 13 18:58:41 2020] [::1]:55006 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:58:41 2020] [::1]:55003 Closing
[Mon Apr 13 18:58:41 2020] [::1]:55004 Closing
[Mon Apr 13 18:58:41 2020] [::1]:55006 Closing
[Mon Apr 13 18:58:41 2020] [::1]:55009 Accepted
[Mon Apr 13 18:58:42 2020] [::1]:55009 Closing
[Mon Apr 13 18:58:42 2020] [::1]:55011 Accepted
[Mon Apr 13 18:58:44 2020] [::1]:55011 Closing
[Mon Apr 13 18:58:44 2020] [::1]:55013 Accepted
[Mon Apr 13 18:58:44 2020] [::1]:55014 Accepted
[Mon Apr 13 18:58:44 2020] [::1]:55013 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:58:44 2020] [::1]:55015 Accepted
[Mon Apr 13 18:58:44 2020] [::1]:55014 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:58:44 2020] [::1]:55015 [200]: GET /css/cake.css
[Mon Apr 13 18:58:44 2020] [::1]:55013 Closing
[Mon Apr 13 18:58:44 2020] [::1]:55014 Closing
[Mon Apr 13 18:58:44 2020] [::1]:55015 Closing
[Mon Apr 13 18:58:44 2020] [::1]:55019 Accepted
[Mon Apr 13 18:58:44 2020] [::1]:55019 Closing
[Mon Apr 13 18:58:44 2020] [::1]:55021 Accepted
[Mon Apr 13 18:58:47 2020] [::1]:55021 Closing
[Mon Apr 13 18:58:47 2020] [::1]:55023 Accepted
[Mon Apr 13 18:58:47 2020] [::1]:55023 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:58:47 2020] [::1]:55023 Closing
[Mon Apr 13 18:58:47 2020] [::1]:55025 Accepted
[Mon Apr 13 18:58:47 2020] [::1]:55025 [200]: GET /css/cake.css
[Mon Apr 13 18:58:47 2020] [::1]:55026 Accepted
[Mon Apr 13 18:58:47 2020] [::1]:55026 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:58:47 2020] [::1]:55025 Closing
[Mon Apr 13 18:58:47 2020] [::1]:55026 Closing
[Mon Apr 13 18:58:47 2020] [::1]:55029 Accepted
[Mon Apr 13 18:58:47 2020] [::1]:55029 Closing
[Mon Apr 13 18:58:47 2020] [::1]:55031 Accepted
[Mon Apr 13 18:58:50 2020] [::1]:55031 Closing
[Mon Apr 13 18:58:50 2020] [::1]:55033 Accepted
[Mon Apr 13 18:58:50 2020] [::1]:55033 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:58:50 2020] [::1]:55035 Accepted
[Mon Apr 13 18:58:50 2020] [::1]:55036 Accepted
[Mon Apr 13 18:58:50 2020] [::1]:55035 [200]: GET /css/cake.css
[Mon Apr 13 18:58:50 2020] [::1]:55036 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:58:50 2020] [::1]:55033 Closing
[Mon Apr 13 18:58:50 2020] [::1]:55035 Closing
[Mon Apr 13 18:58:50 2020] [::1]:55036 Closing
[Mon Apr 13 18:58:50 2020] [::1]:55039 Accepted
[Mon Apr 13 18:58:50 2020] [::1]:55039 Closing
[Mon Apr 13 18:58:50 2020] [::1]:55041 Accepted
[Mon Apr 13 18:58:53 2020] [::1]:55041 Closing
[Mon Apr 13 18:58:53 2020] [::1]:55043 Accepted
[Mon Apr 13 18:58:53 2020] [::1]:55043 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:58:53 2020] [::1]:55043 Closing
[Mon Apr 13 18:58:53 2020] [::1]:55045 Accepted
[Mon Apr 13 18:58:53 2020] [::1]:55045 [200]: GET /css/cake.css
[Mon Apr 13 18:58:53 2020] [::1]:55047 Accepted
[Mon Apr 13 18:58:53 2020] [::1]:55047 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:58:53 2020] [::1]:55045 Closing
[Mon Apr 13 18:58:53 2020] [::1]:55047 Closing
[Mon Apr 13 18:58:53 2020] [::1]:55049 Accepted
[Mon Apr 13 18:58:53 2020] [::1]:55049 Closing
[Mon Apr 13 18:58:53 2020] [::1]:55051 Accepted
[Mon Apr 13 18:58:56 2020] [::1]:55051 Closing
[Mon Apr 13 18:58:56 2020] [::1]:55053 Accepted
[Mon Apr 13 18:58:56 2020] [::1]:55053 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:58:56 2020] [::1]:55054 Accepted
[Mon Apr 13 18:58:56 2020] [::1]:55056 Accepted
[Mon Apr 13 18:58:56 2020] [::1]:55054 [200]: GET /css/cake.css
[Mon Apr 13 18:58:56 2020] [::1]:55056 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:58:56 2020] [::1]:55053 Closing
[Mon Apr 13 18:58:56 2020] [::1]:55054 Closing
[Mon Apr 13 18:58:56 2020] [::1]:55056 Closing
[Mon Apr 13 18:58:56 2020] [::1]:55059 Accepted
[Mon Apr 13 18:58:56 2020] [::1]:55059 Closing
[Mon Apr 13 18:58:56 2020] [::1]:55061 Accepted
[Mon Apr 13 18:58:59 2020] [::1]:55061 Closing
[Mon Apr 13 18:58:59 2020] [::1]:55063 Accepted
[Mon Apr 13 18:58:59 2020] [::1]:55063 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:58:59 2020] [::1]:55064 Accepted
[Mon Apr 13 18:58:59 2020] [::1]:55065 Accepted
[Mon Apr 13 18:58:59 2020] [::1]:55064 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:58:59 2020] [::1]:55065 [200]: GET /css/cake.css
[Mon Apr 13 18:58:59 2020] [::1]:55063 Closing
[Mon Apr 13 18:58:59 2020] [::1]:55064 Closing
[Mon Apr 13 18:58:59 2020] [::1]:55065 Closing
[Mon Apr 13 18:58:59 2020] [::1]:55069 Accepted
[Mon Apr 13 18:58:59 2020] [::1]:55069 Closing
[Mon Apr 13 18:58:59 2020] [::1]:55071 Accepted
[Mon Apr 13 18:59:02 2020] [::1]:55071 Closing
[Mon Apr 13 18:59:02 2020] [::1]:55073 Accepted
[Mon Apr 13 18:59:02 2020] [::1]:55073 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:59:02 2020] [::1]:55074 Accepted
[Mon Apr 13 18:59:02 2020] [::1]:55075 Accepted
[Mon Apr 13 18:59:02 2020] [::1]:55074 [200]: GET /css/cake.css
[Mon Apr 13 18:59:02 2020] [::1]:55075 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:59:02 2020] [::1]:55073 Closing
[Mon Apr 13 18:59:02 2020] [::1]:55074 Closing
[Mon Apr 13 18:59:02 2020] [::1]:55075 Closing
[Mon Apr 13 18:59:02 2020] [::1]:55079 Accepted
[Mon Apr 13 18:59:02 2020] [::1]:55079 Closing
[Mon Apr 13 18:59:02 2020] [::1]:55081 Accepted
[Mon Apr 13 18:59:05 2020] [::1]:55081 Closing
[Mon Apr 13 18:59:05 2020] [::1]:55084 Accepted
[Mon Apr 13 18:59:05 2020] [::1]:55084 [200]: GET /css/milligram.min.css
[Mon Apr 13 18:59:05 2020] [::1]:55085 Accepted
[Mon Apr 13 18:59:05 2020] [::1]:55087 Accepted
[Mon Apr 13 18:59:05 2020] [::1]:55085 [200]: GET /css/cake.css
[Mon Apr 13 18:59:05 2020] [::1]:55087 [200]: GET /debug_kit/js/toolbar.js?1586727035
[Mon Apr 13 18:59:05 2020] [::1]:55084 Closing
[Mon Apr 13 18:59:05 2020] [::1]:55085 Closing
[Mon Apr 13 18:59:05 2020] [::1]:55087 Closing
[Mon Apr 13 18:59:13 2020] [::1]:55090 Accepted
[Mon Apr 13 18:59:18 2020] [::1]:55090 Closed without sending a request; it was probably just an unused speculative preconnection
[Mon Apr 13 18:59:18 2020] [::1]:55090 Closing

**Comment by ermsb** [comment]
adding this in permissions.php made debugkit work even when not logged in
```
        //cakephp debugkit bypassauth
        [
            'plugin' => 'DebugKit',
            'controller' => '*',
            'action' => '*',
            'bypassAuth' => true,
        ],
```

**Comment by robertkendrick** [comment]
Yes, thankyou ermsb I saw this on one of the developing websites.
Thanks for taking the trouble to let me know,
I believe this issue should now be closed.

**Comment by lpedretti** [comment]
I need to only bypass authentication if the request is of type json, and I can't do that if my beforeFilter or initialize controller methods aren't even reached, how could i implement that using cakedc?
