### ISSUE TITLE
Debug Kit not functional when logged out

### ISSUE THREAD

**Issue by linkinted** [CakeDC/users#872]
Hello,

I had some trouble with making the public area work, this was fixed in this issue:
https://github.com/CakeDC/users/issues/871#issuecomment-594619120

The code I'm using in `permissions.php` is the following:

     [
            'role' => '*',
            'controller' => ['Pages','Events','DebugKit','debug_kit','debug-kit'],
            'action' => '*',
            'bypassAuth' => true,
     ], 

This works good for the PagesController and EventsController. However the DebugKit isn't visible anymore. Opening the iframe shows that the DebugKit is redirected to the inlog page. 
I need to be logged in to see it.

How can I fix that?

**Comment by kuebel** [comment]
From #870 - you have to allow the complete plugin:

[
            'role' => '*',
            'plugin' => 'DebugKit',
            'controller' => '*',
            'action' => '*',
            'bypassAuth' => true,
],

**Comment by steinkel** [comment]
Thank you we've added the DebugKit bypassAuth config by default to permissions.php
