### ISSUE TITLE
Email address instead of username

### ISSUE THREAD

**Issue by zsfoto** [CakeDC/users#873]
Hello,

I would like to use email address instead of username. After many trials it work as follows. 
In **`login.php`** **`$this->Form->control('email', ... )`** does not work.
Work the **`$this->Form->control('username', ... )`**.

And in **`config/users.php`** contain: **`'Auth.Identifiers.Password.fields.username' => 'email'`**

Regards Zsolt.

**Comment by Y2hyaXM** [comment]
Exactly! Maybe add users.php (example) to the documentation:
<?php
     $config = [
         'Auth.Identifiers.Password.fields.username' => 'email'
     ];

return $ config;

**Comment by rochamarcelo** [comment]
Have you checked this https://github.com/CakeDC/users/blob/master/Docs/Documentation/Authentication.md#identifiers ?
