### ISSUE TITLE
Can't access the users management (index, add, edit, ...)

### ISSUE THREAD

**Issue by zsfoto** [CakeDC/users#874]
Hello,

I recently installed CakePHP 4 and CakeDC. How do I access user management? 
So far it was like /users/users, now how?

Regards, Zsolt

**Comment by dmartuszewski** [comment]
Hi @zsfoto !

First you should check if the plugin loaded routes correctly.
You can do this by running `./bin/cake routes`

There should be line like:
`cakedc/users.users:_action            | /users/:action/*`

Try to open
`https://yourlocaldomain.test/users/index`

Ommiting the `index` in the url won't work there:
`https://yourlocaldomain.test/users` - that won't work

Does it helped?

**Comment by zsfoto** [comment]
Hi @dmartuszewski!

Thank your help.
The **`/users/index`** is work. Thank you very much. But the **`/users`** doesn't show index.

This is the one line of **`cake routes`**:
```
+---------------------------------------+-------------------------------------------+--------------------------------------------------------------------------------------+
| Route name                            | URI template                              | Defaults                                                                             |
+---------------------------------------+-------------------------------------------+--------------------------------------------------------------------------------------+
...
| cakedc/users.users:_action            | /users/:action/                           | {"action":"index","controller":"Users","plugin":"CakeDC\/Users"}                     |
+---------------------------------------+-------------------------------------------+--------------------------------------------------------------------------------------+

```
