### ISSUE TITLE
404 pages redirect to /login

### ISSUE THREAD

**Issue by impronta48** [CakeDC/users#875]
Hi,
I've got a strange behaviour on CakePHP 4.

When in my page I have a resource which is not existing, eg
`http://drupalvm.test/img/favicon.png`

Instead of getting a simple 404 I get redirected to /login
This causes a lot of traffic in a page with some missing resources,
How do I get the 404 page avaiable to anonimous users?

I've tried, the following in permissions.php with no luck
      [
            'role' => '*',
            'controller' => ['Pages', 'Events','Sitemap',**'Error'**],
            'action' => '*',
            'bypassAuth' => true,
        ],

thanx
Massimo

**Comment by dmartuszewski** [comment]
Hi @impronta48 

Try changing the role line to:
```
'role'' => '*',
```

Does it helped?

**Comment by impronta48** [comment]
It's is as you suggest, the copy-paste removed the * (sorry!)
Anyway it does not work.

Thanks
Massima

**Comment by Y2hyaXM** [comment]
If you have DebugKit enabled, try adding in permissions.php
```
[
             'role' => '*',
             'plugin' => 'DebugKit',
             'controller' => '*',
             'action' => '*',
             'bypassAuth' => true,
]
```
In my case, there were no redirects after this change. If it doesn't work, check the PHP version.

**Comment by impronta48** [comment]
I solved this adding a final rule
    //Open Pages
    [
      'role' => '*',
      'prefix' => false,
      'controller' => '*',
      'action' => '*',
      'bypassAuth' => true,
    ],

which should be evaluated as the last rule.

**Comment by inigoflores** [comment]
@impronta48 thanks! However, this only worked for me after removing the extra spaces surrounding the asterisk in role and controller:

        [
            'role' => '*',
            'prefix' => false,
            'controller' => '*',
            'action' => '*',
            'bypassAuth' => true,
        ],

**Comment by rochamarcelo** [comment]
Be careful with this. You may forgot to add permission to a restricted. I recommend to add permissions for at least to specific controllers.

**Comment by inigoflores** [comment]
@rochamarcelo thanks for the warning. You are right, this essentially defaults to allowing bypassing all authentication, so it should be avoided. 

Do you have a workaround for  the problem described here?

**Comment by rochamarcelo** [comment]
Yes. 

Create a custom unauthorizedHandler https://github.com/CakeDC/users/blob/11.next-cake4/Docs/Documentation/Authorization.md#authorization-middleware  based on https://github.com/CakeDC/users/blob/11.next-cake4/src/Middleware/UnauthorizedHandler/DefaultRedirectHandler.php 

On the new class add a custom logic to check Controller::isAction with ControllerFactory
