### ISSUE TITLE
register event on user

### ISSUE THREAD

**Issue by tgoeminne** [CakeDC/users#884]
Can anyone point out how to register event on User, is this correct? If so is there a list of events that one can use?

public function implementedEvents()
    {
        return [
            'Model.Users.afterRegister' => 'Dosomething',
        ];
    }

**Comment by steinkel** [comment]
Hi @tgoeminne you have a list of the implemented events by the plugin here https://github.com/CakeDC/users/blob/master/Docs/Documentation/Events.md please check that file for a specific example about how to use an `EVENT_BEFORE_REGISTER`

Thanks,

**Comment by tgoeminne** [comment]
Can you use this:
userlistener.php ...

    public function implementedEvents()
    {
        return [
            'Model.Users.afterRegister' => 'afterRegister',
        ];
    }

Or do you also need to specify the plugin before model, eg Users.Model.Users... ? Or you can not tie your event to models in plugins?

I have this:

 use App\Event\UserListener;
$user = new UserListener();
$this->getEventManager()->on($user);

**Comment by tgoeminne** [comment]
Ok I forgot you still need to fire the event if you do it that way. Will have a look and see what I come up with..

**Comment by tgoeminne** [comment]
Do I need to change it like so? I don't think it works...

public function implementedEvents()
{
    return [
'Users.Global.afterRegister' => 'dosomething',
];

}
