### ISSUE TITLE
event problem

### ISSUE THREAD

**Issue by tgoeminne** [CakeDC/users#885]
Pointing out that the documentation says: 

Plugin::EVENT_BEFORE_REGISTER

but in the vendor code it is written:

UsersAuthComponent::EVENT_AFTER_REGISTER

Should it not be same as in the vendor code in the documentation?

**Comment by tgoeminne** [comment]
$event = $this->dispatchEvent(UsersAuthComponent::EVENT_AFTER_REGISTER, [
            'user' => $userSaved
        ]);

I see this in vendor code. My listener is:

public function implementedEvents()
    {
        return [
            'UsersAuthComponent::EVENT_AFTER_REGISTER' => 'afterRegister',
        ];
    }

Nothing happens.

**Comment by tgoeminne** [comment]
Users.Component.UsersAuth.afterRegister

This is what the documentation should show... guess it dates back to when the stuff was not yet in traits components and all ...

**Comment by steinkel** [comment]
Documentation could be outdated, we'll check it and update it, also if you see something wrong pull requests are very welcome, thanks!
