### ISSUE TITLE
[solved partially]Login page (and others) (re)loads infinite

### ISSUE THREAD

**Issue by ironbone** [CakeDC/users#890]
The situation to see the problems.
PHP 7.4

Create cakephp projekt:
`composer create-project --prefer-dist cakephp/app:~4.0 UserTest`
`cd UserTest`
`composer require cakedc/users`
add
`$this->addPlugin(\CakeDC\Users\Plugin::class);`
to the Application.php
`php bin/cake.php migrations migrate -p CakeDC/Users`

Open the main page of the project in the browser.
The page never stops to load. You can see also in the Inspect Element  -> Network that the page loaded and loader repeating all the parts of the page.

**Comment by ironbone** [comment]
The problem is that this plugin does not work well in the debug mode.
 It is not compatible with the debug_kit. Looks like a problem with loading of some Java Script

**Comment by steinkel** [comment]
We've released 9.0.3 in order to incorporate these fixes into a release. thanks!
