### ISSUE TITLE
After login redirect in sub-directory

### ISSUE THREAD

**Issue by pitocms** [CakeDC/users#892]
I am using cakephp version 4.x
and project location in localhost/cakedc 

I have added plugin in application.php using below code 

```
public function bootstrap(): void
 {

        parent::bootstrap();

        $this->addPlugin(\CakeDC\Users\Plugin::class,['routes' => true, 'bootstrap' => true]);

        Configure::write('Users.config', ['users']);

        Configure::write('Auth.loginRedirect', ['plugin' => null, 'controller' => 'Users', 'action' => 'index']);
}
```

I have create a file in confiq/users.php add added confiq setting

```
$config = [
    // default configuration used to auto-load the Auth Component, override to change the way Auth works
    'Auth' => [
        'Authentication' => [
            'serviceLoader' => \CakeDC\Users\Loader\AuthenticationServiceLoader::class
        ],
        'AuthenticationComponent' => [
            'load' => true,
            'loginRedirect' => '/users/index',
            'requireIdentity' => false
        ],
    ],
   
]; 
```

After go in URL localhost/cakedc login page coming 
After login success it's redirecting localhost/deshboard 
But it should go in localhost/cakedc/users/index 

How can I redirect it in  localhost/cakedc/users/index  ?

**Comment by steinkel** [comment]
Use the `Users.Authentication.afterLogin` https://github.com/CakeDC/users/blob/master/Docs/Documentation/Events.md to decide where to go after login based on your app logic. Thanks,
