### ISSUE TITLE
"Login" issues after moving default assets path

### ISSUE THREAD

**Issue by Xbirdfr** [CakeDC/users#901]
On a fresh CakePHP & CakeDC Users, i got this on console :

![1600975834](https://user-images.githubusercontent.com/6831298/94191498-e00d8080-fead-11ea-9836-69dbf2f3da2f.png)

Thoses are file actually not availble (return 404 because they don't existe yet on folder, but are declared in html code)

My app.php config file is edited on assets path : 

`'imageBaseUrl' => 'assets/img/',
        'cssBaseUrl' => 'assets/',
        'jsBaseUrl' => 'assets/',`

I was able to fix the error by add this on permissions.php :  

`[
            'role' => '*',
            'controller' => 'Assets',
            'action' => '*',
            'bypassAuth' => true,
        ],`

**Comment by steinkel** [comment]
Interesting... the AssetsController should not require authentication either way. There could be an issue with the order of loading middlewares in the application, loading the authentication BEFORE assets and causing this issue, could you please check if this is the root cause?

**Comment by Xbirdfr** [comment]
I was not able to reproduce again this issue, maybe I was misconfigurated something last time.
