### ISSUE TITLE
How can I access CakeDC/users from under the admin prefix too?

### ISSUE THREAD

**Issue by zsfoto** [CakeDC/users#903]
To whom it may concern!

I would like to ask how can I access CakeDC/users from under the **admin prefix too**?
Registration, password change, etc. be accessible from the home page without prefix. This is OK.
I have created my own templates (after CakeDC templates) and it works well without prefix.
Some template (index, add, edit, view) would be good if it was available under the admin prefix.
how it's works?
Thanks

**Comment by steinkel** [comment]
The plugin provides a basic routing configuration, that you could change in your application to map a different set of routes to point the plugin controllers or your own controllers. You just need to add the routes needed in your application and add a `prefix=>'Admin` to the route param to enable prefix routing.
