### ISSUE TITLE
Unable to extend MiddlewareQueueLoader

### ISSUE THREAD

**Issue by T0mats0** [CakeDC/users#919]
This is a (multiple allowed):

* [x] bug
* [] enhancement
* [ ] feature-discussion (RFC)

* CakeDC Users Version: 
* Platform and Target: PHP

### What you did
I created a class that extended MiddlewareQueueLoader. So I could overload the loadAuthenticationMiddleware method.
```php
class MiddlewareQueueLoader extends CakeDCMiddlewareQueueLoader
{
}

```

### What happened
I was not able to extend the class because what I tried to overload was this:

/**
     * Load authentication middleware
     *
     * @param \Cake\Http\MiddlewareQueue $middlewareQueue queue of middleware
     * @param \CakeDC\Users\Plugin $plugin Users plugin object
     * @return void
     */
    protected function loadAuthenticationMiddleware(MiddlewareQueue $middlewareQueue, AuthenticationServiceProviderInterface $serviceProvider)
    {
         ///make my middleware with my own service provider
    }

### What you expected to happen
I expected to  be able to pass my own AuthenticationServiceProviderInterface on AuthorizationServiceProviderInterface and was not able to do so.

What I tried doesn't work because of course you can't change the type hints in strict mode. What would be nice is if this class were changed to use the interfaces on the Plugin class instead of the concretion -- Plugin. So I can overload these methods with my own code.

I would propose to make two classes that do what the plugin is doing and pass those in to the MiddlewareQueueLoader and remove the code from the Plugin class.

I consider this a bug, because interfaces were made but not used where they really would have been useful.

**Comment by rochamarcelo** [comment]
@T0mats0 Could you send a pull request for it?

**Comment by T0mats0** [comment]
Yes, I'll make a PR.

**Comment by T0mats0** [comment]
I've created a PR for this issue.

**Comment by rochamarcelo** [comment]
Closing, PR was created
