### ISSUE TITLE
Unable to set a user's role different to 'user' on registration

### ISSUE THREAD

**Issue by mproenza** [CakeDC/users#921]
When I register a new user using `RegisterTrait` I seem to be UNABLE to set the user's role to something different to the default one (*'user'* is the one  built-in).

I can see at least one case when it would be valid to automatically set a role for the user on registration: when I have multiple possible roles for my users and a user can register herself! - very common I guess?

In my case, I want to have a page dedicated for *retailers* registration at */retailers/signup*. I want all successful registrations to end up with the *'retailer'* role immediately after registration.

So far I have tried with a hidden field in the form (not recommended?) and with the beforeMarshal in my `Table` class. Non of these seem to work and the user always ends up with the *'user'* role.

Is it impossible by design of the plugin or am I missing something? How can I achieve that?

Thanks a lot for your help in advance.

**Comment by mproenza** [comment]
Looking further into this issue, I noticed that line 72 in `CakeDC\Users\Model\Behavior\RegisterBehavior` sets the user's role based on the default role, AFTER the entity has been patched in the previous instruction.

This piece of code will never let the user get a role other than the default:

    $user = $this->_table->patchEntity(
            $user,
            $data,
            ['validate' => $validator ?: $this->getRegisterValidators($options)]
        );
    $user['role'] = Configure::read('Users.Registration.defaultRole') ?: 'user'; 

Last line is line #72 

The code in `CakeDC\Users\Model\Behavior\RegisterBehavior` continues until it saves the entity, never giving the opportunity to set the role of the user in a custom way.

**Comment by rochamarcelo** [comment]
@mproenza with the current code you would need to overwrite the config 'Users.Registration.defaultRole' in your controller action OR add a custom logic in beforeSave method.

**Comment by mproenza** [comment]
Hi @rochamarcelo, thanks a lot for your suggestions.

Yes, adding custom logic in my beforeSave() method did it for me! Thanks. Closing this issue then.
