### ISSUE TITLE
I do not access protected actions

### ISSUE THREAD

**Issue by SandroNigro** [CakeDC/users#926]
My working environment:
CakePHP - versione 4.1.0
CakeDC/Users - 9.0.4

In my example there are two controllers: "Playgrounds" and "Bookings". In the permission.php file I configure:
    [
      role' => '*',
      controller' => 'Playgrounds',
      action' => ['index', 'view'],
      bypassAuth' => true,
    ]

Each actions in Playgrounds controller, e.g. http://MY_PATH/Playgrounds/{action} everything works correctly.
Then, if I want to access: http://MY_PATH/Bookings/add/param1, I get the login, and in the URL there is: http://localhost/MY_PATH/login?redirect=http%3A%2F%2Flocalhost%2Fbookings%2Fadd%2Fparam1.
After login, I'm redirected to the home page, "/MY_PATH". If I want to access http://MY_PATH/Bookings/add/param1 I will be redirected to the XAMPP home page.
Please help me understand where I am going wrong?
Thank you and sorry for the disturbance.

**Comment by rochamarcelo** [comment]
@SandroNigro  you need to add a permission at config/permissions.php, something like 
```
[
    role' => 'admin',
    controller' => 'Bookings',
    action' => ['add'],
]
```

**Comment by SandroNigro** [comment]
Thank you for your answer.
If I modify the "permission.php" file as you tell me, I lose the initial part of the URL. For example, after login the URL is: http://localhost/bookings/add/2020-11-10 while it should be http://localhost/MY_PATH/bookings/add/2020-11-10. 
Another question, should I define the "user" as "admin"? Can I use another role?
Thanks for your patience...

**Comment by rochamarcelo** [comment]
@SandroNigro You can use any value for 'role', of course it should match the values save in your table (users). About the url path it seems that you need to update the config 'App.baseUrl' in config/app_local.php or config/app.php to match  your MY_PATH

**Comment by SandroNigro** [comment]
The same thing, if I change the baseUrl, nothing changes after login. Even if I change the .htaccess file, the redirect does not contain the initial part of the URL.
**Thank you very much.**

**Comment by rochamarcelo** [comment]
@SandroNigro What value you have defined in App.baseUrl?  Try something like `http://localhost/my/path/`

**Comment by SandroNigro** [comment]
In this case I obtain: http://localhost/http:/localhost/MYPATH/login?redirect=http%3A%2F%2Flocalhost%2FMYPATH%2Fplaygrounds%2Fcalendar%2F1.
Sigh

**Comment by rochamarcelo** [comment]
It seems you are missing one '/', you used http:/ instead of http://

**Comment by SandroNigro** [comment]
Thank you for your answer.
My baseUrl is: http://localhost/path/. Now I can't access any resources. If I access any resource, the URL becomes:
http://localhost/http:/localhost/path/login?redirect=http%3A%2F%2Flocalhost%2Fpath%2Fplaygrounds%2Fview%2F1

The single "/" is not me who enters it.

**Thank you very much.**

**Comment by rochamarcelo** [comment]
@SandroNigro I can't use XAMPP. Do you still have issue after performing a valid login at '/login'? Have you tried to test using `bin/cake server` ?

**Comment by SandroNigro** [comment]
With "/bin/cake server" and "baseUrl" I can log in, but if I want to access a protected resource, I will always be redirected to /index.php
Thanks

**Comment by SandroNigro** [comment]
I think it is a web server configuration/setting problem. Thank you for your support.
