### ISSUE TITLE
Add Validators t

### ISSUE THREAD

**Issue by zhkuskov** [CakeDC/users#927]
Hello, thanks for your plugin! The ability to add a validator to the CakeDC.Users model for registration is missing. This solution: [Extending the Plugin](https://github.com/CakeDC/users/blob/master/Docs/Documentation/Extending-the-Plugin.md#extending-the-model-tableentity) - doesn't fit. Because I'm fine with the model and controller from the plugin. In addition, when updating the plugin, you can change the model code. Also, adding a validator will not work using the Users.Global.beforeRegister event - because event result should only be user entity

**Comment by rochamarcelo** [comment]
Hi @zhkuskov I don't see how you would add validator without extending plugin's model UsersTable. 

Could you give more details of your use case?

**Comment by ajibarra** [comment]
Closing this because it has no response since 2020
