### ISSUE TITLE
Deprecated warning for config keys `expire` and `httpOnly` on logout and remember me login

### ISSUE THREAD

**Issue by LordSimal** [CakeDC/users#930]
CakeDC Version:  9.1.0
CakePHP Version: 4.2.1
PHP Version: 7.4.13

The following deprecated warning shows when doing one of the following 2 actions:

- Login with the "Remember me" checkbox enabled
- Logout

## The message
```
Deprecated (16384): Config key `expire` is deprecated, use `expires` instead. - 
<my-path>/httpdocs/vendor/cakephp/authentication/src/Authenticator/CookieAuthenticator.php, line: 197
Deprecated (16384): Config key `httpOnly` is deprecated, use `httponly` instead. - 
<my-path>/httpdocs/vendor/cakephp/authentication/src/Authenticator/CookieAuthenticator.php, line: 197
```

## When did this start to occur?
After I updated the cakephp authentication and authorization plugin
```
  - Upgrading cakephp/authentication (2.3.1 => 2.4.0)
  - Upgrading cakephp/authorization (2.0.5 => 2.1.0)
```

## What is the cause?
The new `cakephp/authentication` 2.4.0 release deprecated these 2 keys
See https://github.com/cakephp/authentication/releases/tag/2.4.0

I copied the whole `vendor/cakedc/users/config/users.php` to my `config/users.php` and adjusted just the values I needed.
The problem here is the fact, that configs are merged together from the vendor config and my "custom" config.

Since the vendor config in `vendor/cakedc/users/config/users.php` still has the deprecated array keys present this warning shows.
https://github.com/CakeDC/users/blob/master/config/users.php#L95-L96
https://github.com/CakeDC/users/blob/master/config/users.php#L153-L154

**Comment by steinkel** [comment]
Fixed by #934
