### ISSUE TITLE
Extending controller breaks some routes

### ISSUE THREAD

**Issue by connect232** [CakeDC/users#945]
When I use a custom controller to override certain functions from the plugin, I get a routing error when trying to reset password, which hasn't been overridden on line 61 of the UserValidationTrait.php file under CakeDC\Users\Controller\Traits. From what I can see the line of code is trying to redirect to changePassword action of the CakeDC/Users plugin but the routes defined in the plugin are created using the controller entered in my applications users.php file, so in effect the route ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'changePassword'] doesn't exist.

In the version for CakePHP 3, the routes file contained

Router::plugin('CakeDC/Users', ['path' => '/users'], function ($routes) {
    $routes->fallbacks('DashedRoute');
});

which would always match the route ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'changePassword'] I believe. This would allow me to override certain functions but leave others going through the plugin.

Maybe I am missing something but I see the routes file has been updated but the redirect links in the plugin don't seem to have been updated accordingly.

Let me know what you guys think.

**Comment by challgren** [comment]
All the actions for the UsersController can be found in https://github.com/CakeDC/users/tree/master/src/Controller/Traits. Use the one you need or use them all. But that will fix your routes if you are using a custom controller.

**Comment by connect232** [comment]
Adding the following code to the routes file solved it for me

$routes->plugin('CakeDC/Users', ['path' => '/users'], function (RouteBuilder $builder) {
    $builder->fallbacks('DashedRoute');
});
