### ISSUE TITLE
Recaptcha on registration page

### ISSUE THREAD

**Issue by connect232** [CakeDC/users#946]
I have added my recaptcha keys to users.php and enabled recaptcha to appear on the registration page but the field g-recaptcha-response is missing from the post data, so I keep getting the Invalid Recaptcha error message.

Does anybody know why this is happening please?

**Comment by steinkel** [comment]
Are you using re-captcha keys for v2?

Please check the generated HTML for the registration page to ensure the recaptcha related fields are attached. Please also check recaptcha is enabled in configuration.

Note: it helps to point out the specific version of the plugin used, I assume we're talking about 9?

**Comment by ajibarra** [comment]
Closing this because we have no response since 2021
