### ISSUE TITLE
Google Social Login issue

### ISSUE THREAD

**Issue by monjon** [CakeDC/users#952]
I am trying to add google authentification using Social Authentication following the documentation provided here: https://github.com/CakeDC/users/blob/master/Docs/Documentation/Installation.md
Each time I am running the command: `bin/cake users addSuperuser`
 I have the following error:

> [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value in .../vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39

Thanks for your help

**Comment by rochamarcelo** [comment]
This happens when you have a custom table without auto unique id.
