### ISSUE TITLE
Overriding the default configuration not working

### ISSUE THREAD

**Issue by abarkhuysen** [CakeDC/users#960]
This plugin is really useful, and I need two login endpoints for my application. Each endpoint with its own layout and template, and I'm having a hard time overriding the **'Auth.Authenticators.Form.loginUrl'** config key. I follow the documentation here [Overriding the default configuration](https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md#overriding-the-default-configuration). This sample however seems outdated as plugins are loaded from Application.php and not bootstrap.php.

I'm using the following versions:
CakePHP v4.2.0
CakeDC/Users V9.1.0

My files:
routes.php
```
$routes->scope('/', function (RouteBuilder $builder) {
    $builder->connect('/nafc', ['controller' => 'MyUsers', 'action' => 'nafc']);
    ....
    $builder->fallbacks();
}
```

Application.php
```
// Load custom users.php config file
Configure::write('Users.config', ['users']);
$this->addPlugin(\CakeDC\Users\Plugin::class);
Configure::write('Auth.Authenticators.Form.loginUrl', ['/login', '/nafc']);
```

MyUsersController.php
```
public function nafc()
{
        $this->viewBuilder()->setLayout('nafc');
        $this->request->allowMethod(['get', 'post']);
        $result = $this->Authentication->getResult();

        debug($result);
}
```

MyUsersController.php **debug** result, as you can see the loginUrl is still the CakeDC/users plugin default and not the newly set URLs.
```
APP/Controller/MyUsersController.php (line 142)
object(Authentication\Authenticator\Result) id:0 {
  protected _status => 'FAILURE_OTHER'
  protected _data => null
  protected _errors => [
    (int) 0 => 'Login URL `http://localhost:8765/nafc` did not match `CakeDC/Users` or `Users` or `login` or ``.',
  ]
}
```

I read a replay to issue #948 stating **"Then you can override specific items in your Application::pluginBootstrap function after the plugin is configured."** but I'm not sure how to do this.

Any help will be really appriciated!

**Comment by abarkhuysen** [comment]
This was totally and utterly my own lack of troubleshooting that led me to open this "issue".
I apologize to the CakeDC team and will close this "issue". Sorry again.

**Comment by steinkel** [comment]
Hey, no problem at all!

Post here your actual issue, it would help others stuck in a similar situation.

Thanks!
