### ISSUE TITLE
Cakedc/users extending endless redirect

### ISSUE THREAD

**Issue by mokiwaa** [CakeDC/users#969]
I have create a new cakephp 4 project and install arodu/cakelte and cakedc/users. I have follow the doc for extending the cakedc/users plugin and create model, table and controller exactly as the doc say, but when i access the main page or login page I get an error 414 with the message “Submitted URI too large!”. if I use just the default controller in config/users.php, all work fine.

**Comment by rochamarcelo** [comment]
@mokiwaa you need to update the rules in you file config/permissions.php. If you don't have one you can copy from https://github.com/CakeDC/users/blob/master/config/permissions.php

**Comment by rochamarcelo** [comment]
Also, check the updated doc page https://github.com/CakeDC/users/blob/master/Docs/Documentation/Installation.md

**Comment by mokiwaa** [comment]
Thank you for your response and helping me. I have read many time the doc and dont remember anything sugesting to copy  the permission file. The link "Go to permission documentation for more information." are not working.

**Comment by rochamarcelo** [comment]
@mokiwaa here is the permissions documentation https://github.com/CakeDC/users/blob/master/Docs/Documentation/Permissions.md . Keep in mind that you need to have the file config/permissions.php

**Comment by mokiwaa** [comment]
I have make a copy of the file to config/permissions.php, make some modification and is working now... Thks. The purpose of extending the plugin is to set another view layout for the login (not the login.php view form page but the main layout).

**Comment by rochamarcelo** [comment]
Good to hear that is working.
