### ISSUE TITLE
Cake\Routing\Exception\MissingRouteException for url's generated by Url helper in layout

### ISSUE THREAD

**Issue by C8Robin** [CakeDC/users#983]
Navigation in my layout builds urls using the Url builder.
#958 and #935 seem similar, but not exactly, although #935 mentions also view building links seems to cause the issue.

When attempting to render a page as a **non logged-in user**, I get a MissingRouteException for those urls that the layout is asking the Url helper to build.

I noticed that the routes being requested include 'plugin'=> 'CakeDC/Users' ; I assume this is the case because the user is not yet logged in. See example below, no route requested with plugin reference.

Would expect a Url->build(...) request to work in a layout, as I am not asking to execute that request yet, just build the link. Tried the AuthLink helper, but the result is the same.

### Reproduce 

- by baking a default CakePHP 4 application, 
- and use CakeDC/Users plugin: load plugin, execute migrations and create a superadmin, use default permissions file, didn't use my own auth config file (NO users.php file in config/). So am using plugin as much out of the box as possible.
- Keep the default cakephp layout (default.php), just add a statement somewhere to build a url.
- Note: have a DB with one table (books) and baked everything for 'books'

CakeDC/Users: 11.0.0
CakePHP: 4.3.5

### Layout extract
```
<main class="main">
    <div class="container">
        <?= $this->Url->build(['controller' => 'Books']);?>
        <?= $this->Flash->render() ?>
        <?= $this->fetch('content') ?>
    </div>
</main>
```

### Application.php
```
public function bootstrap(): void
    {
        // Call parent to load bootstrap from files.
        parent::bootstrap();

        if (PHP_SAPI === 'cli') {
            $this->bootstrapCli();
        } else {
            FactoryLocator::add(
                'Table',
                (new TableLocator())->allowFallbackClass(false)
            );
        }

        /*
         * Only try to load DebugKit in development mode
         * Debug Kit should not be installed on a production system
         */
        if (Configure::read('debug')) {
            $this->addPlugin('DebugKit');
        }

        // Load more plugins here
        $this->addPlugin('CakeDC/Users');
    }
```

**Comment by C8Robin** [comment]
Maybe a better workaround for now, is to generate my site nav urls like this:

`<?= $this->Html->link('Books', ['plugin' => false, 'controller' => 'Books'])?>`

This link works, and when not logged in I am redirected to the login page.

Doesn't solve the root cause, and if I would have to do this throughout my application, it would not be very elegant.

**Comment by inlandsailor** [comment]
I am getting the same error on a site using CakeDC/users plugin. The site worked fine on Saturday. I first became aware of the issue on Sunday. 

Prior to this, attempting to access a valid url when not authenticated would redirect to a login page.

**Comment by inlandsailor** [comment]
Confirmed C8Robin's workaround  using HTML helper and including 'plugin' => false works for my situation also. The issue appeared recently for me due to adding HTML helper code on the home.php page.

**Comment by rochamarcelo** [comment]
That's how HtmlHelper and UrlHelper works. They will create url based on current request, if you are accessing a plugin or prefix url they will use the current plugin|prefix. 
To use a non plugin|prefix url you must do what you did `<?= $this->Html->link('Books', ['plugin' => false, 'controller' => 'Books'])?> `  or `<?= $this->Html->link('Books', ['plugin' => false, 'prefix' => false, 'controller' => 'Books'])?>`
