### ISSUE TITLE
How to limit the access only to some users?

### ISSUE THREAD

**Issue by SandroNigro** [CakeDC/users#989]
I used CakeDC for logging via social (google to be precise). Everything works correctly, but if I want to limit the access to my system only to some users, for example those who are already registered, how can I do it? I haven't found anything that explains this situation. For example, after a user has successfully logged in from social where should I check if this user can access or not?
Thank you very much.

**Comment by rochamarcelo** [comment]
Hi @SandroNigro  you will need to extend the behavior https://github.com/CakeDC/users/blob/master/src/Model/Behavior/SocialBehavior.php#L68 and probably create a custom users table too.

**Comment by SandroNigro** [comment]
Thank you for your response. I will try your advice.
