### ISSUE TITLE
Routes broken

### ISSUE THREAD

**Issue by EronarDiaras** [CakeDC/users#990]
I just noticed that the CakeDCUsers pages aren't working. (only the pages)

config/routes.php:
```
$builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
//$builder->connect('/{controller}', ['action' => 'index', 'plugin' => 'CakeDC/Users', '_ext' => NULL,]);
//$builder->connect('/{controller}/{action}/*', ['plugin' => 'CakeDC/Users', '_ext' => NULL,]);
```

![missin-route](https://user-images.githubusercontent.com/7106113/157655621-e66201f5-3493-46ce-a2a8-3bd13c1de83f.png)

![projects-work](https://user-images.githubusercontent.com/7106113/157655632-bba996e3-1e81-41e8-946d-0fd1fdc9e58f.png)

But if I overwrite the config/routes.php file:
```
$builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
$builder->connect('/{controller}', ['action' => 'index', 'plugin' => 'CakeDC/Users', '_ext' => NULL,]);
$builder->connect('/{controller}/{action}/*', ['plugin' => 'CakeDC/Users', '_ext' => NULL,]);
```

will work:
![missin-route-w](https://user-images.githubusercontent.com/7106113/157656012-d790fbdc-ab7a-40e3-acb5-ba1489e0afe0.png)

its breaks down:
![Clipboard02](https://user-images.githubusercontent.com/7106113/157656284-39dd2893-5692-4a0c-9340-f6ee77ae0425.png)

What is wrong? What makes this possible?

**Comment by EronarDiaras** [comment]
I added these lines to the config/routes.php:
```
$routes->scope('/users/', function (RouteBuilder $builder) {
		$builder->connect('/{controller}', ['action' => 'index', 'plugin' => 'CakeDC/Users', '_ext' => NULL,]);
		$builder->connect('/{controller}/{action}/*', ['plugin' => 'CakeDC/Users', '_ext' => NULL,]);
        $builder->fallbacks();
    });
```
_(Above these lines: "$routes->scope('/', function (RouteBuilder $builder) {")_

And now everything works. But is that a good solution?

**Comment by rochamarcelo** [comment]
@EronarDiaras  It looks like you have a link your layout using `['controller' => 'Projects', 'action' => 'index']`  since the layout is being used for /profile action you must change to something like `['controller' => 'Projects', 'action' => 'index', 'plugin' => false]`

**Comment by EronarDiaras** [comment]
True... Thank you very much!!!
