### ISSUE TITLE
Remember me function not working

### ISSUE THREAD

**Issue by atlet** [CakeDC/users#992]
I crated a new project with CakePHP 4.2 and cakedc/users plugin (9.2). If I login and thick box remember me, cookie is crated but it's not working properly as I get logged out in about an hour (session duration). Any hints where to check what can be wrong? I followed the installation instructions of plugin.

**Comment by rochamarcelo** [comment]
Hi @atlet I just tested with users 9.2.1 and could not reproduce the issue. Have you check if the cookie `CookieAuth` is created with a future expires date?

**Comment by atlet** [comment]
Hi, I think I found the problem. Cookie is setup, but is missing field username, as I don't store any username in table (they are null). I only use email for login (for username). Now I need to find a solution, how to populate this field.

![image](https://user-images.githubusercontent.com/1223162/158607807-8c0ce357-4d4a-4b74-ab25-7c0f56f02ad3.png)

**Comment by atlet** [comment]
Fixed, now it's working great. In users.php was missing this:
Auth.Authenticators.Cookie.fields.username' => 'email',

**Comment by rochamarcelo** [comment]
Updated doc page https://github.com/CakeDC/users/blob/master/Docs/Documentation/Configuration.md#using-the-users-email-to-login

**Comment by rochamarcelo** [comment]
Thank you @atlet

**Comment by rochamarcelo** [comment]
Pull request sent #993 . Thank you.
