### ISSUE TITLE
Auth.authenticate.* removed in 9.* but still used in ProfileTrait

### ISSUE THREAD

**Issue by haraldernst** [CakeDC/users#996]
The config variable `Auth.authenticate.*` was removed in version 9.* but is still used in 

`CakeDC\Users\Controller\Traits\ProfileTrait` 

https://github.com/CakeDC/users/blob/948b7a5fa070e56c29ca382462660c83f29906af/src/Controller/Traits/ProfileTrait.php#L44

If you use the `Auth.authenticate.*`  bootstrap.php triggers a notice.

https://github.com/CakeDC/users/blob/948b7a5fa070e56c29ca382462660c83f29906af/config/bootstrap.php#L29-L41

**Comment by rochamarcelo** [comment]
Changes merged, we can close this issue.
